import type { XunpuAdaptationVariantV4 } from "./types.js";

export const xunpuV4AdaptationVariants: XunpuAdaptationVariantV4[] = [
  {
    variantId: "variant-xunpu-source-triangulation",
    title: "来源三角核验强化场",
    triggerCriterionRefs: ["criterion-fact-verification"],
    triggerEvidenceRule: "事实维度证据充分但低于阈值，且错误集中于来源层级或年度外推。",
    changedEventTemplateRefs: ["evt-year-claim-conflict-early", "evt-similar-repost-added", "evt-researcher-delayed"],
    npcResistance: "研究者先要求学生提交来源层级判断，不直接给答案。",
    evidenceAvailability: "新增一份外观相似的高质量转引，原始来源仍可通过两条路径获得。",
    deadlinePattern: "来源冲突提前到第八分钟，研究者回执延后四分钟。",
    scaffoldingBudget: 2,
    mechanicalDifferenceCount: 4,
    successEvidence: ["学生主动标记转引", "能把主张降级或补证", "不等待 AI 给唯一答案"],
  },
  {
    variantId: "variant-xunpu-consent-negotiation",
    title: "多主体授权协商场",
    triggerCriterionRefs: ["criterion-interview-consent", "criterion-rights-governance"],
    triggerEvidenceRule: "采访或权利维度证据充分但低于阈值，且错误涉及用途、平台、期限或撤回。",
    changedEventTemplateRefs: ["evt-dual-consent-scope", "evt-withdraw-before-publication", "evt-safe-replacement-offer"],
    npcResistance: "两名人物给出不同公开范围，一人只同意文字、一人先同意后撤回。",
    evidenceAvailability: "提供一组可替换手部素材，但需同步字幕和台账。",
    deadlinePattern: "撤回发生在平台预检前三分钟。",
    scaffoldingBudget: 2,
    mechanicalDifferenceCount: 4,
    successEvidence: ["分别记录两名人物范围", "撤回后作品与台账同步", "不强迫同意"],
  },
  {
    variantId: "variant-xunpu-deadline-service",
    title: "限时公共服务连续更新场",
    triggerCriterionRefs: ["criterion-fact-verification", "criterion-editorial-judgment"],
    triggerEvidenceRule: "时效取舍低于阈值，表现为过度等待或未核抢发。",
    changedEventTemplateRefs: ["evt-rumor-early", "evt-official-receipt-delayed", "evt-service-window-shortened"],
    npcResistance: "公共联络员不提前给结论，只给确认时点和已知服务事项。",
    evidenceAvailability: "正式回执延迟，但现场服务信息可由两项独立证据确认。",
    deadlinePattern: "安全传言提前到第十二分钟，首个服务窗口缩短五分钟。",
    scaffoldingBudget: 1,
    mechanicalDifferenceCount: 4,
    successEvidence: ["区分已知与未知", "给出下次更新时间", "快讯与深度稿版本分离"],
  },
  {
    variantId: "variant-xunpu-editorial-independence",
    title: "隐性商业交换判断场",
    triggerCriterionRefs: ["criterion-editorial-judgment"],
    triggerEvidenceRule: "编辑独立性证据充分但低于阈值，且存在未披露合作或流量替代公共价值。",
    changedEventTemplateRefs: ["evt-indirect-placement-request", "evt-editor-traffic-incentive", "evt-community-framing-review"],
    npcResistance: "商户不直接要求广告，而以独家素材和提前发布窗口施加隐性交换。",
    evidenceAvailability: "素材权利本身清楚，但编辑利益关系需要学生主动识别和披露。",
    deadlinePattern: "独家素材有效期与编辑催办同时到达。",
    scaffoldingBudget: 1,
    mechanicalDifferenceCount: 4,
    successEvidence: ["识别隐性交换", "披露素材来源", "标题和正文保持独立", "能解释拒绝成本"],
  },
];
