import type { XunpuArtifactBlueprintV4 } from "./types.js";

export const xunpuV4Artifacts: XunpuArtifactBlueprintV4[] = [
  {
    artifactId: "artifact-topic-brief",
    title: "选题工单",
    artifactKind: "topic_brief",
    editableFields: [
      { fieldId: "angle", label: "报道角度", valueKind: "text", minimumLength: 24, maximumLength: 320 },
      { fieldId: "audience", label: "核心受众", valueKind: "text", minimumLength: 8, maximumLength: 160 },
      { fieldId: "public_value", label: "公共价值", valueKind: "text", minimumLength: 24, maximumLength: 320 },
      { fieldId: "risk_plan", label: "风险、时间和放弃条件", valueKind: "text", minimumLength: 24, maximumLength: 480 },
    ],
    completionChecks: ["不把簪花围简化为猎奇视觉", "明确公众问题", "有时间预算和放弃条件"],
    evidenceRequirements: ["编辑工单引用", "至少一条文化来源", "建议取舍记录"],
    artifactCompletionIsNotCompetencyScore: true,
  },
  {
    artifactId: "artifact-source-matrix",
    title: "信源矩阵",
    artifactKind: "source_matrix",
    editableFields: [
      { fieldId: "claims", label: "主张—证据图", valueKind: "claim_graph", minimumLength: 1, maximumLength: 120 },
      { fieldId: "source_levels", label: "原始来源、转引和人物经验", valueKind: "text", minimumLength: 80, maximumLength: 1800 },
      { fieldId: "conflicts", label: "冲突和待核项", valueKind: "text", minimumLength: 24, maximumLength: 900 },
    ],
    completionChecks: ["至少三类立场", "区分原始来源和转引", "每项主张有状态"],
    evidenceRequirements: ["knowledgeRef 与 locator", "核验行动", "状态变化收据"],
    artifactCompletionIsNotCompetencyScore: true,
  },
  {
    artifactId: "artifact-interview-plan-log",
    title: "采访提纲与对话记录",
    artifactKind: "interview_plan_and_log",
    editableFields: [
      { fieldId: "questions", label: "自写问题与追问", valueKind: "text", minimumLength: 80, maximumLength: 1800 },
      { fieldId: "dialogue_refs", label: "真实 NPC 对话引用", valueKind: "text", minimumLength: 40, maximumLength: 1600 },
      { fieldId: "consent", label: "公开、匿名和删题边界", valueKind: "rights_table", minimumLength: 1, maximumLength: 80 },
    ],
    completionChecks: ["有开放问题和证据追问", "用途和公开范围明确", "记录拒答、承诺或删题"],
    evidenceRequirements: ["NPC 回答", "学生追问", "同意或匿名回执"],
    artifactCompletionIsNotCompetencyScore: true,
  },
  {
    artifactId: "artifact-fact-check-sheet",
    title: "事实核查表",
    artifactKind: "fact_check_sheet",
    editableFields: [
      { fieldId: "fact_items", label: "事实、支持、反证和置信", valueKind: "claim_graph", minimumLength: 1, maximumLength: 120 },
      { fieldId: "final_wording", label: "最终限定措辞", valueKind: "text", minimumLength: 24, maximumLength: 900 },
    ],
    completionChecks: ["事实和待核分开", "年份和客流不跨年度拼接", "安全表述标时点"],
    evidenceRequirements: ["原始来源", "研究者或官方回执", "修订差异"],
    artifactCompletionIsNotCompetencyScore: true,
  },
  {
    artifactId: "artifact-rights-ledger",
    title: "素材权利台账",
    artifactKind: "rights_ledger",
    editableFields: [
      { fieldId: "materials", label: "作者、人物、渠道和元数据", valueKind: "rights_table", minimumLength: 1, maximumLength: 120 },
      { fieldId: "permission_scope", label: "用途、期限、平台和 AI 标识", valueKind: "text", minimumLength: 40, maximumLength: 1200 },
    ],
    completionChecks: ["每项素材有来源", "版权、肖像和个人信息分开", "撤回有替代方案"],
    evidenceRequirements: ["原媒体哈希", "授权或撤回回执", "派生版本引用"],
    artifactCompletionIsNotCompetencyScore: true,
  },
  {
    artifactId: "artifact-feature-story",
    title: "专题稿",
    artifactKind: "feature_story",
    editableFields: [
      { fieldId: "headline", label: "标题", valueKind: "text", minimumLength: 8, maximumLength: 60 },
      { fieldId: "lead", label: "导语", valueKind: "text", minimumLength: 40, maximumLength: 280 },
      { fieldId: "body", label: "正文", valueKind: "text", minimumLength: 480, maximumLength: 3600 },
      { fieldId: "disclosure", label: "来源、合作和 AI 使用披露", valueKind: "text", minimumLength: 20, maximumLength: 800 },
    ],
    completionChecks: ["主张回指信源矩阵", "引语与授权一致", "至少保存 R1 和 R2"],
    evidenceRequirements: ["版本 diff", "claim 引用", "建议取舍"],
    artifactCompletionIsNotCompetencyScore: true,
  },
  {
    artifactId: "artifact-multiplatform-package",
    title: "多平台媒体包",
    artifactKind: "multiplatform_package",
    editableFields: [
      { fieldId: "graphic_summary", label: "图文摘要", valueKind: "text", minimumLength: 80, maximumLength: 600 },
      { fieldId: "audio_cut", label: "音频剪辑与字幕", valueKind: "media_timeline", minimumLength: 1, maximumLength: 80 },
      { fieldId: "video_cut", label: "竖屏视频时间线", valueKind: "media_timeline", minimumLength: 1, maximumLength: 120 },
      { fieldId: "breaking_update", label: "限定性快讯", valueKind: "text", minimumLength: 40, maximumLength: 360 },
      { fieldId: "platform_reason", label: "平台适配理由", valueKind: "text", minimumLength: 40, maximumLength: 600 },
    ],
    completionChecks: ["各平台事实边界一致", "画面与权利台账一致", "快讯标时点和未知项", "媒体可预览"],
    evidenceRequirements: ["原媒体和派生哈希", "ASR/OCR 确认", "平台预检回执"],
    artifactCompletionIsNotCompetencyScore: true,
  },
  {
    artifactId: "artifact-publication-correction-decision",
    title: "发布与更正决定",
    artifactKind: "publication_and_correction_decision",
    editableFields: [
      { fieldId: "publish_scope", label: "版本、渠道、时间和受众", valueKind: "text", minimumLength: 40, maximumLength: 800 },
      { fieldId: "known_unknown", label: "已知、未知和再次更新条件", valueKind: "text", minimumLength: 40, maximumLength: 800 },
      { fieldId: "risk_response", label: "事实、权利和安全处置", valueKind: "text", minimumLength: 60, maximumLength: 1200 },
      { fieldId: "correction", label: "更正、下架或维持决定", valueKind: "text", minimumLength: 40, maximumLength: 1200 },
    ],
    completionChecks: ["发布门有明确版本", "未知项不伪装确定", "更正保留旧版"],
    evidenceRequirements: ["教师门", "平台回执", "受影响 NPC 反馈", "版本链"],
    artifactCompletionIsNotCompetencyScore: true,
  },
  {
    artifactId: "artifact-transfer-reflection",
    title: "迁移反思",
    artifactKind: "transfer_reflection",
    editableFields: [
      { fieldId: "evidence_refs", label: "真实轨迹引用", valueKind: "text", minimumLength: 40, maximumLength: 900 },
      { fieldId: "mistake_or_uncertainty", label: "一次失误或不确定判断", valueKind: "text", minimumLength: 40, maximumLength: 900 },
      { fieldId: "strategy", label: "本场有效或无效策略", valueKind: "text", minimumLength: 60, maximumLength: 1200 },
      { fieldId: "next_action", label: "下一场可执行改进", valueKind: "text", minimumLength: 40, maximumLength: 900 },
    ],
    completionChecks: ["至少两条真实轨迹", "包含失误或不确定", "改进动作可在第二场执行"],
    evidenceRequirements: ["行动引用", "作品版本", "NPC/教师决定和世界后果"],
    artifactCompletionIsNotCompetencyScore: true,
  },
];
