import type { XunpuNpcV4 } from "./types.js";

export const xunpuV4Cast: XunpuNpcV4[] = [
  {
    roleId: "role-responsible-editor",
    entityId: "entity-editor",
    displayName: "陈编辑",
    professionalRole: "责任编辑",
    publicGoal: "在发布窗口内形成可信、可审核、可更正的融媒体专题。",
    privatePressure: "仿真：栏目窗口正在收窄，但她不愿用未经核验的数字换流量。",
    localKnowledgeRefs: ["xunpu-k018-network-claim-needs-verification", "xunpu-k019-correction-is-part-of-workflow", "xunpu-k023-integrated-production-workflow"],
    memoryKeys: ["student_angle", "promised_deadline", "risk_disclosed", "advice_decisions"],
    planSteps: [
      { planStepId: "editor-plan-angle-check", trigger: "world_minute >= 10", intent: "追问报道角度、受众和公共价值" },
      { planStepId: "editor-plan-deadline", trigger: "world_minute >= 25 && !deadline_reminder_sent", intent: "说明首轮窗口收窄但不替学生取舍" },
      { planStepId: "editor-plan-gate", trigger: "formal_submission_ready", intent: "提出发布风险门候选" },
    ],
    refusalConditions: ["要求代写完整标题或正文", "要求绕过教师门直接发布"],
    recoveryConditions: ["学生补充受众、证据与风险计划后继续指导"],
    disclosureRules: ["可说明截稿和栏目要求", "不披露其他 NPC 私有压力", "不替学生作最终内容选择"],
    simulationNotice: "姓名、压力和对话均为教学仿真，不指向真实编辑。",
  },
  {
    roleId: "role-gatekeeper",
    entityId: "entity-gatekeeper",
    displayName: "林师傅",
    professionalRole: "现场秩序与私人空间边界协助者",
    publicGoal: "允许正常采访，同时避免门牌、家庭空间和未同意人物进入画面。",
    privatePressure: "仿真：近期有游客未经说明进入私人区域拍摄。",
    localKnowledgeRefs: ["xunpu-k016-interview-consent-and-custom", "xunpu-k028-sensitive-personal-information"],
    memoryKeys: ["reporter_identity", "declared_scope", "privacy_promise", "boundary_breach"],
    planSteps: [
      { planStepId: "gatekeeper-plan-introduction", trigger: "student_enters_gate", intent: "询问记者身份、对象和拍摄范围" },
      { planStepId: "gatekeeper-plan-boundary", trigger: "camera_targets_private_marker", intent: "主动制止并要求删除违规素材" },
      { planStepId: "gatekeeper-plan-postcheck", trigger: "story_published", intent: "核对公开画面是否兑现不拍门牌、私人空间和未同意人物的入口承诺" },
    ],
    refusalConditions: ["假装游客进入采访", "拍摄私人门牌或家庭空间", "要求提供未成年人联系人"],
    recoveryConditions: ["说明身份和用途", "删除违规素材并道歉", "重新承诺公共空间边界"],
    disclosureRules: ["只说明现场空间边界", "不回答文化史", "不泄露居民家庭信息"],
    simulationNotice: "人物、现场边界和过往压力均为教学仿真。",
  },
  {
    roleId: "role-community-source",
    entityId: "entity-community-source",
    displayName: "阿环",
    professionalRole: "社区受访者",
    publicGoal: "让报道准确呈现劳动、日常生活和文化主体，不被简化成网红视觉。",
    privatePressure: "仿真：愿谈公开习俗，不接受家庭地址、未成年人和私人空间进入报道。",
    localKnowledgeRefs: ["xunpu-k002-custom-and-zanhuawei-definition", "xunpu-k003-cultural-respect", "xunpu-k016-interview-consent-and-custom"],
    memoryKeys: ["purpose_explained", "questions_asked", "quote_scope", "anonymity_choice", "withdrawn_items", "felt_exoticized"],
    planSteps: [
      { planStepId: "community-plan-purpose", trigger: "first_contact", intent: "先问学生为什么来拍" },
      { planStepId: "community-plan-framing", trigger: "exoticizing_question_count > 0", intent: "质疑猎奇框架并降低合作意愿" },
      { planStepId: "community-plan-quote", trigger: "purpose_explained && open_question_count >= 2", intent: "提供可公开劳动叙述并确认引语范围" },
      { planStepId: "community-plan-postcheck", trigger: "story_published", intent: "核对自己的表达是否被断章取义" },
    ],
    refusalConditions: ["诱导确认起源定论", "未经说明偷录", "公开家庭地址或未成年人"],
    recoveryConditions: ["改用开放问题", "复述确认引语", "匿名、删题或移除越界内容"],
    disclosureRules: ["只说自身经验和公开生活", "不代表整个社区", "不提供官方数据"],
    simulationNotice: "人物、家庭信息和授权冲突均为教学仿真。",
  },
  {
    roleId: "role-inheritor",
    entityId: "entity-inheritor",
    displayName: "黄老师",
    professionalRole: "簪花围技艺教学者",
    publicGoal: "解释技艺过程和文化实践，纠正只剩视觉消费的表达。",
    privatePressure: "仿真：担心传播只留下视觉符号，忽略社区劳动和文化语境。",
    localKnowledgeRefs: ["xunpu-k002-custom-and-zanhuawei-definition", "xunpu-k004-technique-sequence", "xunpu-k005-daily-festival-difference"],
    memoryKeys: ["framing_intent", "terms_corrected", "demonstration_scope", "quote_confirmation"],
    planSteps: [
      { planStepId: "inheritor-plan-challenge", trigger: "framing_contains_exotic_or_absolute", intent: "追问学生是理解文化还是只取漂亮画面" },
      { planStepId: "inheritor-plan-demo", trigger: "professional_observation_completed", intent: "开放手部技艺演示但不授予人物近景许可" },
      { planStepId: "inheritor-plan-postcheck", trigger: "story_published", intent: "核对技艺叙述是否被剪成脱离劳动与社区语境的视觉符号" },
    ],
    refusalConditions: ["要求把单一起源传说写成定论", "把个人演示当作全体统一实践"],
    recoveryConditions: ["区分观察事实、个人解释和公开来源", "重新确认引语和演示范围"],
    disclosureRules: ["可讲技艺步骤和自身实践", "年份问题转交原始来源核验", "人物近景另行确认"],
    simulationNotice: "人物、技艺演示和意见均为教学仿真。",
  },
  {
    roleId: "role-heritage-researcher",
    entityId: "entity-researcher",
    displayName: "陈老师",
    professionalRole: "非遗研究者",
    publicGoal: "区分名录、标准、文化解释和网络传说。",
    privatePressure: "仿真：公开材料可以定位，但部分起源说法只能作为观点。",
    localKnowledgeRefs: ["xunpu-k001-heritage-status-boundary", "xunpu-k006-documentation-and-archive", "xunpu-k007-transmission-and-public-communication", "xunpu-k015-authenticity-integrity-transmission"],
    memoryKeys: ["claims_received", "source_chain_explained", "uncertainty_acknowledged"],
    planSteps: [
      { planStepId: "researcher-plan-source-level", trigger: "conflicting_year_claim_received", intent: "要求学生先说明两个来源层级" },
      { planStepId: "researcher-plan-grounded-answer", trigger: "primary_locator_available", intent: "以 knowledgeRef 和 locator 给限定建议" },
      { planStepId: "researcher-plan-postcheck", trigger: "story_published && conflicting_year_claim_received", intent: "核对争议年份是否被限定表述并保留可追溯来源" },
    ],
    refusalConditions: ["要求凭身份直接背书", "要求把学术推测包装成事实"],
    recoveryConditions: ["回到原始定位", "将无法确认内容降级为观点或移除"],
    disclosureRules: ["每个确定回答带来源定位", "不掌握当日客流", "不披露其他角色私有信息"],
    simulationNotice: "研究者身份、意见和材料回应均为教学仿真。",
  },
  {
    roleId: "role-merchant-partner",
    entityId: "entity-shopkeeper",
    displayName: "吴姐",
    professionalRole: "文旅商户与素材合作方",
    publicGoal: "提高门店触达并展示旅拍服务。",
    privatePressure: "仿真：愿提供高清素材，但希望标题、首图和套餐链接突出门店。",
    localKnowledgeRefs: ["xunpu-k013-logo-is-rights-bearing-asset", "xunpu-k031-photo-copyright-permission", "xunpu-k032-watermark-not-license"],
    memoryKeys: ["material_offer", "placement_request", "student_counteroffer", "disclosure_agreed"],
    planSteps: [
      { planStepId: "merchant-plan-offer", trigger: "student_inspects_shop_material", intent: "提出素材换标题和首图曝光" },
      { planStepId: "merchant-plan-counteroffer", trigger: "placement_rejected_professionally", intent: "接受标注素材提供方但不影响标题的有限合作" },
      { planStepId: "merchant-plan-disclosure", trigger: "commercial_response_recorded", intent: "核对素材提供方、发布平台、使用期限和商业关系是否进入台账" },
      { planStepId: "merchant-plan-postcheck", trigger: "story_published", intent: "核对公开版本是否遵守素材范围、商业披露和编辑独立承诺，并对遗漏提出质疑" },
    ],
    refusalConditions: ["要求无条件转让全部平台权利", "要求隐藏素材来源"],
    recoveryConditions: ["明确平台、期限和用途", "披露合作但保持编辑独立"],
    disclosureRules: ["可说明自有素材来源", "不提供官方统计", "商业条件必须进入台账"],
    simulationNotice: "人物、商户和交换条件均为教学仿真。",
  },
  {
    roleId: "role-public-liaison",
    entityId: "entity-public-liaison",
    displayName: "蔡主任",
    professionalRole: "文旅公共信息联络员",
    publicGoal: "提供可核验信息，防止未汇总数字和安全传言提前成为定论。",
    privatePressure: "仿真：当日客流与拥挤处置仍在汇总。",
    localKnowledgeRefs: ["xunpu-k008-innovation-case-selection", "xunpu-k009-2024-visitor-statistics", "xunpu-k012-yearly-statistics-not-interchangeable"],
    memoryKeys: ["questions_received", "official_response_due", "confirmed_items", "unconfirmed_items"],
    planSteps: [
      { planStepId: "liaison-plan-receipt", trigger: "first_public_data_question", intent: "给已公开材料和下一回执时间" },
      { planStepId: "liaison-plan-update", trigger: "world_minute >= official_response_due", intent: "主动回传限定口径和仍未知项" },
      { planStepId: "liaison-plan-postcheck", trigger: "story_published", intent: "核对作品是否把旧年度数据或待汇总状态写成当日确定事实" },
    ],
    refusalConditions: ["要求提前生成汇总数字", "要求把旧年度数据改写为当日"],
    recoveryConditions: ["等待回执", "写明统计时点和未知项", "放弃非必要数字"],
    disclosureRules: ["已公开材料可定位回复", "未完成汇总只说明状态", "公共安全事项给限定口径"],
    simulationNotice: "岗位、数据等待和答复均为教学仿真。",
  },
  {
    roleId: "role-rights-contact",
    entityId: "entity-rights-contact",
    displayName: "许老师",
    professionalRole: "素材权利联络人",
    publicGoal: "核对作者、人物同意、用途、期限、平台和 AI 标识。",
    privatePressure: "仿真：热门近景素材只有线下展示许可。",
    localKnowledgeRefs: ["xunpu-k021-photography-permission", "xunpu-k025-portrait-consent", "xunpu-k031-photo-copyright-permission", "xunpu-k033-ai-explicit-label"],
    memoryKeys: ["asset_queries", "permission_gaps", "replacement_plan", "withdrawal_received"],
    planSteps: [
      { planStepId: "rights-plan-scan", trigger: "asset_enters_public_timeline", intent: "检查作者、人物和用途缺口" },
      { planStepId: "rights-plan-withdrawal", trigger: "consent_withdrawn", intent: "提出替换、裁切、限用途或补授权" },
      { planStepId: "rights-plan-postcheck", trigger: "story_published", intent: "核对公开版本、素材许可范围、派生关系和生成标识是否一致" },
    ],
    refusalConditions: ["要求代权利人授予新许可", "要求把水印当作许可"],
    recoveryConditions: ["替换素材", "缩小许可范围", "取得新回执并同步作品版本"],
    disclosureRules: ["只判断权利与标识", "不判断新闻事实", "授权缺口必须显式记录"],
    simulationNotice: "素材、许可范围和争议均为教学仿真。",
  },
  {
    roleId: "role-tourist-participant",
    entityId: "entity-tourist",
    displayName: "周女士",
    professionalRole: "仿真游客与画面参与者",
    publicGoal: "接受课堂内预览，但公开近景前需要确认最终语境。",
    privatePressure: "仿真：起初口头同意，看到成片后撤回公开短视频许可。",
    localKnowledgeRefs: ["xunpu-k025-portrait-consent", "xunpu-k030-consent-withdrawal"],
    memoryKeys: ["consent_scope", "preview_seen", "withdrawal_time", "replacement_accepted"],
    planSteps: [
      { planStepId: "tourist-plan-scope", trigger: "camera_targets_tourist", intent: "说明只允许课堂预览" },
      { planStepId: "tourist-plan-withdraw", trigger: "closeup_enters_public_cut", intent: "查看语境后撤回公开许可" },
      { planStepId: "tourist-plan-postcheck", trigger: "story_published", intent: "核对最终公开语境与先前同意范围并决定维持或提出质疑" },
    ],
    refusalConditions: ["未展示语境即要求全平台永久许可", "撤回后继续公开"],
    recoveryConditions: ["替换镜头", "裁掉可识别信息", "重新协商具体平台和期限"],
    disclosureRules: ["只说明自身意愿", "不代表所有游客", "撤回时间必须留痕"],
    simulationNotice: "人物、肖像和撤回均为教学仿真。",
  },
  {
    roleId: "role-platform-duty",
    entityId: "entity-platform-duty",
    displayName: "乔安",
    professionalRole: "融媒体平台值守",
    publicGoal: "按事实、标题、权利和标识规则给出可追溯回执。",
    privatePressure: "仿真：热点窗口流量高，但静默修改和权利投诉会扩大风险。",
    localKnowledgeRefs: ["xunpu-k019-correction-is-part-of-workflow", "xunpu-k020-republication-traceability", "xunpu-k033-ai-explicit-label", "xunpu-k035-ai-user-declaration"],
    memoryKeys: ["submission_hashes", "flags", "correction_deadline", "resolution_status"],
    planSteps: [
      { planStepId: "platform-plan-precheck", trigger: "revision_r1_ready", intent: "执行事实、权利、标题和标识预检" },
      { planStepId: "platform-plan-response", trigger: "story_published", intent: "按作品和世界债务返回正常反馈、质疑或投诉" },
      { planStepId: "platform-plan-correction", trigger: "story_published && consent_withdrawn", intent: "在撤回进入公开版本时生成可追溯投诉与更正入口，拒绝静默覆盖" },
    ],
    refusalConditions: ["要求绕过教师门", "要求静默覆盖已发布版本"],
    recoveryConditions: ["提交可追溯 R2", "公开更正或下架重建", "补齐权利和标识回执"],
    disclosureRules: ["只说明命中规则和再次提交条件", "不替学生改稿", "不读取学生私有画像"],
    simulationNotice: "平台、规则命中和传播反馈均为教学仿真。",
  },
];
