import {
  DialogueSceneDefinitionV4Schema,
  DialogueSceneDefinitionV4SchemaVersion,
  type DialogueSceneDefinitionV4,
} from "@ronggang/contracts";
import { hashCanonical } from "../canonical.js";

type SceneDraft = Omit<DialogueSceneDefinitionV4, "definitionHash">;
type DialogueRule = DialogueSceneDefinitionV4["rules"][number];

function rule(input: {
  ruleRef: string;
  priority: number;
  minTurn?: number;
  maxTurn?: number;
  allowedIntents: DialogueRule["allowedIntents"];
  all?: string[];
  any?: string[];
  forbidden?: string[];
  requires?: DialogueRule["issueRequirements"];
  act: DialogueRule["response"]["act"];
  stance: DialogueRule["response"]["stance"];
  text: string;
  prompt: string | null;
  updates?: DialogueRule["issueUpdates"];
  facts?: string[];
  relationship: DialogueRule["relationshipDelta"];
  commitment?: DialogueRule["commitment"];
  time?: number;
  outcome: DialogueRule["outcome"];
  routeRef?: string;
  eventTemplateRef?: string;
  resolutionSummary?: string;
}): DialogueRule {
  return {
    ruleRef: input.ruleRef,
    priority: input.priority,
    minTurn: input.minTurn ?? 1,
    maxTurn: input.maxTurn ?? 7,
    allowedIntents: input.allowedIntents,
    requiredAllSignalRefs: input.all ?? [],
    requiredAnySignalRefs: input.any ?? [],
    forbiddenSignalRefs: input.forbidden ?? [],
    issueRequirements: input.requires ?? [],
    response: {
      act: input.act,
      stance: input.stance,
      publicText: input.text,
      nextPrompt: input.prompt,
    },
    issueUpdates: input.updates ?? [],
    disclosedFactRefs: input.facts ?? [],
    relationshipDelta: input.relationship,
    commitment: input.commitment ?? null,
    timeCostMinutes: input.time ?? 2,
    outcome: input.outcome,
    routeRef: input.routeRef ?? null,
    eventTemplateRef: input.eventTemplateRef ?? null,
    resolutionSummary: input.resolutionSummary ?? null,
  };
}

function scene(draft: SceneDraft): DialogueSceneDefinitionV4 {
  return DialogueSceneDefinitionV4Schema.parse({
    ...draft,
    definitionHash: hashCanonical(draft),
  });
}

function exitRule(prefix: string, publicText: string): DialogueRule {
  return rule({
    ruleRef: `rule-${prefix}-exit`,
    priority: 300,
    allowedIntents: ["exit_conversation"],
    act: "close",
    stance: "cautious",
    text: publicText,
    prompt: null,
    relationship: {
      trust: 0,
      cooperation: 0,
      alertness: 0,
      publicReason: "学生主动结束本轮对话，现场关系保持可恢复。",
    },
    time: 1,
    outcome: "exited",
  });
}

export function hashXunpuDialogueSceneDefinitionV4(
  definition: DialogueSceneDefinitionV4,
): string {
  const { definitionHash: _definitionHash, ...draft } = definition;
  return hashCanonical(draft);
}

const challengeTurns = {
  level3: 7,
  level4: 7,
  level5: 6,
  level6: 5,
  level7: 5,
} as const;

const responseWindows = {
  level3: 15,
  level4: 13,
  level5: 11,
  level6: 9,
  level7: 8,
} as const;

const gatekeeperScene = scene({
  schemaVersion: DialogueSceneDefinitionV4SchemaVersion,
  definitionId: "dialogue-gatekeeper-entry-v4",
  npcRef: "entity-gatekeeper",
  npcRoleRef: "role-gatekeeper",
  topicRef: "topic-community-entry-boundary",
  title: "先说明来意，再争取进入社区",
  objective: "以记者身份协商采访入口，同时保护居民、门牌和私人空间。",
  openingMessage: "林师傅抬手示意你停在巷口：今天游客多，里面也是居民生活区。",
  openingPrompt: "你代表谁来、想采访谁、准备拍到哪里？",
  privateBoundaryHash: hashCanonical({
    simulatedPressure: "近期有游客未经说明进入私人区域拍摄",
    forbiddenDisclosure: ["居民家庭地址", "未成年人联系人", "其他人物私有压力"],
  }),
  localKnowledgeRefs: [
    "xunpu-k016-interview-consent-and-custom",
    "xunpu-k017-multiple-perspectives",
    "xunpu-k028-sensitive-personal-information",
  ],
  allowedIntents: [
    "introduce_scope",
    "ask_open_question",
    "probe_detail",
    "negotiate_terms",
    "set_boundary",
    "accept_condition",
    "repair_breach",
    "exit_conversation",
  ],
  maximumTurnsByChallenge: challengeTurns,
  responseWindowMinutesByChallenge: responseWindows,
  initialRelationship: { trust: 34, cooperation: 32, alertness: 68 },
  issues: [
    {
      issueRef: "issue-gatekeeper-identity",
      publicLabel: "记者身份与采访目的",
      initialStatus: "open",
      requiredForResolution: true,
    },
    {
      issueRef: "issue-gatekeeper-privacy",
      publicLabel: "拍摄范围、知情同意与撤回",
      initialStatus: "open",
      requiredForResolution: true,
    },
  ],
  facts: [
    {
      factRef: "fact-gatekeeper-public-courtyard",
      publicText: "公共院落外沿可以在不拍门牌和未同意人物的前提下观察。",
      knowledgeRefs: ["xunpu-k016-interview-consent-and-custom"],
      disclosureRuleRefs: ["rule-gatekeeper-resolve-public-edge"],
    },
    {
      factRef: "fact-gatekeeper-contact-window",
      publicText: "林师傅可以联系一位愿意先听采访说明的居民，但同意需由本人确认。",
      knowledgeRefs: [
        "xunpu-k016-interview-consent-and-custom",
        "xunpu-k028-sensitive-personal-information",
      ],
      disclosureRuleRefs: ["rule-gatekeeper-resolve-assisted-contact"],
    },
    {
      factRef: "fact-gatekeeper-background-briefing",
      publicText: "若暂不采集可识别素材，林师傅可在巷口进行一次不录音的背景说明，后续主张仍需另找来源确认。",
      knowledgeRefs: [
        "xunpu-k016-interview-consent-and-custom",
        "xunpu-k017-multiple-perspectives",
      ],
      disclosureRuleRefs: ["rule-gatekeeper-resolve-background-briefing"],
    },
  ],
  signals: [
    { signalRef: "signal-gatekeeper-identity", keywordGroups: [["学生记者", "记者", "课程实训", "融媒体"]] },
    { signalRef: "signal-gatekeeper-purpose", keywordGroups: [["采访", "报道", "了解", "记录"]] },
    { signalRef: "signal-gatekeeper-privacy", keywordGroups: [["同意", "隐私", "不拍", "撤回", "门牌"]] },
    { signalRef: "signal-gatekeeper-force", keywordGroups: [["必须进去", "让我进去", "装游客", "偷偷拍"]] },
    { signalRef: "signal-gatekeeper-repair", keywordGroups: [["抱歉", "道歉", "重新说明", "删除"]] },
    { signalRef: "signal-gatekeeper-assisted", keywordGroups: [["联系", "引荐", "愿意受访", "先听说明"]] },
    { signalRef: "signal-gatekeeper-public-edge", keywordGroups: [["公共区域", "院落外沿", "只观察", "不进入"]] },
    { signalRef: "signal-gatekeeper-private-contact", keywordGroups: [["未成年人联系人", "家庭住址", "住哪一户", "门牌和电话"]] },
    { signalRef: "signal-gatekeeper-repair-contact", keywordGroups: [["不索要联系人", "不记录住址", "只在公共区域", "由本人决定"]] },
    { signalRef: "signal-gatekeeper-background", keywordGroups: [["背景了解", "不录音", "不拍摄", "只做背景沟通"]] },
  ],
  rules: [
    exitRule("gatekeeper", "好，你可以先在巷口观察。需要进入时再重新说明来意。"),
    rule({
      ruleRef: "rule-gatekeeper-refuse-force",
      priority: 220,
      allowedIntents: ["probe_detail", "negotiate_terms"],
      all: ["signal-gatekeeper-force"],
      act: "refuse",
      stance: "withdrawn",
      text: "不能把居民生活区当布景，更不能装游客或偷偷拍。你先退回巷口。",
      prompt: "如果你愿意说明身份、删除越界素材并承诺拍摄边界，我会再听一次。",
      updates: [{
        issueRef: "issue-gatekeeper-privacy",
        nextStatus: "contested",
        publicReason: "试图绕过知情同意，现场边界被触发。",
      }],
      relationship: { trust: -18, cooperation: -16, alertness: 24, publicReason: "强行进入损害了信任。" },
      outcome: "refusal",
    }),
    rule({
      ruleRef: "rule-gatekeeper-refuse-private-contact",
      priority: 215,
      allowedIntents: ["probe_detail", "negotiate_terms", "ask_open_question"],
      all: ["signal-gatekeeper-private-contact"],
      act: "refuse",
      stance: "withdrawn",
      text: "我不能替居民交出住址、门牌和未成年人联系方式。采访便利不是索取私人信息的理由。",
      prompt: "如果你愿意停止索取私人联系人，改在公共区域说明用途，并由受访者本人决定，我可以继续听。",
      updates: [{
        issueRef: "issue-gatekeeper-privacy",
        nextStatus: "contested",
        publicReason: "请求超出采访必要范围的私人联系信息。",
      }],
      relationship: { trust: -15, cooperation: -14, alertness: 20, publicReason: "私人信息请求触发现场保护边界。" },
      outcome: "refusal",
    }),
    rule({
      ruleRef: "rule-gatekeeper-repair-private-contact",
      priority: 205,
      allowedIntents: ["repair_breach", "set_boundary", "introduce_scope"],
      all: ["signal-gatekeeper-repair", "signal-gatekeeper-repair-contact"],
      requires: [{ issueRef: "issue-gatekeeper-privacy", allowedStatuses: ["contested"] }],
      act: "acknowledge",
      stance: "cautious",
      text: "你收回了私人信息请求。接下来只能从公共入口开始，任何人物采访都由本人决定。",
      prompt: "你要先做不录音的背景沟通，还是只在公共边缘观察？说明后续怎样补证。",
      updates: [
        { issueRef: "issue-gatekeeper-identity", nextStatus: "satisfied", publicReason: "学生重新说明记者身份和公共目的。" },
        { issueRef: "issue-gatekeeper-privacy", nextStatus: "satisfied", publicReason: "学生停止索取私人信息并恢复本人同意边界。" },
      ],
      relationship: { trust: 8, cooperation: 7, alertness: -9, publicReason: "明确收回越界请求，关系进入谨慎恢复。" },
      outcome: "recovery",
    }),
    rule({
      ruleRef: "rule-gatekeeper-repair",
      priority: 200,
      allowedIntents: ["repair_breach", "set_boundary", "introduce_scope"],
      all: ["signal-gatekeeper-repair", "signal-gatekeeper-privacy"],
      requires: [{ issueRef: "issue-gatekeeper-privacy", allowedStatuses: ["contested"] }],
      act: "acknowledge",
      stance: "cautious",
      text: "愿意停下来修复就好。先把身份、用途和不拍什么说完整。",
      prompt: "你希望只在公共边缘观察，还是请我联系一位愿意受访的居民？",
      updates: [
        { issueRef: "issue-gatekeeper-identity", nextStatus: "satisfied", publicReason: "学生重新说明记者身份与采访用途。" },
        { issueRef: "issue-gatekeeper-privacy", nextStatus: "satisfied", publicReason: "学生删除越界素材并承诺可撤回的知情同意。" },
      ],
      relationship: { trust: 10, cooperation: 8, alertness: -12, publicReason: "主动承认并修复越界。" },
      outcome: "recovery",
    }),
    rule({
      ruleRef: "rule-gatekeeper-establish-scope",
      priority: 120,
      allowedIntents: ["introduce_scope", "set_boundary"],
      all: ["signal-gatekeeper-identity", "signal-gatekeeper-purpose", "signal-gatekeeper-privacy"],
      forbidden: ["signal-gatekeeper-force"],
      act: "clarify",
      stance: "cooperative",
      text: "身份和边界都说清楚了。我可以给你两个不越界的入口，但选择会影响采访深度和时间。",
      prompt: "你选择留在公共区域先观察，还是请我联系愿意受访的居民？为什么？",
      updates: [
        { issueRef: "issue-gatekeeper-identity", nextStatus: "satisfied", publicReason: "采访身份和公共目的明确。" },
        { issueRef: "issue-gatekeeper-privacy", nextStatus: "satisfied", publicReason: "拍摄范围和撤回机制明确。" },
      ],
      relationship: { trust: 10, cooperation: 9, alertness: -10, publicReason: "专业开场降低了现场警惕。" },
      outcome: "clarification",
    }),
    rule({
      ruleRef: "rule-gatekeeper-resolve-assisted-contact",
      priority: 180,
      minTurn: 2,
      allowedIntents: ["ask_open_question", "accept_condition", "negotiate_terms"],
      all: ["signal-gatekeeper-assisted", "signal-gatekeeper-privacy"],
      forbidden: ["signal-gatekeeper-force"],
      requires: [
        { issueRef: "issue-gatekeeper-identity", allowedStatuses: ["satisfied"] },
        { issueRef: "issue-gatekeeper-privacy", allowedStatuses: ["satisfied"] },
      ],
      act: "commit",
      stance: "committed",
      text: "我先替你联系，但是否接受采访由居民本人决定。你在巷口把用途再说一遍。",
      prompt: null,
      facts: ["fact-gatekeeper-contact-window"],
      relationship: { trust: 12, cooperation: 16, alertness: -10, publicReason: "学生选择以明确同意换取更深采访。" },
      commitment: {
        madeBy: "student",
        summary: "接触每位居民前重新说明采访用途并取得本人同意。",
        condition: "不拍门牌、私人空间和未明确同意的人物。",
        dueAfterVirtualMinutes: 10,
      },
      outcome: "resolved",
      routeRef: "dialogue-route-assisted-contact",
      eventTemplateRef: "event-template-gatekeeper",
      resolutionSummary: "林师傅开放受控联系人入口；采访更深入，但需逐人确认并消耗时间。",
    }),
    rule({
      ruleRef: "rule-gatekeeper-resolve-public-edge",
      priority: 170,
      minTurn: 2,
      allowedIntents: ["set_boundary", "accept_condition", "ask_open_question"],
      all: ["signal-gatekeeper-public-edge", "signal-gatekeeper-privacy"],
      forbidden: ["signal-gatekeeper-force"],
      requires: [
        { issueRef: "issue-gatekeeper-identity", allowedStatuses: ["satisfied"] },
        { issueRef: "issue-gatekeeper-privacy", allowedStatuses: ["satisfied"] },
      ],
      act: "commit",
      stance: "cooperative",
      text: "可以。你留在公共边缘做环境观察，不拍门牌和未同意人物；之后再决定是否需要深入。",
      prompt: null,
      facts: ["fact-gatekeeper-public-courtyard"],
      relationship: { trust: 8, cooperation: 10, alertness: -8, publicReason: "学生主动缩小范围，快速获得低风险入口。" },
      commitment: {
        madeBy: "student",
        summary: "只在公共边缘完成不识别个人的环境观察。",
        condition: "需要人物采访时必须重新协商。",
        dueAfterVirtualMinutes: 8,
      },
      outcome: "resolved",
      routeRef: "dialogue-route-public-edge",
      eventTemplateRef: "event-template-gatekeeper",
      resolutionSummary: "学生获得快速但信息较浅的公共区域观察入口。",
    }),
    rule({
      ruleRef: "rule-gatekeeper-resolve-background-briefing",
      priority: 165,
      minTurn: 2,
      allowedIntents: ["ask_open_question", "set_boundary", "accept_condition"],
      all: ["signal-gatekeeper-background"],
      forbidden: ["signal-gatekeeper-force", "signal-gatekeeper-private-contact"],
      requires: [
        { issueRef: "issue-gatekeeper-identity", allowedStatuses: ["satisfied"] },
        { issueRef: "issue-gatekeeper-privacy", allowedStatuses: ["satisfied"] },
      ],
      act: "commit",
      stance: "cooperative",
      text: "我可以在巷口做一次不录音、不拍摄的背景说明。它只能帮你形成问题，不能直接作为公开事实。",
      prompt: null,
      facts: ["fact-gatekeeper-background-briefing"],
      relationship: { trust: 9, cooperation: 9, alertness: -7, publicReason: "学生主动降低采集侵扰并保留后续核验责任。" },
      commitment: {
        madeBy: "student",
        summary: "背景沟通不直接引述、不记录可识别信息，只用于形成后续采访问题。",
        condition: "公开主张必须由本人采访、现场观察或登记来源另行支持。",
        dueAfterVirtualMinutes: 6,
      },
      outcome: "resolved",
      routeRef: "dialogue-route-background-briefing",
      eventTemplateRef: "event-template-gatekeeper",
      resolutionSummary: "学生快速获得现场方向与问题线索，但本轮没有可直接公开的引语或人物素材。",
    }),
    rule({
      ruleRef: "rule-gatekeeper-clarify",
      priority: -100,
      allowedIntents: ["introduce_scope", "ask_open_question", "probe_detail", "negotiate_terms", "set_boundary", "accept_condition", "repair_breach"],
      act: "challenge",
      stance: "guarded",
      text: "我还不能判断你会不会越过居民边界。",
      prompt: "请具体说明身份、采访用途、拍摄范围，以及对方不同意或撤回时你会怎么做。",
      relationship: { trust: 0, cooperation: -1, alertness: 2, publicReason: "关键信息仍不完整。" },
      outcome: "continue",
    }),
  ],
  exitOptions: ["礼貌结束对话，在巷口继续公开环境观察。"],
});

const inheritorScene = scene({
  schemaVersion: DialogueSceneDefinitionV4SchemaVersion,
  definitionId: "dialogue-inheritor-framing-v4",
  npcRef: "entity-inheritor",
  npcRoleRef: "role-inheritor",
  topicRef: "topic-cultural-subject-and-technique",
  title: "从漂亮画面走向文化主体",
  objective: "用开放问题和可核验观察建立不猎奇、不越权的技艺采访。",
  openingMessage: "黄老师没有立即开始演示：很多镜头只留下花，没有留下做花的人。",
  openingPrompt: "你打算怎样提问，才能不把簪花围写成一个供游客消费的符号？",
  privateBoundaryHash: hashCanonical({
    simulatedPressure: "担心传播脱离劳动与社区语境",
    forbiddenDisclosure: ["唯一古代起源", "代表全社区的统一结论", "未确认的人物近景许可"],
  }),
  localKnowledgeRefs: [
    "xunpu-k002-custom-and-zanhuawei-definition",
    "xunpu-k004-technique-sequence",
    "xunpu-k005-daily-festival-difference",
  ],
  allowedIntents: [
    "introduce_scope",
    "ask_open_question",
    "probe_detail",
    "reflect_back",
    "request_evidence",
    "set_boundary",
    "repair_breach",
    "exit_conversation",
  ],
  maximumTurnsByChallenge: challengeTurns,
  responseWindowMinutesByChallenge: responseWindows,
  initialRelationship: { trust: 42, cooperation: 38, alertness: 58 },
  issues: [
    { issueRef: "issue-inheritor-framing", publicLabel: "文化主体与报道框架", initialStatus: "open", requiredForResolution: true },
    { issueRef: "issue-inheritor-method", publicLabel: "观察、引语与可核验来源的边界", initialStatus: "open", requiredForResolution: true },
  ],
  facts: [
    {
      factRef: "fact-inheritor-process-demo",
      publicText: "黄老师愿意开放手部技艺演示，人物近景仍需另行确认。",
      knowledgeRefs: ["xunpu-k004-technique-sequence", "xunpu-k005-daily-festival-difference"],
      disclosureRuleRefs: ["rule-inheritor-resolve-process"],
    },
    {
      factRef: "fact-inheritor-context-interview",
      publicText: "黄老师愿意从个人实践谈劳动、日常与节庆差异，但不代表整个社区。",
      knowledgeRefs: ["xunpu-k002-custom-and-zanhuawei-definition", "xunpu-k005-daily-festival-difference"],
      disclosureRuleRefs: ["rule-inheritor-resolve-context"],
    },
    {
      factRef: "fact-inheritor-terminology-check",
      publicText: "黄老师愿意逐项核对学生记录中的技艺术语与可观察步骤，但历史来源仍须回到公开材料。",
      knowledgeRefs: ["xunpu-k002-custom-and-zanhuawei-definition", "xunpu-k004-technique-sequence"],
      disclosureRuleRefs: ["rule-inheritor-resolve-terminology"],
    },
  ],
  signals: [
    { signalRef: "signal-inheritor-context", keywordGroups: [["劳动", "日常", "文化主体", "社区", "语境"]] },
    { signalRef: "signal-inheritor-open", keywordGroups: [["怎么看", "怎样", "能否讲讲", "对你来说", "为什么"]] },
    { signalRef: "signal-inheritor-boundary", keywordGroups: [["个人实践", "不代表", "来源", "限定", "确认引语"]] },
    { signalRef: "signal-inheritor-origin-demand", keywordGroups: [["唯一来源", "最早起源", "确定就是", "必须证明"]] },
    { signalRef: "signal-inheritor-exotic", keywordGroups: [["网红打卡", "奇观", "猎奇", "最美头饰"]] },
    { signalRef: "signal-inheritor-repair", keywordGroups: [["抱歉", "重新提问", "收回", "改用开放问题"]] },
    { signalRef: "signal-inheritor-process", keywordGroups: [["手部", "步骤", "技艺过程", "观察演示"]] },
    { signalRef: "signal-inheritor-interview", keywordGroups: [["个人经历", "日常变化", "劳动经验", "讲述"]] },
    { signalRef: "signal-inheritor-speaks-for-all", keywordGroups: [["代表所有人", "大家都一样", "整个社区都", "统一说法"]] },
    { signalRef: "signal-inheritor-repair-representation", keywordGroups: [["只代表你", "个人经验", "不扩张", "另找受访者"]] },
    { signalRef: "signal-inheritor-terminology", keywordGroups: [["术语核对", "标准定位", "逐项核对", "步骤名称"]] },
  ],
  rules: [
    exitRule("inheritor", "可以。你先把公开来源查清楚，之后愿意带着更具体的问题回来，我再听。"),
    rule({
      ruleRef: "rule-inheritor-refuse-exotic",
      priority: 220,
      allowedIntents: ["probe_detail", "request_evidence"],
      any: ["signal-inheritor-origin-demand", "signal-inheritor-exotic"],
      act: "refuse",
      stance: "withdrawn",
      text: "如果你只需要一个绝对起源或网红标签，我不能替这种结论背书，也不会开放演示。",
      prompt: "你可以收回这个框架，改问我亲历的技艺、劳动和使用语境。",
      updates: [{ issueRef: "issue-inheritor-framing", nextStatus: "contested", publicReason: "提问把文化压缩为猎奇符号或绝对结论。" }],
      relationship: { trust: -16, cooperation: -18, alertness: 18, publicReason: "猎奇和诱导性提问削弱合作意愿。" },
      outcome: "refusal",
    }),
    rule({
      ruleRef: "rule-inheritor-refuse-representative-overclaim",
      priority: 215,
      allowedIntents: ["ask_open_question", "probe_detail", "reflect_back"],
      all: ["signal-inheritor-speaks-for-all"],
      act: "refuse",
      stance: "withdrawn",
      text: "我只能谈自己的实践，不能替整个社区给你一个统一答案。把个人经验写成‘所有人都这样’同样会失真。",
      prompt: "请把问题限定到我能确认的经历，并说明你还要找谁或查什么材料补足代表性。",
      updates: [{ issueRef: "issue-inheritor-method", nextStatus: "contested", publicReason: "学生要求个人受访者代表整个社区。" }],
      relationship: { trust: -14, cooperation: -15, alertness: 16, publicReason: "代表性被过度扩张，人物拒绝继续背书。" },
      outcome: "refusal",
    }),
    rule({
      ruleRef: "rule-inheritor-repair-representation",
      priority: 205,
      allowedIntents: ["repair_breach", "reflect_back", "ask_open_question"],
      all: ["signal-inheritor-repair", "signal-inheritor-repair-representation"],
      requires: [{ issueRef: "issue-inheritor-method", allowedStatuses: ["contested"] }],
      act: "acknowledge",
      stance: "cautious",
      text: "限定为我的个人经验，并计划补其他受访者或公开来源，这样可以继续。",
      prompt: "你要先核对技艺术语、观察步骤，还是追问我的个人经历？说明这一次证据能支持到哪里。",
      updates: [
        { issueRef: "issue-inheritor-framing", nextStatus: "satisfied", publicReason: "学生回到具体人物与文化主体。" },
        { issueRef: "issue-inheritor-method", nextStatus: "satisfied", publicReason: "学生限定代表性并提出补充来源计划。" },
      ],
      relationship: { trust: 9, cooperation: 10, alertness: -8, publicReason: "学生主动缩小主张边界，恢复采访可能。" },
      outcome: "recovery",
    }),
    rule({
      ruleRef: "rule-inheritor-repair",
      priority: 200,
      allowedIntents: ["repair_breach", "reflect_back", "ask_open_question"],
      all: ["signal-inheritor-repair", "signal-inheritor-context"],
      requires: [{ issueRef: "issue-inheritor-framing", allowedStatuses: ["contested"] }],
      act: "acknowledge",
      stance: "cautious",
      text: "你愿意改问题，我愿意继续。但请区分你看到的、我个人说的和公开来源能证明的。",
      prompt: "先复述这个边界，再选择观察技艺过程或追问我的日常经验。",
      updates: [
        { issueRef: "issue-inheritor-framing", nextStatus: "satisfied", publicReason: "学生收回猎奇框架并回到文化主体。" },
        { issueRef: "issue-inheritor-method", nextStatus: "satisfied", publicReason: "学生承诺区分观察、个人引语与公开来源。" },
      ],
      relationship: { trust: 10, cooperation: 12, alertness: -10, publicReason: "反思和方法修复恢复了采访可能。" },
      outcome: "recovery",
    }),
    rule({
      ruleRef: "rule-inheritor-establish-method",
      priority: 120,
      allowedIntents: ["ask_open_question", "reflect_back", "set_boundary"],
      all: ["signal-inheritor-context", "signal-inheritor-open", "signal-inheritor-boundary"],
      forbidden: ["signal-inheritor-origin-demand", "signal-inheritor-exotic"],
      act: "clarify",
      stance: "cooperative",
      text: "这个问法把我当具体的人，也给事实留了边界。接下来你只能优先做一件事。",
      prompt: "你要观察手部技艺步骤，还是先做一轮个人经验采访？说明你愿意放弃什么。",
      updates: [
        { issueRef: "issue-inheritor-framing", nextStatus: "satisfied", publicReason: "报道框架尊重文化主体和劳动语境。" },
        { issueRef: "issue-inheritor-method", nextStatus: "satisfied", publicReason: "学生区分观察、引语和来源证明。" },
      ],
      relationship: { trust: 11, cooperation: 10, alertness: -9, publicReason: "开放问题和证据边界建立专业信任。" },
      outcome: "clarification",
    }),
    rule({
      ruleRef: "rule-inheritor-resolve-process",
      priority: 180,
      minTurn: 2,
      allowedIntents: ["probe_detail", "request_evidence", "set_boundary"],
      all: ["signal-inheritor-process", "signal-inheritor-boundary"],
      requires: [
        { issueRef: "issue-inheritor-framing", allowedStatuses: ["satisfied"] },
        { issueRef: "issue-inheritor-method", allowedStatuses: ["satisfied"] },
      ],
      act: "commit",
      stance: "committed",
      text: "我开放手部演示。你可以记录步骤，但人物近景和起源解释不包含在这次许可里。",
      prompt: null,
      facts: ["fact-inheritor-process-demo"],
      relationship: { trust: 10, cooperation: 15, alertness: -8, publicReason: "观察目标清晰且没有扩张许可。" },
      commitment: {
        madeBy: "npc",
        summary: "开放可核验的手部技艺演示。",
        condition: "只记录步骤；人物近景和历史结论需另行核验。",
        dueAfterVirtualMinutes: 8,
      },
      outcome: "resolved",
      routeRef: "dialogue-route-process-observation",
      eventTemplateRef: "event-template-inheritor",
      resolutionSummary: "学生获得高可观察性技艺证据，但放弃本轮人物深访。",
    }),
    rule({
      ruleRef: "rule-inheritor-resolve-context",
      priority: 170,
      minTurn: 2,
      allowedIntents: ["ask_open_question", "reflect_back", "set_boundary"],
      all: ["signal-inheritor-interview", "signal-inheritor-boundary"],
      requires: [
        { issueRef: "issue-inheritor-framing", allowedStatuses: ["satisfied"] },
        { issueRef: "issue-inheritor-method", allowedStatuses: ["satisfied"] },
      ],
      act: "commit",
      stance: "committed",
      text: "我可以从自己的经历谈日常劳动和变化。引用前请复述确认，也不要写成全社区统一经验。",
      prompt: null,
      facts: ["fact-inheritor-context-interview"],
      relationship: { trust: 14, cooperation: 13, alertness: -9, publicReason: "学生选择让文化主体发声并保留代表性边界。" },
      commitment: {
        madeBy: "student",
        summary: "引用前复述确认，并标明这是个人经验。",
        condition: "不得把个人讲述扩张为全社区结论。",
        dueAfterVirtualMinutes: 10,
      },
      outcome: "resolved",
      routeRef: "dialogue-route-context-interview",
      eventTemplateRef: "event-template-inheritor",
      resolutionSummary: "学生获得更深的个人经验引语，但需另行补足技艺步骤证据。",
    }),
    rule({
      ruleRef: "rule-inheritor-resolve-terminology",
      priority: 190,
      minTurn: 2,
      allowedIntents: ["request_evidence", "reflect_back", "probe_detail", "set_boundary"],
      all: ["signal-inheritor-terminology"],
      forbidden: ["signal-inheritor-origin-demand", "signal-inheritor-speaks-for-all"],
      requires: [
        { issueRef: "issue-inheritor-framing", allowedStatuses: ["satisfied"] },
        { issueRef: "issue-inheritor-method", allowedStatuses: ["satisfied"] },
      ],
      act: "commit",
      stance: "cooperative",
      text: "我可以逐项核对你记录的步骤名称，并指出哪些是我刚才实际演示的；历史解释仍由你回到来源定位。",
      prompt: null,
      facts: ["fact-inheritor-terminology-check"],
      relationship: { trust: 9, cooperation: 12, alertness: -7, publicReason: "学生把人物知识限定在可观察技艺和术语范围。" },
      commitment: {
        madeBy: "npc",
        summary: "核对技艺术语和本次可观察步骤，不为历史来源或全社区实践背书。",
        condition: "学生必须在事实核查表中分开现场确认与公开来源。",
        dueAfterVirtualMinutes: 6,
      },
      outcome: "resolved",
      routeRef: "dialogue-route-terminology-check",
      eventTemplateRef: "event-template-inheritor",
      resolutionSummary: "学生获得精确术语和步骤边界，但本轮放弃人物深访与完整演示画面。",
    }),
    rule({
      ruleRef: "rule-inheritor-clarify",
      priority: -100,
      allowedIntents: ["introduce_scope", "ask_open_question", "probe_detail", "reflect_back", "request_evidence", "set_boundary", "repair_breach"],
      act: "challenge",
      stance: "guarded",
      text: "这个问题还没有说明你怎样处理文化主体、个人经验和公开事实之间的差别。",
      prompt: "请用一个开放问题重问，并说明哪些内容需要另外核验。",
      relationship: { trust: 0, cooperation: -1, alertness: 2, publicReason: "采访方法仍不清楚。" },
      outcome: "continue",
    }),
  ],
  exitOptions: ["感谢黄老师，先去查阅公开来源再回来。"],
});

const shopkeeperScene = scene({
  schemaVersion: DialogueSceneDefinitionV4SchemaVersion,
  definitionId: "dialogue-shopkeeper-editorial-v4",
  npcRef: "entity-shopkeeper",
  npcRoleRef: "role-merchant-partner",
  topicRef: "topic-commercial-material-and-editorial-independence",
  title: "素材合作不能交换编辑权",
  objective: "在素材许可、商业披露和编辑独立之间完成可审计协商。",
  openingMessage: "吴姐展示一组清晰的旅拍素材：可以给你原片，但希望门店进标题、首图带套餐链接。",
  openingPrompt: "你怎样回应这项交换？请说明素材、标题和商业关系分别由谁决定。",
  privateBoundaryHash: hashCanonical({
    simulatedPressure: "商户希望通过素材交换获得标题和首图曝光",
    forbiddenDisclosure: ["伪造完整版权链", "隐藏商业关系", "代表平台承诺流量"],
  }),
  localKnowledgeRefs: [
    "xunpu-k013-logo-is-rights-bearing-asset",
    "xunpu-k031-photo-copyright-permission",
    "xunpu-k032-watermark-not-license",
  ],
  allowedIntents: [
    "ask_open_question",
    "probe_detail",
    "request_evidence",
    "negotiate_terms",
    "set_boundary",
    "accept_condition",
    "repair_breach",
    "exit_conversation",
  ],
  maximumTurnsByChallenge: challengeTurns,
  responseWindowMinutesByChallenge: responseWindows,
  initialRelationship: { trust: 46, cooperation: 62, alertness: 44 },
  issues: [
    { issueRef: "issue-shopkeeper-editorial", publicLabel: "标题、首图与报道判断的独立性", initialStatus: "open", requiredForResolution: true },
    { issueRef: "issue-shopkeeper-license", publicLabel: "作者、平台、期限、用途与商业披露", initialStatus: "open", requiredForResolution: true },
  ],
  facts: [
    {
      factRef: "fact-shopkeeper-limited-license",
      publicText: "商户可提供一组确认作者的原片，并接受限定平台、期限和素材来源标注。",
      knowledgeRefs: ["xunpu-k031-photo-copyright-permission", "xunpu-k032-watermark-not-license"],
      disclosureRuleRefs: ["rule-shopkeeper-resolve-limited-license"],
    },
    {
      factRef: "fact-shopkeeper-own-interview",
      publicText: "即使不使用商户原片，吴姐仍愿意以商户身份接受一段标明商业立场的采访。",
      knowledgeRefs: ["xunpu-k013-logo-is-rights-bearing-asset"],
      disclosureRuleRefs: ["rule-shopkeeper-resolve-decline-assets"],
    },
    {
      factRef: "fact-shopkeeper-reference-only",
      publicText: "吴姐允许学生在现场查看样片和拍摄信息作为线索，但不复制文件、不进入公开作品，后续由学生独立采集。",
      knowledgeRefs: ["xunpu-k031-photo-copyright-permission", "xunpu-k032-watermark-not-license"],
      disclosureRuleRefs: ["rule-shopkeeper-resolve-reference-only"],
    },
  ],
  signals: [
    { signalRef: "signal-shopkeeper-editorial-boundary", keywordGroups: [["标题独立", "编辑独立", "不交换标题", "报道判断"]] },
    { signalRef: "signal-shopkeeper-license", keywordGroups: [["作者", "平台", "期限", "用途", "授权"]] },
    { signalRef: "signal-shopkeeper-disclosure", keywordGroups: [["标注来源", "商业关系", "披露", "素材提供方"]] },
    { signalRef: "signal-shopkeeper-hidden-deal", keywordGroups: [["不标来源", "别披露", "偷偷", "隐藏合作"]] },
    { signalRef: "signal-shopkeeper-accept-placement", keywordGroups: [["放进标题", "首图放门店", "带套餐链接", "换素材"]] },
    { signalRef: "signal-shopkeeper-repair", keywordGroups: [["抱歉", "收回", "重新协商", "不能这样交换"]] },
    { signalRef: "signal-shopkeeper-use-assets", keywordGroups: [["使用原片", "有限授权", "采用素材"]] },
    { signalRef: "signal-shopkeeper-decline-assets", keywordGroups: [["不使用素材", "自行拍摄", "拒绝原片", "只做采访"]] },
    { signalRef: "signal-shopkeeper-overbroad-license", keywordGroups: [["全部权利", "永久全平台", "保证版权", "水印就能发"]] },
    { signalRef: "signal-shopkeeper-repair-license", keywordGroups: [["不把水印当授权", "另找权利人", "缩小许可", "不要求全部权利"]] },
    { signalRef: "signal-shopkeeper-reference-only", keywordGroups: [["只核对线索", "仅现场查看", "不复制原片", "不导出文件"]] },
  ],
  rules: [
    exitRule("shopkeeper", "没关系。素材交换到此为止，我会保留你没有承诺推广的记录。"),
    rule({
      ruleRef: "rule-shopkeeper-refuse-hidden-deal",
      priority: 220,
      allowedIntents: ["accept_condition", "negotiate_terms"],
      any: ["signal-shopkeeper-hidden-deal", "signal-shopkeeper-accept-placement"],
      forbidden: ["signal-shopkeeper-editorial-boundary"],
      act: "refuse",
      stance: "guarded",
      text: "口头答应把门店塞进标题、又不留合作记录，对你我都不安全。我不会按这种方式给原片。",
      prompt: "如果要继续，请收回交换，分别谈编辑决定、素材授权和公开披露。",
      updates: [{ issueRef: "issue-shopkeeper-editorial", nextStatus: "contested", publicReason: "素材被用于交换标题或隐藏商业关系。" }],
      relationship: { trust: -14, cooperation: -12, alertness: 18, publicReason: "不可审计交换增加双方风险。" },
      outcome: "refusal",
    }),
    rule({
      ruleRef: "rule-shopkeeper-refuse-overbroad-license",
      priority: 215,
      allowedIntents: ["request_evidence", "negotiate_terms", "accept_condition"],
      all: ["signal-shopkeeper-overbroad-license"],
      act: "refuse",
      stance: "guarded",
      text: "我不能替摄影者保证全部权利，也不会因为文件有水印就承诺永久全平台使用。",
      prompt: "你可以缩小平台、期限和用途，联系实际权利人，或只在现场查看样片线索而不复制。",
      updates: [{ issueRef: "issue-shopkeeper-license", nextStatus: "contested", publicReason: "学生要求无法由商户确认的过宽许可。" }],
      relationship: { trust: -10, cooperation: -13, alertness: 17, publicReason: "过宽许可要求让权利链不可审计。" },
      outcome: "refusal",
    }),
    rule({
      ruleRef: "rule-shopkeeper-repair-license",
      priority: 205,
      allowedIntents: ["repair_breach", "request_evidence", "negotiate_terms"],
      all: ["signal-shopkeeper-repair", "signal-shopkeeper-repair-license"],
      requires: [{ issueRef: "issue-shopkeeper-license", allowedStatuses: ["contested"] }],
      act: "acknowledge",
      stance: "cautious",
      text: "你愿意收窄许可并另核权利人，可以继续。标题和商业披露仍要独立说明。",
      prompt: "你要谈有限许可、只在现场查看线索，还是完全不用原片？",
      updates: [
        { issueRef: "issue-shopkeeper-editorial", nextStatus: "satisfied", publicReason: "学生确认编辑判断不随许可条件转移。" },
        { issueRef: "issue-shopkeeper-license", nextStatus: "satisfied", publicReason: "学生收回过宽许可并提出可核验范围。" },
      ],
      relationship: { trust: 8, cooperation: 9, alertness: -7, publicReason: "许可边界被重新拆分并可继续核验。" },
      outcome: "recovery",
    }),
    rule({
      ruleRef: "rule-shopkeeper-repair",
      priority: 200,
      allowedIntents: ["repair_breach", "set_boundary", "negotiate_terms"],
      all: ["signal-shopkeeper-repair", "signal-shopkeeper-editorial-boundary", "signal-shopkeeper-disclosure"],
      requires: [{ issueRef: "issue-shopkeeper-editorial", allowedStatuses: ["contested"] }],
      act: "acknowledge",
      stance: "cautious",
      text: "这样可以继续谈。标题由编辑判断，素材合作写入台账，接下来把平台、期限和用途说清楚。",
      prompt: "你选择有限使用原片，还是完全不用原片、只记录我的商户观点？",
      updates: [
        { issueRef: "issue-shopkeeper-editorial", nextStatus: "satisfied", publicReason: "学生收回标题交换并恢复编辑独立。" },
        { issueRef: "issue-shopkeeper-license", nextStatus: "satisfied", publicReason: "学生承诺登记来源与商业关系。" },
      ],
      relationship: { trust: 9, cooperation: 10, alertness: -8, publicReason: "透明修复使合作重新可审计。" },
      outcome: "recovery",
    }),
    rule({
      ruleRef: "rule-shopkeeper-establish-terms",
      priority: 120,
      allowedIntents: ["request_evidence", "negotiate_terms", "set_boundary"],
      all: ["signal-shopkeeper-editorial-boundary", "signal-shopkeeper-license", "signal-shopkeeper-disclosure"],
      forbidden: ["signal-shopkeeper-hidden-deal"],
      act: "clarify",
      stance: "cooperative",
      text: "你把三件事分开了：素材权利、商业披露、编辑判断。现在可以选择不同成本的合作方式。",
      prompt: "你要限定使用已核对原片，还是放弃原片、自己采集并只记录我的商户立场？",
      updates: [
        { issueRef: "issue-shopkeeper-editorial", nextStatus: "satisfied", publicReason: "标题和首图不再作为素材交换条件。" },
        { issueRef: "issue-shopkeeper-license", nextStatus: "satisfied", publicReason: "作者、平台、期限、用途与披露均进入协商。" },
      ],
      relationship: { trust: 10, cooperation: 10, alertness: -8, publicReason: "专业拆分让合作边界可验证。" },
      outcome: "clarification",
    }),
    rule({
      ruleRef: "rule-shopkeeper-resolve-limited-license",
      priority: 180,
      minTurn: 2,
      allowedIntents: ["negotiate_terms", "accept_condition", "request_evidence"],
      all: ["signal-shopkeeper-use-assets", "signal-shopkeeper-license", "signal-shopkeeper-disclosure"],
      forbidden: ["signal-shopkeeper-hidden-deal", "signal-shopkeeper-accept-placement"],
      requires: [
        { issueRef: "issue-shopkeeper-editorial", allowedStatuses: ["satisfied"] },
        { issueRef: "issue-shopkeeper-license", allowedStatuses: ["satisfied"] },
      ],
      act: "commit",
      stance: "committed",
      text: "我提供已确认作者的原片，限定本次课程专题和约定平台。你标注素材提供方，但标题由你们编辑决定。",
      prompt: null,
      facts: ["fact-shopkeeper-limited-license"],
      relationship: { trust: 12, cooperation: 16, alertness: -8, publicReason: "有限许可和编辑独立同时得到确认。" },
      commitment: {
        madeBy: "student",
        summary: "登记作者、素材提供方、平台、期限和用途。",
        condition: "素材不得换取标题、首图或未披露推广。",
        dueAfterVirtualMinutes: 8,
      },
      outcome: "resolved",
      routeRef: "dialogue-route-limited-material-license",
      eventTemplateRef: "event-template-commercial-response",
      resolutionSummary: "学生获得高质量素材，但承担完整权利台账与商业披露义务。",
    }),
    rule({
      ruleRef: "rule-shopkeeper-resolve-decline-assets",
      priority: 170,
      minTurn: 2,
      allowedIntents: ["set_boundary", "negotiate_terms", "ask_open_question"],
      all: ["signal-shopkeeper-decline-assets", "signal-shopkeeper-editorial-boundary"],
      forbidden: ["signal-shopkeeper-hidden-deal", "signal-shopkeeper-accept-placement"],
      requires: [
        { issueRef: "issue-shopkeeper-editorial", allowedStatuses: ["satisfied"] },
        { issueRef: "issue-shopkeeper-license", allowedStatuses: ["satisfied"] },
      ],
      act: "commit",
      stance: "cooperative",
      text: "不使用原片也行。你可以自己采集公开环境，并把我作为有商业立场的受访者，而不是报道赞助方。",
      prompt: null,
      facts: ["fact-shopkeeper-own-interview"],
      relationship: { trust: 8, cooperation: 8, alertness: -6, publicReason: "放弃素材降低权利风险，但也减少画面资源。" },
      commitment: {
        madeBy: "npc",
        summary: "以明确商业身份接受有限采访。",
        condition: "采访内容不附带标题、首图或套餐链接承诺。",
        dueAfterVirtualMinutes: 6,
      },
      outcome: "resolved",
      routeRef: "dialogue-route-decline-commercial-assets",
      eventTemplateRef: "event-template-commercial-response",
      resolutionSummary: "学生保住编辑独立并降低素材权利风险，但放弃现成高清画面。",
    }),
    rule({
      ruleRef: "rule-shopkeeper-resolve-reference-only",
      priority: 165,
      minTurn: 2,
      allowedIntents: ["request_evidence", "set_boundary", "negotiate_terms"],
      all: ["signal-shopkeeper-reference-only"],
      forbidden: ["signal-shopkeeper-hidden-deal", "signal-shopkeeper-accept-placement", "signal-shopkeeper-overbroad-license"],
      requires: [
        { issueRef: "issue-shopkeeper-editorial", allowedStatuses: ["satisfied"] },
        { issueRef: "issue-shopkeeper-license", allowedStatuses: ["satisfied"] },
      ],
      act: "commit",
      stance: "cooperative",
      text: "你可以在这里看样片的拍摄点和镜头信息，但不复制文件。之后自行采集，成片也不写成我提供素材。",
      prompt: null,
      facts: ["fact-shopkeeper-reference-only"],
      relationship: { trust: 9, cooperation: 10, alertness: -6, publicReason: "把素材降为现场线索，兼顾效率和独立采集。" },
      commitment: {
        madeBy: "student",
        summary: "样片只用于现场路线和镜头线索，不复制、不公开、不声称取得许可。",
        condition: "最终媒体必须来自独立采集或另有完整授权的素材。",
        dueAfterVirtualMinutes: 7,
      },
      outcome: "resolved",
      routeRef: "dialogue-route-reference-only",
      eventTemplateRef: "event-template-commercial-response",
      resolutionSummary: "学生获得拍摄线索并保留编辑独立，但必须投入时间自行采集且不能使用现成高清原片。",
    }),
    rule({
      ruleRef: "rule-shopkeeper-clarify",
      priority: -100,
      allowedIntents: ["ask_open_question", "probe_detail", "request_evidence", "negotiate_terms", "set_boundary", "accept_condition", "repair_breach"],
      act: "challenge",
      stance: "guarded",
      text: "你还没有把素材许可、商业披露和标题决定分开。",
      prompt: "请分别说明作者和授权范围、合作如何披露，以及为什么标题不能作为交换条件。",
      relationship: { trust: 0, cooperation: -1, alertness: 2, publicReason: "合作条件仍不可审计。" },
      outcome: "continue",
    }),
  ],
  exitOptions: ["拒绝素材交换，保留此次商业接触记录后离开。"],
});

export const xunpuV4DialogueScenes: DialogueSceneDefinitionV4[] = [
  gatekeeperScene,
  inheritorScene,
  shopkeeperScene,
];
