import { hashCanonical } from "../canonical.js";
import type {
  XunpuGroundedClaimV4,
  XunpuKnowledgeRecordV4,
} from "./types.js";

type KnowledgeDraft = Omit<XunpuKnowledgeRecordV4, "contentHash">;

function record(draft: KnowledgeDraft): XunpuKnowledgeRecordV4 {
  return { ...draft, contentHash: hashCanonical(draft) };
}

const civilCodeUrl =
  "https://wb.flk.npc.gov.cn/flfg/PDF/bd53dd912c1048f2aecbaa229238334b.pdf";
const personalInformationUrl =
  "https://www.cac.gov.cn/2021-08/20/c_1631050028355286.htm";
const photographyUrl =
  "https://www.ncac.gov.cn/xxfb/flfg/gfxwj/202006/t20200611_50562.html";
const aiLabelUrl =
  "https://www.cac.gov.cn/2025-03/14/c_1743654684782215.htm";
const fakeNewsUrl =
  "https://press.nppa.gov.cn/zcfg/202312/t20231205_820779_m.html";

const common = {
  accessedAt: "2026-08-28",
  reviewStatus: "pending_expert_review" as const,
  copyrightNote: "仅保存来源元数据、定位和改写教学摘要；不复制全文或页面媒体。",
  storedExcerpt: "" as const,
};

export const xunpuV4AddedKnowledgeRecords: XunpuKnowledgeRecordV4[] = [
  record({
    ...common,
    knowledgeId: "xunpu-k025-portrait-consent",
    title: "肖像权、制作使用公开与许可边界",
    teachingSummary: "识别自然人肖像后，应把肖像权、摄影作品版权和个人信息分别核对；未经许可制作、使用或公开肖像的风险不能由一条来源水印消除。",
    sourceTitle: "中华人民共和国民法典",
    publisher: "全国人民代表大会",
    url: civilCodeUrl,
    publishedAt: "2020-05-28",
    locator: "第四编第四章第一千零一十八条、第一千零一十九条",
    sourceVersion: "2020-05-28 通过文本",
  }),
  record({
    ...common,
    knowledgeId: "xunpu-k026-news-use-necessary-scope",
    title: "公共利益新闻处理个人信息的合理范围",
    teachingSummary: "为公共利益实施新闻报道等行为可以在法律规定的合理范围内处理个人信息；课程不得把该规则扩张为任意拍摄、任意平台、任意期限的许可。",
    sourceTitle: "中华人民共和国个人信息保护法",
    publisher: "全国人民代表大会常务委员会（中国网信网全文）",
    url: personalInformationUrl,
    publishedAt: "2021-08-20",
    locator: "第二章第一节第十三条第一款第五项",
    sourceVersion: "2021-08-20 通过文本",
  }),
  record({
    ...common,
    knowledgeId: "xunpu-k027-voice-protection",
    title: "自然人声音保护参照肖像权规则",
    teachingSummary: "采访录音、声音克隆和可识别声音的公开不能只按音频文件版权处理，还要评估自然人声音权益和具体许可范围。",
    sourceTitle: "中华人民共和国民法典",
    publisher: "全国人民代表大会",
    url: civilCodeUrl,
    publishedAt: "2020-05-28",
    locator: "第四编第四章第一千零二十三条第二款",
    sourceVersion: "2020-05-28 通过文本",
  }),
  record({
    ...common,
    knowledgeId: "xunpu-k028-sensitive-personal-information",
    title: "敏感个人信息的特定目的、必要性和严格保护",
    teachingSummary: "生物识别、特定身份、行踪轨迹等可能属于敏感个人信息；处理需要特定目的、充分必要性和严格保护，并注意单独同意及告知要求。",
    sourceTitle: "中华人民共和国个人信息保护法",
    publisher: "全国人民代表大会常务委员会（中国网信网全文）",
    url: personalInformationUrl,
    publishedAt: "2021-08-20",
    locator: "第二章第二节第二十八条至第三十条",
    sourceVersion: "2021-08-20 通过文本",
  }),
  record({
    ...common,
    knowledgeId: "xunpu-k029-minor-information",
    title: "不满十四周岁未成年人个人信息保护",
    teachingSummary: "不满十四周岁未成年人的个人信息属于敏感个人信息；课程现场不允许学生以采访便利代替监护人同意和专门保护规则。",
    sourceTitle: "中华人民共和国个人信息保护法",
    publisher: "全国人民代表大会常务委员会（中国网信网全文）",
    url: personalInformationUrl,
    publishedAt: "2021-08-20",
    locator: "第二章第二节第二十八条、第三十一条",
    sourceVersion: "2021-08-20 通过文本",
  }),
  record({
    ...common,
    knowledgeId: "xunpu-k030-consent-withdrawal",
    title: "撤回同意与作品版本响应",
    teachingSummary: "基于同意处理个人信息时，个人有权撤回同意；课程将撤回后的停止公开、替换素材和保留版本回执设计为职业动作，不把撤回前处理自动描述为违法。",
    sourceTitle: "中华人民共和国个人信息保护法",
    publisher: "全国人民代表大会常务委员会（中国网信网全文）",
    url: personalInformationUrl,
    publishedAt: "2021-08-20",
    locator: "第二章第一节第十五条",
    sourceVersion: "2021-08-20 通过文本",
  }),
  record({
    ...common,
    knowledgeId: "xunpu-k031-photo-copyright-permission",
    title: "新闻题材摄影作品仍受著作权保护",
    teachingSummary: "以新闻事件为主题的摄影作品不当然属于不受保护的时事新闻；使用他人摄影作品原则上应核对权利人许可、报酬和约定范围。",
    sourceTitle: "国家版权局关于规范摄影作品版权秩序的通知",
    publisher: "国家版权局",
    url: photographyUrl,
    publishedAt: "2020-05-20",
    locator: "第一条、第二条",
    sourceVersion: "国版发〔2020〕1号",
  }),
  record({
    ...common,
    knowledgeId: "xunpu-k032-watermark-not-license",
    title: "水印不能单独证明权属，也不能替代许可核验",
    teachingSummary: "通知明确权利声明和水印不能单独作为权属证据，并要求使用者核对许可；课程据此把水印视为来源线索而非可用许可。",
    sourceTitle: "国家版权局关于规范摄影作品版权秩序的通知",
    publisher: "国家版权局",
    url: photographyUrl,
    publishedAt: "2020-05-20",
    locator: "第二条、第十条",
    sourceVersion: "国版发〔2020〕1号",
  }),
  record({
    ...common,
    knowledgeId: "xunpu-k033-ai-explicit-label",
    title: "生成合成内容和显式标识",
    teachingSummary: "生成合成内容包括文本、图片、音频、视频和虚拟场景；适用情形下，显式标识应以用户可明显感知的方式呈现，导出文件也需满足相应要求。",
    sourceTitle: "人工智能生成合成内容标识办法",
    publisher: "国家互联网信息办公室等四部门",
    url: aiLabelUrl,
    publishedAt: "2025-03-14",
    locator: "第三条、第四条",
    sourceVersion: "国信办通字〔2025〕2号，2025-09-01 施行",
  }),
  record({
    ...common,
    knowledgeId: "xunpu-k034-ai-implicit-label",
    title: "生成合成文件元数据中的隐式标识",
    teachingSummary: "适用服务应在生成合成文件元数据中记录内容属性、服务者编码、内容编号等制作要素；课程媒体导出需分别检查可见标识和元数据标识。",
    sourceTitle: "人工智能生成合成内容标识办法",
    publisher: "国家互联网信息办公室等四部门",
    url: aiLabelUrl,
    publishedAt: "2025-03-14",
    locator: "第五条、第六条",
    sourceVersion: "国信办通字〔2025〕2号，2025-09-01 施行",
  }),
  record({
    ...common,
    knowledgeId: "xunpu-k035-ai-user-declaration",
    title: "发布生成合成内容的主动声明和标识义务",
    teachingSummary: "用户发布生成合成内容时应主动声明并使用平台标识功能；恶意删除、篡改、伪造或隐匿标识不得作为作品优化动作。",
    sourceTitle: "人工智能生成合成内容标识办法",
    publisher: "国家互联网信息办公室等四部门",
    url: aiLabelUrl,
    publishedAt: "2025-03-14",
    locator: "第六条、第九条、第十条",
    sourceVersion: "国信办通字〔2025〕2号，2025-09-01 施行",
  }),
  record({
    ...common,
    knowledgeId: "xunpu-k036-source-interview-correction",
    title: "多方核实、网络线索复核与公开更正",
    teachingSummary: "采访应全面听取相关方、避免单一事实证据；未经核实的网络和手机信息不得直接采用；确认失实后应及时公开更正并处理投诉。",
    sourceTitle: "关于严防虚假新闻报道的若干规定",
    publisher: "国家新闻出版署主办中国记者网",
    url: fakeNewsUrl,
    publishedAt: "2023-07-27",
    locator: "第一条第二至第五项、第二条第三项、第三条第一至第二项",
    sourceVersion: "新出政发〔2011〕14号，页面更新 2023-07-27",
  }),
];

export const xunpuV4GroundedClaims: XunpuGroundedClaimV4[] = [
  {
    claimId: "claim-heritage-listing-2008",
    allowedWording: "公开名录与地方标准支持 2008 年列入第二批国家级非物质文化遗产名录。",
    knowledgeRefs: ["xunpu-k001-heritage-status-boundary", "xunpu-k002-custom-and-zanhuawei-definition"],
    runtimeEvidenceKinds: ["source_comparison"],
    prohibitedExpansion: "不得写成 2007 年已入选或用网络转引覆盖原始定位。",
    minimumIndependentSupportCount: 2,
  },
  {
    claimId: "claim-custom-scope",
    allowedWording: "应按来源区分蟳埔女习俗、簪花围技艺和传播称谓。",
    knowledgeRefs: ["xunpu-k002-custom-and-zanhuawei-definition", "xunpu-k015-authenticity-integrity-transmission"],
    runtimeEvidenceKinds: ["expert_dialogue"],
    prohibitedExpansion: "不得把视觉符号等同完整文化。",
    minimumIndependentSupportCount: 2,
  },
  {
    claimId: "claim-technique-process",
    allowedWording: "技艺步骤按地方标准和受访者可确认的个人实践描述。",
    knowledgeRefs: ["xunpu-k004-technique-sequence", "xunpu-k005-daily-festival-difference"],
    runtimeEvidenceKinds: ["field_observation", "confirmed_quote"],
    prohibitedExpansion: "不得推断唯一古代起源或所有人统一实践。",
    minimumIndependentSupportCount: 2,
  },
  {
    claimId: "claim-cultural-subject",
    allowedWording: "传播应尊重传承主体、真实性和完整性。",
    knowledgeRefs: ["xunpu-k003-cultural-respect", "xunpu-k015-authenticity-integrity-transmission"],
    runtimeEvidenceKinds: ["community_dialogue"],
    prohibitedExpansion: "不得以保护名义替社区发言。",
    minimumIndependentSupportCount: 2,
  },
  {
    claimId: "claim-2024-innovation-case",
    allowedWording: "该传播案例入选发布方公布的 2024 年文旅经济创新案例。",
    knowledgeRefs: ["xunpu-k008-innovation-case-selection", "xunpu-k011-case-evaluation-frame"],
    runtimeEvidenceKinds: ["page_timestamp"],
    prohibitedExpansion: "不得写成永久官方排名。",
    minimumIndependentSupportCount: 2,
  },
  {
    claimId: "claim-2024-visitor-data",
    allowedWording: "客流数字只按页面所述 2024 年统计口径引用。",
    knowledgeRefs: ["xunpu-k009-2024-visitor-statistics", "xunpu-k012-yearly-statistics-not-interchangeable"],
    runtimeEvidenceKinds: ["official_receipt"],
    prohibitedExpansion: "不得外推为当日实时客流。",
    minimumIndependentSupportCount: 2,
  },
  {
    claimId: "claim-online-reach",
    allowedWording: "传播量是发布方在特定统计窗口中的数据。",
    knowledgeRefs: ["xunpu-k010-online-reach-attribution", "xunpu-k012-yearly-statistics-not-interchangeable"],
    runtimeEvidenceKinds: ["page_timestamp"],
    prohibitedExpansion: "不得写成实时平台数据或独立第三方测量。",
    minimumIndependentSupportCount: 2,
  },
  {
    claimId: "claim-source-verification",
    allowedWording: "网络线索需回到来源、采访相关方并进行多方核实。",
    knowledgeRefs: ["xunpu-k018-network-claim-needs-verification", "xunpu-k036-source-interview-correction"],
    runtimeEvidenceKinds: ["source_comparison", "official_receipt"],
    prohibitedExpansion: "不得把热搜、群聊或模型回答当确认事实。",
    minimumIndependentSupportCount: 2,
  },
  {
    claimId: "claim-photo-and-portrait",
    allowedWording: "摄影作品版权、人物肖像和个人信息需要分别核对。",
    knowledgeRefs: ["xunpu-k025-portrait-consent", "xunpu-k028-sensitive-personal-information", "xunpu-k031-photo-copyright-permission"],
    runtimeEvidenceKinds: ["asset_metadata", "consent_receipt"],
    prohibitedExpansion: "水印不等于许可，新闻用途不等于无限使用。",
    minimumIndependentSupportCount: 3,
  },
  {
    claimId: "claim-consent-withdrawal",
    allowedWording: "公开范围改变后，作品版本和传播范围需要响应。",
    knowledgeRefs: ["xunpu-k025-portrait-consent", "xunpu-k030-consent-withdrawal"],
    runtimeEvidenceKinds: ["withdrawal_receipt", "revision_diff"],
    prohibitedExpansion: "不得静默忽略撤回或抹掉撤回前版本。",
    minimumIndependentSupportCount: 2,
  },
  {
    claimId: "claim-ai-label",
    allowedWording: "生成合成图像、音频和视频应按适用规则处理显式与隐式标识。",
    knowledgeRefs: ["xunpu-k033-ai-explicit-label", "xunpu-k034-ai-implicit-label", "xunpu-k035-ai-user-declaration"],
    runtimeEvidenceKinds: ["asset_metadata", "platform_receipt"],
    prohibitedExpansion: "不得伪装为真实拍摄或恶意删除标识。",
    minimumIndependentSupportCount: 3,
  },
  {
    claimId: "claim-job-workflow",
    allowedWording: "融媒体岗位训练覆盖采集、编辑、审核发布、视听生产和复盘。",
    knowledgeRefs: ["xunpu-k022-real-project-scenario-teaching", "xunpu-k023-integrated-production-workflow", "xunpu-k024-all-media-job-loop"],
    runtimeEvidenceKinds: ["artifact_version", "publication_receipt"],
    prohibitedExpansion: "不得把点击完成或文本填空等同岗位能力。",
    minimumIndependentSupportCount: 3,
  },
];
