import {
  FlagshipRuntimeActionPolicyV4Schema,
  FlagshipWorldRuntimeDefinitionV4Schema,
  FlagshipWorldRuntimeDefinitionV4SchemaVersion,
  type FlagshipContentReferenceV4,
  type FlagshipRuntimeActionPolicyV4,
  type FlagshipWorldRuntimeDefinitionV4,
} from "@ronggang/contracts";

const worldVerbs = [
  "observe",
  "ask",
  "probe",
  "inspect",
  "compare",
  "negotiate",
] as const;

const eventStatus = (eventType: string) => ({
  kind: "event_status" as const,
  eventType,
  statuses: ["committed"] as const,
});

const anyAfter = (...eventTypes: string[]) => ({
  all: [],
  any: eventTypes.map(eventStatus),
  none: [],
});

export const xunpuFlagshipActionPolicyV4: FlagshipRuntimeActionPolicyV4 =
  FlagshipRuntimeActionPolicyV4Schema.parse({
    schemaVersion: "flagship-action-policy/4.0.0",
    policyId: "xunpu-flagship-action-policy-v4",
    actions: [
      {
        eventTemplateId: "event-template-draft-story",
        requirements: { all: [], any: [], none: [] },
        unavailableReason: "请先在作品台保存可核对的实际修订版本。",
      },
      {
        eventTemplateId: "event-template-publication",
        requirements: anyAfter("student_drafts_story", "student_compares_sources", "student_inspects_source"),
        unavailableReason: "发布前需要已经形成的稿件修订或来源核验；作品完整性与教师发布门仍须分别通过。",
      },
      {
        eventTemplateId: "event-template-limited-alert",
        requirements: { all: [], any: [], none: [] },
        unavailableReason: "安全提醒必须附实际作品、时点、未知项并通过教师门。",
      },
      {
        eventTemplateId: "event-template-correction",
        requirements: anyAfter("student_submits_story", "student_submits_limited_alert"),
        unavailableReason: "尚无已处理的公开稿件或安全提醒，不能凭空生成公开更正。",
      },
      {
        eventTemplateId: "event-template-topic-brief",
        requirements: { all: [], any: [], none: [] },
        unavailableReason: "编辑工单尚未进入当前发布版本。",
      },
      {
        eventTemplateId: "event-template-gatekeeper",
        requirements: { all: [], any: [], none: [] },
        unavailableReason: "当前没有可进入的公共采访准入行动。",
      },
      {
        eventTemplateId: "event-template-community-source",
        requirements: anyAfter(
          "student_asks_gatekeeper",
          "student_observes_editorial_brief",
          "student_compares_sources",
          "student_inspects_source",
        ),
        unavailableReason: "先完成编辑工单、采访准入或一轮来源核验，才能进入人物采访。",
      },
      {
        eventTemplateId: "event-template-inheritor",
        requirements: anyAfter(
          "student_asks_community_source",
          "student_compares_sources",
          "student_inspects_source",
        ),
        unavailableReason: "先取得人物采访入口或完成一轮来源核验，才能追问传承人的具体经验。",
      },
      {
        eventTemplateId: "event-template-researcher-probe",
        requirements: anyAfter(
          "student_asks_community_source",
          "student_asks_inheritor",
          "student_compares_sources",
          "student_inspects_source",
        ),
        unavailableReason: "先形成现场或人物主张，再请求研究者判断证据层级。",
      },
      {
        eventTemplateId: "event-template-source-check",
        requirements: { all: [], any: [], none: [] },
        unavailableReason: "当前没有可核对的来源事件。",
      },
      {
        eventTemplateId: "event-template-compare-sources",
        requirements: { all: [], any: [], none: [] },
        unavailableReason: "当前没有可并列比较的来源事件。",
      },
      {
        eventTemplateId: "event-template-official-request",
        requirements: anyAfter(
          "student_compares_sources",
          "student_inspects_source",
          "student_probes_researcher",
        ),
        unavailableReason: "先指出具体冲突或请求研究判断，才能向公共联络员请求带时点数据。",
      },
      {
        eventTemplateId: "event-template-verification-wait",
        requirements: {
          all: [{
            kind: "time_threshold",
            metric: "remaining_minutes",
            operator: "gte",
            value: 10,
          }],
          any: [],
          none: [],
        },
        unavailableReason: "剩余时间不足十分钟，不能再开启可恢复的等待窗口。",
      },
      {
        eventTemplateId: "event-template-rights-inspection",
        requirements: anyAfter(
          "shopkeeper_requests_placement",
          "tourist_withdraws_consent",
          "student_asks_community_source",
        ),
        unavailableReason: "先获得素材或授权线索，再核对人物、用途、平台和期限。",
      },
      {
        eventTemplateId: "event-template-commercial-response",
        requirements: anyAfter("shopkeeper_requests_placement"),
        unavailableReason: "商户尚未提出素材与曝光条件，不能凭空回应商业交换。",
      },
    ],
  });

export function createXunpuFlagshipRuntimeDefinitionV4(
  contentRef: FlagshipContentReferenceV4,
): FlagshipWorldRuntimeDefinitionV4 {
  return FlagshipWorldRuntimeDefinitionV4Schema.parse({
    schemaVersion: FlagshipWorldRuntimeDefinitionV4SchemaVersion,
    definitionId: "xunpu-flagship-world-runtime-v4",
    contentRef,
    externalObjectRefs: ["entity-cultural-association"],
    phases: [
      {
        phaseId: "phase-publication-and-correction",
        priority: 800,
        worldStateRef: "state-publication-and-correction",
        locationId: "loc-newsroom-desk",
        environmentAssetId: "asset-env-editor-desk-wide-01",
        npcRefs: ["entity-editor", "entity-platform-duty", "entity-community-source"],
        objectRefs: ["obj-story-workbench", "obj-publication-window", "obj-claim-board"],
        prompt: "明确提交哪个版本、附带哪些证据，以及发布、暂缓或更正的理由；系统不会替你作价值判断。",
        activation: {
          terminal: true,
          allHandledEventTypes: [],
          anyHandledEventTypes: ["student_submits_story"],
        },
      },
      {
        phaseId: "phase-drafting-r1",
        priority: 700,
        worldStateRef: "state-drafting-r1",
        locationId: "loc-mobile-edit-bay",
        environmentAssetId: "asset-env-editor-desk-wide-01",
        npcRefs: ["entity-editor", "entity-platform-duty"],
        objectRefs: ["obj-story-workbench", "obj-claim-board", "obj-video-bin", "obj-consent-ledger"],
        prompt: "把已确认事实、引语、素材和权利范围编入真实版本；需要制作或保存时进入作品台。",
        activation: {
          terminal: false,
          allHandledEventTypes: [],
          anyHandledEventTypes: ["student_drafts_story"],
        },
      },
      {
        phaseId: "phase-media-rights-review",
        priority: 600,
        worldStateRef: "state-media-rights-review",
        locationId: "loc-mobile-edit-bay",
        environmentAssetId: "asset-env-editor-desk-wide-01",
        npcRefs: ["entity-rights-contact", "entity-tourist", "entity-platform-duty"],
        objectRefs: ["obj-camera-roll", "obj-video-bin", "obj-audio-recorder", "obj-consent-ledger"],
        prompt: "素材已进入编辑台。请核对作者、人物、用途、平台、期限、撤回与 AI 标识，或提出替换方案。",
        activation: {
          terminal: false,
          allHandledEventTypes: [],
          anyHandledEventTypes: ["student_inspects_rights", "tourist_withdraws_consent"],
        },
      },
      {
        phaseId: "phase-commercial-and-consent-negotiation",
        priority: 500,
        worldStateRef: "state-commercial-and-consent-negotiation",
        locationId: "loc-merchant-storefront",
        environmentAssetId: "asset-env-storefront-wide-01",
        npcRefs: ["entity-shopkeeper", "entity-tourist", "entity-rights-contact"],
        objectRefs: ["obj-camera-roll", "obj-consent-ledger", "obj-publication-window"],
        prompt: "商业素材、公开许可与截稿压力同时出现。请给出底线、范围、等待条件或替代方案。",
        activation: {
          terminal: false,
          allHandledEventTypes: [],
          anyHandledEventTypes: ["shopkeeper_requests_placement"],
        },
      },
      {
        phaseId: "phase-source-conflict-active",
        priority: 400,
        worldStateRef: "state-source-conflict-active",
        locationId: "loc-waterfront-service-point",
        environmentAssetId: "asset-env-service-point-01",
        npcRefs: ["entity-researcher", "entity-public-liaison", "entity-community-source"],
        objectRefs: ["obj-source-packet-a", "obj-source-packet-b", "obj-claim-board", "obj-groupchat-rumor"],
        prompt: "来源年份、统计时点或群聊线索存在冲突。请比较原始定位、请求回执或限定表述。",
        activation: {
          terminal: false,
          allHandledEventTypes: [],
          anyHandledEventTypes: ["student_compares_sources", "student_inspects_source"],
        },
      },
      {
        phaseId: "phase-interview-contradiction-visible",
        priority: 300,
        worldStateRef: "state-interview-contradiction-visible",
        locationId: "loc-zanhuawei-workshop",
        environmentAssetId: "asset-env-workshop-close-01",
        npcRefs: ["entity-inheritor", "entity-researcher", "entity-community-source"],
        objectRefs: ["obj-audio-recorder", "obj-source-packet-a", "obj-claim-board"],
        prompt: "现场说法出现边界差异。请指出具体矛盾，继续追问或把不确定主张标成待核。",
        activation: {
          terminal: false,
          allHandledEventTypes: [],
          anyHandledEventTypes: ["student_asks_inheritor"],
        },
      },
      {
        phaseId: "phase-community-interview-open",
        priority: 200,
        worldStateRef: "state-community-interview-open",
        locationId: "loc-community-courtyard",
        environmentAssetId: "asset-env-community-courtyard-01",
        npcRefs: ["entity-community-source", "entity-inheritor", "entity-tourist"],
        objectRefs: ["obj-audio-recorder", "obj-camera-roll", "obj-consent-ledger"],
        prompt: "选择采访对象或记录工具，用开放问题取得经历、文化语境与具体公开范围。",
        activation: {
          terminal: false,
          allHandledEventTypes: ["student_asks_gatekeeper", "student_observes_editorial_brief"],
          anyHandledEventTypes: [],
        },
      },
      {
        phaseId: "phase-at-alley-gate",
        priority: 0,
        worldStateRef: "state-at-alley-gate",
        locationId: "loc-oyster-alley-gate",
        environmentAssetId: "asset-env-oyster-alley-wide-01",
        npcRefs: ["entity-gatekeeper", "entity-editor"],
        objectRefs: [
          "obj-editor-brief",
          "obj-camera-roll",
          "obj-source-packet-a",
          "obj-source-packet-b",
          "obj-claim-board",
        ],
        prompt: "先观察现场并说明记者身份、采访对象与公共拍摄边界。你可以直接用自己的话行动。",
        activation: {
          terminal: false,
          allHandledEventTypes: [],
          anyHandledEventTypes: [],
        },
      },
    ],
    intentBindings: [
      {
        bindingId: "binding-workspace-only",
        priority: 1_000,
        verbs: ["draft", "submit", "escalate"],
        targetRefs: [],
        eventTemplateCandidates: [],
        workspaceOnly: true,
      },
      {
        bindingId: "binding-topic-brief",
        priority: 950,
        verbs: ["observe", "ask", "inspect"],
        targetRefs: ["entity-editor", "obj-editor-brief"],
        eventTemplateCandidates: ["event-template-topic-brief"],
        workspaceOnly: false,
      },
      {
        bindingId: "binding-verification-wait",
        priority: 900,
        verbs: ["wait"],
        targetRefs: [],
        eventTemplateCandidates: ["event-template-verification-wait"],
        workspaceOnly: false,
      },
      {
        bindingId: "binding-rights-inspection",
        priority: 800,
        verbs: [...worldVerbs],
        targetRefs: ["entity-rights-contact", "entity-tourist", "obj-consent-ledger", "obj-video-bin", "obj-camera-roll"],
        eventTemplateCandidates: ["event-template-rights-inspection"],
        workspaceOnly: false,
      },
      {
        bindingId: "binding-official-request",
        priority: 750,
        verbs: [...worldVerbs],
        targetRefs: ["entity-public-liaison", "obj-groupchat-rumor"],
        eventTemplateCandidates: ["event-template-official-request"],
        workspaceOnly: false,
      },
      {
        bindingId: "binding-source-probe",
        priority: 720,
        verbs: ["probe"],
        targetRefs: ["entity-researcher", "obj-source-packet-a", "obj-source-packet-b", "obj-claim-board"],
        eventTemplateCandidates: ["event-template-researcher-probe", "event-template-compare-sources"],
        workspaceOnly: false,
      },
      {
        bindingId: "binding-source-check",
        priority: 700,
        verbs: ["observe", "ask", "inspect", "compare", "negotiate"],
        targetRefs: ["entity-researcher", "obj-source-packet-a", "obj-source-packet-b", "obj-claim-board"],
        eventTemplateCandidates: ["event-template-compare-sources", "event-template-source-check"],
        workspaceOnly: false,
      },
      {
        bindingId: "binding-community-source",
        priority: 650,
        verbs: [...worldVerbs],
        targetRefs: ["entity-community-source"],
        eventTemplateCandidates: ["event-template-community-source"],
        workspaceOnly: false,
      },
      {
        bindingId: "binding-commercial-response",
        priority: 640,
        verbs: [...worldVerbs],
        targetRefs: ["entity-shopkeeper"],
        eventTemplateCandidates: ["event-template-commercial-response"],
        workspaceOnly: false,
      },
      {
        bindingId: "binding-inheritor",
        priority: 630,
        verbs: [...worldVerbs],
        targetRefs: ["entity-inheritor"],
        eventTemplateCandidates: ["event-template-inheritor"],
        workspaceOnly: false,
      },
      {
        bindingId: "binding-gatekeeper",
        priority: 620,
        verbs: [...worldVerbs],
        targetRefs: ["entity-gatekeeper", "loc-oyster-alley-gate"],
        eventTemplateCandidates: ["event-template-gatekeeper"],
        workspaceOnly: false,
      },
    ],
    eventActions: [
      { eventTemplateId: "event-template-topic-brief", action: { verb: "observe", targetRef: { objectType: "entity", objectId: "entity-editor" } } },
      { eventTemplateId: "event-template-gatekeeper", action: { verb: "ask", targetRef: { objectType: "entity", objectId: "entity-gatekeeper" } } },
      { eventTemplateId: "event-template-inheritor", action: { verb: "probe", targetRef: { objectType: "entity", objectId: "entity-inheritor" } } },
      { eventTemplateId: "event-template-community-source", action: { verb: "negotiate", targetRef: { objectType: "entity", objectId: "entity-community-source" } } },
      { eventTemplateId: "event-template-commercial-response", action: { verb: "negotiate", targetRef: { objectType: "entity", objectId: "entity-shopkeeper" } } },
      { eventTemplateId: "event-template-researcher-probe", action: { verb: "probe", targetRef: { objectType: "entity", objectId: "entity-researcher" } } },
      { eventTemplateId: "event-template-official-request", action: { verb: "ask", targetRef: { objectType: "entity", objectId: "entity-public-liaison" } } },
      { eventTemplateId: "event-template-source-check", action: { verb: "compare", targetRefs: [{ objectType: "entity", objectId: "entity-cultural-association" }, { objectType: "entity", objectId: "entity-researcher" }] } },
      { eventTemplateId: "event-template-compare-sources", action: { verb: "compare", targetRefs: [{ objectType: "entity", objectId: "entity-cultural-association" }, { objectType: "entity", objectId: "entity-researcher" }] } },
      { eventTemplateId: "event-template-rights-inspection", action: { verb: "inspect", targetRefs: [{ objectType: "entity", objectId: "entity-rights-contact" }, { objectType: "artifact", objectId: "artifact-rights-ledger" }] } },
      { eventTemplateId: "event-template-verification-wait", action: { verb: "wait", durationMinutes: 10 } },
    ],
    groundedBindings: [
      {
        episodeTemplateRef: "episode-source-year-challenge",
        eventTemplateIds: ["event-template-source-check", "event-template-compare-sources", "event-template-researcher-probe"],
        affectedObjectRefs: ["entity-researcher", "artifact-source-matrix", "artifact-fact-check-sheet"],
        evidenceKinds: ["source_comparison", "official_receipt"],
      },
      {
        episodeTemplateRef: "episode-media-rights-challenge",
        eventTemplateIds: ["event-template-rights-inspection"],
        affectedObjectRefs: ["entity-rights-contact", "artifact-rights-ledger", "artifact-multiplatform-package"],
        evidenceKinds: ["asset_metadata", "consent_receipt", "withdrawal_receipt", "revision_diff", "platform_receipt"],
      },
      {
        episodeTemplateRef: "episode-breaking-rumor-challenge",
        eventTemplateIds: ["event-template-official-request", "event-template-verification-wait"],
        affectedObjectRefs: ["entity-public-liaison", "artifact-fact-check-sheet", "artifact-multiplatform-package"],
        evidenceKinds: ["source_comparison", "official_receipt"],
      },
    ],
    autonomyBindings: [
      { eventType: "student_asks_gatekeeper", actorRef: "entity-gatekeeper", memoryKey: "reporter_identity", staticSignals: { reporter_identity_declared: true }, positiveDeltaSignal: null },
      { eventType: "shopkeeper_requests_placement", actorRef: "entity-shopkeeper", memoryKey: "material_offer", staticSignals: { merchant_offer_received: true }, positiveDeltaSignal: null },
      { eventType: "student_resolves_commercial_exchange", actorRef: "entity-shopkeeper", memoryKey: "student_counteroffer", staticSignals: { commercial_response_recorded: true }, positiveDeltaSignal: { variableId: "editorial_independence", positiveSignal: "placement_rejected_professionally" } },
      { eventType: "system_clock_tick", actorRef: null, memoryKey: null, staticSignals: { deadline_reminder_sent: true, closeup_enters_public_cut: true }, positiveDeltaSignal: null },
      { eventType: "student_asks_community_source", actorRef: "entity-community-source", memoryKey: "purpose_explained", staticSignals: { first_contact: true, purpose_explained: true, open_question_count: 2 }, positiveDeltaSignal: null },
      { eventType: "student_asks_inheritor", actorRef: "entity-inheritor", memoryKey: "framing_intent", staticSignals: { professional_observation_completed: true }, positiveDeltaSignal: null },
      { eventType: "student_compares_sources", actorRef: "entity-researcher", memoryKey: "claims_received", staticSignals: { conflicting_year_claim_received: true, primary_locator_available: true }, positiveDeltaSignal: null },
      { eventType: "student_inspects_source", actorRef: "entity-researcher", memoryKey: "claims_received", staticSignals: { conflicting_year_claim_received: true, primary_locator_available: true }, positiveDeltaSignal: null },
      { eventType: "student_requests_official_data", actorRef: "entity-public-liaison", memoryKey: "questions_received", staticSignals: { first_public_data_question: true, official_response_due: 30 }, positiveDeltaSignal: null },
      { eventType: "student_inspects_rights", actorRef: "entity-rights-contact", memoryKey: "asset_queries", staticSignals: { asset_enters_public_timeline: true }, positiveDeltaSignal: null },
      { eventType: "rights_contact_flags_scope", actorRef: "entity-rights-contact", memoryKey: "asset_queries", staticSignals: { asset_enters_public_timeline: true }, positiveDeltaSignal: null },
      { eventType: "tourist_withdraws_consent", actorRef: "entity-tourist", memoryKey: "withdrawal_time", staticSignals: { camera_targets_tourist: true, consent_withdrawn: true }, positiveDeltaSignal: null },
      { eventType: "student_drafts_story", actorRef: "entity-editor", memoryKey: "student_angle", staticSignals: { revision_r1_ready: true }, positiveDeltaSignal: null },
      { eventType: "student_submits_story", actorRef: "entity-platform-duty", memoryKey: "submission_hashes", staticSignals: { formal_submission_ready: true, story_published: true }, positiveDeltaSignal: null },
    ],
    portraits: [
      { entityId: "entity-editor", assetId: "asset-npc-editor-chen-01" },
      { entityId: "entity-gatekeeper", assetId: "asset-npc-gatekeeper-lin-01" },
      { entityId: "entity-community-source", assetId: "asset-npc-community-ahuan-01" },
      { entityId: "entity-inheritor", assetId: "asset-npc-inheritor-huang-01" },
      { entityId: "entity-researcher", assetId: "asset-npc-researcher-chen-01" },
      { entityId: "entity-shopkeeper", assetId: "asset-npc-shopkeeper-wu-01" },
      { entityId: "entity-public-liaison", assetId: "asset-npc-liaison-cai-01" },
      { entityId: "entity-rights-contact", assetId: "asset-npc-rights-xu-01" },
      { entityId: "entity-tourist", assetId: "asset-npc-tourist-zhou-01" },
      { entityId: "entity-platform-duty", assetId: "asset-npc-platform-qiao-01" },
    ],
  });
}
