import type {
  XunpuAdversarialPairV4,
  XunpuAssessmentCriterionV4,
  XunpuWorkSampleV4,
} from "./types.js";

export const xunpuV4AssessmentCriteria: XunpuAssessmentCriterionV4[] = [
  {
    criterionId: "criterion-fact-verification",
    title: "事实与信源核验",
    weight: 20,
    minimumIndependentEvidenceCount: 3,
    artifactRefs: ["artifact-source-matrix", "artifact-fact-check-sheet", "artifact-feature-story"],
    observableEvidence: ["主张回指原始来源", "处理反证和年份冲突", "对未知项使用限定措辞", "错误后修订正文"],
    failClosedWhen: ["只有最终文本而无核验过程", "来源定位缺失", "把仿真隐藏事实写成公共事实"],
  },
  {
    criterionId: "criterion-interview-consent",
    title: "采访、沟通与知情边界",
    weight: 18,
    minimumIndependentEvidenceCount: 3,
    artifactRefs: ["artifact-interview-plan-log", "artifact-publication-correction-decision"],
    observableEvidence: ["说明身份与用途", "围绕矛盾追问", "记录匿名、删题与撤回", "承诺越界后修复"],
    failClosedWhen: ["只有预写提纲而无 NPC 对话", "没有公开范围记录", "忽略撤回仍提交"],
  },
  {
    criterionId: "criterion-editorial-judgment",
    title: "编辑判断与独立性",
    weight: 18,
    minimumIndependentEvidenceCount: 3,
    artifactRefs: ["artifact-topic-brief", "artifact-feature-story", "artifact-publication-correction-decision"],
    observableEvidence: ["角度连接公共价值", "识别商业交换", "解释时效取舍", "拒绝或披露利益关系"],
    failClosedWhen: ["只有选择结果而无理由", "用触达替代公共价值", "隐藏商业条件"],
  },
  {
    criterionId: "criterion-rights-governance",
    title: "素材权利与内容治理",
    weight: 16,
    minimumIndependentEvidenceCount: 3,
    artifactRefs: ["artifact-rights-ledger", "artifact-multiplatform-package", "artifact-publication-correction-decision"],
    observableEvidence: ["核作者与人物同意", "区分用途、平台与期限", "撤回后替换或补授权", "处理 AI 标识"],
    failClosedWhen: ["素材只有链接或截图", "权利范围不明仍标可用", "教师门未决仍发布"],
  },
  {
    criterionId: "criterion-multiplatform-production",
    title: "融媒体作品生产与适配",
    weight: 14,
    minimumIndependentEvidenceCount: 2,
    artifactRefs: ["artifact-feature-story", "artifact-multiplatform-package"],
    observableEvidence: ["正文有 R1/R2", "图文、音频、视频保持事实一致", "平台适配有受众理由"],
    failClosedWhen: ["只有完成布尔值", "没有媒体派生或正文哈希", "多平台版本相互矛盾"],
  },
  {
    criterionId: "criterion-recovery-transfer",
    title: "纠错恢复、协作与迁移",
    weight: 14,
    minimumIndependentEvidenceCount: 2,
    artifactRefs: ["artifact-publication-correction-decision", "artifact-transfer-reflection"],
    observableEvidence: ["错误后补证或公开更正", "说明 AI 建议取舍", "把策略迁移到下一场"],
    failClosedWhen: ["复盘没有真实轨迹", "只因终局安全判高能力", "只因使用支架直接扣分"],
  },
];

const criteria = {
  fact: "criterion-fact-verification",
  interview: "criterion-interview-consent",
  editorial: "criterion-editorial-judgment",
  rights: "criterion-rights-governance",
  media: "criterion-multiplatform-production",
  recovery: "criterion-recovery-transfer",
} as const;

export const xunpuV4WorkSamples: XunpuWorkSampleV4[] = [
  {
    sampleId: "work-sample-01-traceable-high",
    title: "克制但完整的社区专题",
    synopsis: "正文不追求夸张，核心主张、采访同意、媒体派生和 R1/R2 均可追溯。",
    traceRefs: ["trace-purpose-explained", "trace-source-comparison", "trace-consent-confirmed", "trace-revision-r2"],
    artifactRefs: ["artifact-source-matrix", "artifact-interview-plan-log", "artifact-rights-ledger", "artifact-feature-story", "artifact-multiplatform-package"],
    expectedJudgments: [
      { criterionId: criteria.fact, band: "high", rationale: "关键主张有原始定位和反证处理。" },
      { criterionId: criteria.interview, band: "high", rationale: "存在真实追问、复述和同意范围。" },
      { criterionId: criteria.rights, band: "high", rationale: "媒体与许可逐项对应。" },
      { criterionId: criteria.media, band: "high", rationale: "形成可预览媒体成品和版本链。" },
    ],
    expectedOverallConstraint: "在挑战上限内可进入高水平区间，但仍需教师最终裁决。",
  },
  {
    sampleId: "work-sample-02-polished-fabricated",
    title: "华丽但虚构的起源稿",
    synopsis: "文笔流畅、结构完整，却虚构唯一古代起源并给出不存在的 locator。",
    traceRefs: ["trace-fabricated-source"],
    artifactRefs: ["artifact-feature-story"],
    expectedJudgments: [
      { criterionId: criteria.fact, band: "insufficient_evidence", rationale: "核心事实引用伪造，失败关闭。" },
      { criterionId: criteria.editorial, band: "low", rationale: "以吸引力覆盖事实边界。" },
      { criterionId: criteria.media, band: "medium", rationale: "形式可用不能补偿事实失败。" },
    ],
    expectedOverallConstraint: "不得因文采、长度或完成度进入高分区。",
  },
  {
    sampleId: "work-sample-03-concise-supported",
    title: "短而有证据的解释稿",
    synopsis: "篇幅较短，主动删除非必要数字，所有保留主张都有来源和限定措辞。",
    traceRefs: ["trace-claim-removed", "trace-primary-source-linked", "trace-bounded-wording"],
    artifactRefs: ["artifact-source-matrix", "artifact-fact-check-sheet", "artifact-feature-story"],
    expectedJudgments: [
      { criterionId: criteria.fact, band: "high", rationale: "证据密度高且未知透明。" },
      { criterionId: criteria.editorial, band: "high", rationale: "主动舍弃高风险但不必要信息。" },
      { criterionId: criteria.media, band: "medium", rationale: "媒体形态完整但制作复杂度一般。" },
    ],
    expectedOverallConstraint: "事实与编辑判断必须高于关键词堆砌样例。",
  },
  {
    sampleId: "work-sample-04-keyword-stuffed",
    title: "专业词堆砌稿",
    synopsis: "反复出现真实性、版权、社会价值等词，但无采访、定位、媒体版本和授权回执。",
    traceRefs: ["trace-long-text-only"],
    artifactRefs: ["artifact-feature-story"],
    expectedJudgments: [
      { criterionId: criteria.fact, band: "insufficient_evidence", rationale: "无 claim 到 evidence 关系。" },
      { criterionId: criteria.interview, band: "insufficient_evidence", rationale: "无真实 NPC 对话。" },
      { criterionId: criteria.rights, band: "insufficient_evidence", rationale: "无权利台账和回执。" },
      { criterionId: criteria.media, band: "low", rationale: "只有文字，没有媒体作品。" },
    ],
    expectedOverallConstraint: "关键词、篇幅和专业术语不能通过能力门。",
  },
  {
    sampleId: "work-sample-05-blind-ai-accept",
    title: "盲目采纳建议的安全作品",
    synopsis: "每次都采纳 AI，最终作品安全，但学生无法解释理由和替代方案。",
    traceRefs: ["trace-advice-accepted-all", "trace-no-student-rationale"],
    artifactRefs: ["artifact-feature-story", "artifact-rights-ledger", "artifact-publication-correction-decision"],
    expectedJudgments: [
      { criterionId: criteria.fact, band: "medium", rationale: "作品证据合格但学生核验主动性有限。" },
      { criterionId: criteria.editorial, band: "low", rationale: "无法解释取舍和替代方案。" },
      { criterionId: criteria.recovery, band: "low", rationale: "没有独立策略证据。" },
    ],
    expectedOverallConstraint: "采纳率不能直接加分，安全终局不能覆盖判断不足。",
  },
  {
    sampleId: "work-sample-06-evidenced-rejection",
    title: "有依据拒绝延误建议",
    synopsis: "学生拒绝等待完整数据，改发限定性服务信息，保留官方回执和下一更新时间。",
    traceRefs: ["trace-advice-evidence-requested", "trace-advice-rejected", "trace-limited-update", "trace-official-receipt"],
    artifactRefs: ["artifact-fact-check-sheet", "artifact-multiplatform-package", "artifact-publication-correction-decision"],
    expectedJudgments: [
      { criterionId: criteria.fact, band: "high", rationale: "已知、未知和时点清楚。" },
      { criterionId: criteria.editorial, band: "high", rationale: "拒绝建议有证据和机会成本判断。" },
      { criterionId: criteria.recovery, band: "high", rationale: "能说明 AI 建议边界并迁移策略。" },
    ],
    expectedOverallConstraint: "有依据拒绝不得低于盲目采纳。",
  },
  {
    sampleId: "work-sample-07-failure-recovery",
    title: "R1 失误后的公开恢复",
    synopsis: "R1 含错误年份和权利缺口，学生补证、换图、公开更正并保留旧版。",
    traceRefs: ["trace-initial-error", "trace-platform-rejection", "trace-consent-withdrawal", "trace-public-correction"],
    artifactRefs: ["artifact-fact-check-sheet", "artifact-rights-ledger", "artifact-feature-story", "artifact-publication-correction-decision", "artifact-transfer-reflection"],
    expectedJudgments: [
      { criterionId: criteria.fact, band: "medium", rationale: "初始错误保留，但后续核验有效。" },
      { criterionId: criteria.rights, band: "medium", rationale: "初始许可判断错误，恢复动作完整。" },
      { criterionId: criteria.recovery, band: "high", rationale: "公开更正、版本链和反思充分。" },
    ],
    expectedOverallConstraint: "恢复维度可高，初始判断证据不得被最终安全抹除。",
  },
  {
    sampleId: "work-sample-08-reach-rights-breach",
    title: "高触达但权利失败",
    synopsis: "标题和近景带来高触达，学生无视撤回并静默换图。",
    traceRefs: ["trace-high-reach", "trace-withdrawal-ignored", "trace-silent-edit"],
    artifactRefs: ["artifact-multiplatform-package", "artifact-publication-correction-decision"],
    expectedJudgments: [
      { criterionId: criteria.rights, band: "low", rationale: "无视撤回且破坏版本链。" },
      { criterionId: criteria.editorial, band: "low", rationale: "流量覆盖公共责任。" },
      { criterionId: criteria.media, band: "high", rationale: "技术制作好不代表治理合格。" },
      { criterionId: criteria.recovery, band: "low", rationale: "静默修改不是专业恢复。" },
    ],
    expectedOverallConstraint: "高流量不能覆盖治理失败，综合结果受高风险上限约束。",
  },
];

export const xunpuV4AdversarialPairs: XunpuAdversarialPairV4[] = [
  {
    pairId: "pair-concise-vs-keywords",
    leftSampleRef: "work-sample-03-concise-supported",
    rightSampleRef: "work-sample-04-keyword-stuffed",
    invariant: "短而有证据样例的事实判断必须高于长而无证据样例。",
  },
  {
    pairId: "pair-reject-vs-blind-accept",
    leftSampleRef: "work-sample-06-evidenced-rejection",
    rightSampleRef: "work-sample-05-blind-ai-accept",
    invariant: "有依据拒绝的编辑判断不得低于盲目采纳。",
  },
  {
    pairId: "pair-recovery-vs-clean-success",
    leftSampleRef: "work-sample-07-failure-recovery",
    rightSampleRef: "work-sample-01-traceable-high",
    invariant: "失败恢复可在恢复维度达到高水平，但不能抹掉初始事实和权利错误。",
  },
  {
    pairId: "pair-media-beauty-vs-rights",
    leftSampleRef: "work-sample-08-reach-rights-breach",
    rightSampleRef: "work-sample-01-traceable-high",
    invariant: "制作精美不能使无权利作品通过治理门。",
  },
  {
    pairId: "pair-reach-vs-trust",
    leftSampleRef: "work-sample-08-reach-rights-breach",
    rightSampleRef: "work-sample-03-concise-supported",
    invariant: "高触达不能覆盖事实或权利债务。",
  },
  {
    pairId: "pair-style-vs-traceability",
    leftSampleRef: "work-sample-02-polished-fabricated",
    rightSampleRef: "work-sample-03-concise-supported",
    invariant: "华丽但虚构的作品不得高于克制且可追溯的作品。",
  },
];
