import type {
  XunpuLocationV4,
  XunpuTimelineBeatV4,
  XunpuWorldObjectV4,
  XunpuWorldVariableV4,
} from "./types.js";

export const xunpuV4Locations: XunpuLocationV4[] = [
  {
    locationId: "loc-newsroom-desk",
    title: "移动编辑台",
    publicDescription: "责任编辑、工单、发布窗口和作品版本集中于此。",
    objectRefs: ["obj-editor-brief", "obj-publication-window", "obj-story-workbench"],
    npcRefs: ["entity-editor", "entity-platform-duty"],
    allowedIntents: ["observe", "ask", "inspect", "draft", "save_revision", "request_advice", "submit_gate"],
  },
  {
    locationId: "loc-oyster-alley-gate",
    title: "蚵壳厝巷口",
    publicDescription: "公共巷道、游客流与居民私人空间在此交界。",
    objectRefs: ["obj-camera-roll"],
    npcRefs: ["entity-gatekeeper"],
    allowedIntents: ["observe", "ask", "probe", "negotiate", "record"],
  },
  {
    locationId: "loc-community-courtyard",
    title: "社区公共院落",
    publicDescription: "可在约定边界内采访、录音和确认人物引语。",
    objectRefs: ["obj-audio-recorder", "obj-camera-roll", "obj-consent-ledger"],
    npcRefs: ["entity-community-source", "entity-tourist"],
    allowedIntents: ["observe", "ask", "probe", "record", "negotiate", "annotate"],
  },
  {
    locationId: "loc-zanhuawei-workshop",
    title: "簪花围技艺工作台",
    publicDescription: "可观察项目生成的技艺演示并核对术语。",
    objectRefs: ["obj-camera-roll", "obj-video-bin", "obj-source-packet-a"],
    npcRefs: ["entity-inheritor", "entity-researcher"],
    allowedIntents: ["observe", "ask", "probe", "inspect", "compare", "record", "cite"],
  },
  {
    locationId: "loc-merchant-storefront",
    title: "仿真旅拍门店外",
    publicDescription: "商业诉求、素材吸引力和编辑独立性在此发生冲突。",
    objectRefs: ["obj-camera-roll", "obj-video-bin", "obj-consent-ledger"],
    npcRefs: ["entity-shopkeeper", "entity-rights-contact"],
    allowedIntents: ["observe", "ask", "inspect", "negotiate", "import_media", "replace"],
  },
  {
    locationId: "loc-waterfront-service-point",
    title: "公共服务联络点",
    publicDescription: "用于核验公开数据、服务信息和公共安全线索。",
    objectRefs: ["obj-source-packet-b", "obj-groupchat-rumor", "obj-claim-board"],
    npcRefs: ["entity-public-liaison"],
    allowedIntents: ["ask", "inspect", "compare", "wait", "escalate", "cite"],
  },
  {
    locationId: "loc-mobile-edit-bay",
    title: "移动融媒体工作台",
    publicDescription: "图文、音频、视频、权利和主张在同一作品链中编排。",
    objectRefs: [
      "obj-camera-roll",
      "obj-audio-recorder",
      "obj-video-bin",
      "obj-consent-ledger",
      "obj-claim-board",
      "obj-story-workbench",
    ],
    npcRefs: ["entity-rights-contact", "entity-platform-duty"],
    allowedIntents: [
      "inspect",
      "compare",
      "import_media",
      "transcribe",
      "annotate",
      "replace",
      "wait",
      "draft",
      "save_revision",
      "request_advice",
      "submit_gate",
    ],
  },
];

export const xunpuV4WorldObjects: XunpuWorldObjectV4[] = [
  ["obj-editor-brief", "document", "编辑工单可读，报道角度开放", ["inspect", "compare", "annotate"], true],
  ["obj-source-packet-a", "source_packet", "含地方标准和官方名录定位", ["inspect", "compare", "cite"], true],
  ["obj-source-packet-b", "source_packet", "含转引链、年度统计和冲突年份", ["inspect", "compare", "request_evidence"], true],
  ["obj-groupchat-rumor", "message_capture", "发布主体、时间和现场定位缺失", ["inspect", "compare", "escalate", "reject_advice"], true],
  ["obj-camera-roll", "media_collection", "六张项目生成现场图，权利状态不一", ["import_media", "inspect", "annotate", "replace"], true],
  ["obj-audio-recorder", "media_collection", "三段仿真采访录音和一段环境声", ["inspect", "transcribe", "annotate"], true],
  ["obj-video-bin", "media_collection", "三段项目生成竖屏素材", ["inspect", "annotate", "replace"], true],
  ["obj-consent-ledger", "rights_record", "初始为空", ["draft", "ask", "save_revision"], true],
  ["obj-claim-board", "claim_graph", "两个核心主张处于待核状态", ["draft", "compare", "cite", "save_revision"], true],
  ["obj-publication-window", "world_clock", "剩余五十五个虚拟分钟", ["observe", "request_pause"], false],
  ["obj-story-workbench", "artifact_workspace", "初始无作品版本", ["draft", "save_revision", "compare", "submit_gate"], true],
].map(([objectId, objectKind, initialState, allowedIntents, evidenceBearing]) => ({
  objectId: objectId as string,
  objectKind: objectKind as XunpuWorldObjectV4["objectKind"],
  title: ({
    "obj-editor-brief": "编辑工单",
    "obj-source-packet-a": "原始来源包",
    "obj-source-packet-b": "冲突来源包",
    "obj-groupchat-rumor": "巷口封闭群聊截图",
    "obj-camera-roll": "现场图片库",
    "obj-audio-recorder": "采访录音库",
    "obj-video-bin": "竖屏视频素材库",
    "obj-consent-ledger": "人物与用途确认台账",
    "obj-claim-board": "主张—证据板",
    "obj-publication-window": "首轮发布窗口",
    "obj-story-workbench": "融媒体作品台",
  } as Record<string, string>)[objectId as string]!,
  initialState: initialState as string,
  allowedIntents: allowedIntents as XunpuWorldObjectV4["allowedIntents"],
  evidenceBearing: evidenceBearing as boolean,
}));

export const xunpuV4Variables: XunpuWorldVariableV4[] = [
  ["community_trust", "社区信任", 45, "社区更愿继续回应", "合作空间正在扩大"],
  ["source_access", "信源可达", 35, "可访问人物和材料更多", "更多采访与材料入口可用"],
  ["evidence_confidence", "证据置信", 25, "核心主张更可发布", "关键事实的依据更稳固"],
  ["editorial_independence", "编辑独立", 70, "较少受利益交换支配", "选题独立性保持良好"],
  ["copyright_risk", "版权与肖像风险", 20, "素材权利风险更高", "素材仍需权利核对"],
  ["public_safety_risk", "公共安全风险", 15, "未核安全信息损害更大", "公共服务表述风险可控"],
  ["deadline_pressure", "截稿压力", 25, "首轮发布窗口更紧", "仍有可规划的核验时间"],
  ["public_trust", "公共可信", 50, "发布后公共可信度更高", "作品可信度处于中性"],
  ["reach_potential", "传播潜力", 35, "可能触达更多受众", "传播潜力仍待作品形成"],
  ["correction_debt", "更正债务", 0, "未处理事实或权利债务更多", "当前没有更正债务"],
  ["platform_risk", "平台风险", 10, "退回、投诉或下架风险更高", "平台风险较低"],
].map(([variableId, title, initialValue, higherMeans, studentProjection]) => ({
  variableId: variableId as XunpuWorldVariableV4["variableId"],
  title: title as string,
  initialValue: initialValue as number,
  minimum: 0 as const,
  maximum: 100 as const,
  higherMeans: higherMeans as string,
  studentProjection: studentProjection as string,
}));

export const xunpuV4TimelineBeats: XunpuTimelineBeatV4[] = [
  ["beat-editorial-brief", "evt-brief-window-open", 0, "编辑工单开放", ["session"], "会话启动", true, false, ["obj-editor-brief"]],
  ["beat-access", "evt-gatekeeper-boundary-check", 3, "门卫核查采访范围", ["student_action", "npc_plan"], "首次进入巷口", true, true, ["entity-gatekeeper", "community_trust", "source_access"]],
  ["beat-purpose", "evt-community-purpose-test", 7, "社区质疑报道目的", ["student_action", "npc_plan"], "首次接触阿环或黄老师", true, true, ["entity-community-source", "entity-inheritor"]],
  ["beat-commercial", "evt-merchant-material-exchange", 12, "商户以素材换曝光", ["student_action", "npc_plan"], "检查商户素材或采访经营", true, true, ["entity-shopkeeper", "editorial_independence"]],
  ["beat-source-conflict", "evt-year-claim-conflict", 16, "来源年份发生冲突", ["student_action", "threshold"], "年份或起源主张进入 claim board", true, true, ["obj-source-packet-a", "obj-source-packet-b", "obj-claim-board"]],
  ["beat-data-wait", "evt-official-data-pending", 20, "最新公共数据待汇总", ["student_action", "npc_plan"], "询问当日客流或安全", true, true, ["entity-public-liaison", "evidence_confidence"]],
  ["beat-rights", "evt-portrait-consent-withdrawn", 24, "近景公开许可被撤回", ["student_action", "npc_plan"], "周女士近景进入公开视频版本", true, true, ["entity-tourist", "obj-video-bin", "copyright_risk"]],
  ["beat-rumor", "evt-alley-closure-rumor", 29, "巷口封闭传言出现", ["clock", "threshold"], "世界分钟达到 29 或安全风险达到 35", true, true, ["obj-groupchat-rumor", "public_safety_risk"]],
  ["beat-deadline", "evt-publication-window-narrowed", 35, "首轮窗口收窄", ["clock"], "世界分钟达到 35", true, false, ["obj-publication-window", "deadline_pressure"]],
  ["beat-precheck", "evt-platform-precheck", 42, "平台检查 R1", ["student_action", "threshold"], "存在可发布 R1", true, true, ["entity-platform-duty", "obj-story-workbench"]],
  ["beat-publication", "evt-publication-gate-open", 48, "正式发布教师门开放", ["student_action"], "学生提交正式发布", false, true, ["obj-story-workbench", "platform_risk"]],
  ["beat-consequence", "evt-postpublication-response", 51, "传播后果抵达", ["npc_plan", "threshold"], "发布或审慎暂缓后", true, true, ["entity-community-source", "entity-inheritor", "entity-tourist", "entity-public-liaison", "entity-platform-duty", "public_trust", "reach_potential", "correction_debt"]],
  ["beat-recovery", "evt-correction-window", 53, "更正窗口开放", ["npc_plan", "threshold"], "存在更正债务或平台标记", true, true, ["entity-editor", "entity-platform-duty", "obj-story-workbench", "correction_debt"]],
  ["beat-transfer", "evt-transfer-review", 55, "终局与第二场输入", ["threshold"], "世界进入终局", true, false, ["obj-story-workbench"]],
].map(([beatId, eventId, worldMinute, title, triggerKinds, triggerRule, proactive, canBePreempted, affectedObjectRefs]) => ({
  beatId: beatId as string,
  eventId: eventId as string,
  worldMinute: worldMinute as number,
  title: title as string,
  triggerKinds: triggerKinds as XunpuTimelineBeatV4["triggerKinds"],
  triggerRule: triggerRule as string,
  proactive: proactive as boolean,
  canBePreempted: canBePreempted as boolean,
  affectedObjectRefs: affectedObjectRefs as string[],
}));
