import { useEffect, useState, type CSSProperties } from 'react';
import { ArrowRight, BookOpen, Check, ChevronRight, FileImage, GitBranch, GripVertical, LoaderCircle, Plus, Save, Send, Trash2, UserRound } from 'lucide-react';
import { createDefaultCharacterWorkflowV3, CharacterBlueprintV3Schema, type CharacterBlueprintV3, type CharacterStudioWorkspaceV3 } from '@ronggang/contracts';
import type { TeachingAuthorContext, TeachingTaskGateway } from '../teaching-task-gateway';
import './character-studio.css';
const firstCourse = 'course-xunpu-intangible-media';
function initialCharacter(workspace: CharacterStudioWorkspaceV3): CharacterBlueprintV3 {
  const region = workspace.courses.find(course=>course.courseId===workspace.draft.courseId)!.regionId;
  return { id:'character-'+crypto.randomUUID(), name:'新人物', role:'现场联络员', nodeId:workspace.nodes[0]!.id,
    goal:'帮助来访者了解自己岗位范围内的工作。',personality:'做事认真，先听清具体问题，再用朴实的语言回应；不了解的事情会说明不知道。',unknown:'不替其他人承诺权限，不补写没有依据的经历和数字。',greeting:'你好，我在这里负责现场联络，你想具体了解什么？',
    appearance:{image:`/assets/v3/${region}-actors.png`,x:.62,y:.94,height:.58,atlas:{columns:3,rows:1,index:0}},
    social:{supportsContact:true,initialTrust:15,contactThreshold:25,referralThreshold:45,referralTargets:[],refusal:'我们先把现场的事情沟通清楚，再考虑保留联系方式。'},knowledgeIds:[],
    topics:[{id:'work',title:'我的工作范围',keywords:['工作','负责','范围'],response:'我负责自己值守区域的联络。其他岗位的决定需要向相应负责人确认，我可以帮你分清要核对什么。',sourceKind:'simulation',sourceTitle:'教师编排的岗位工作说明',sourceUrl:null}],
    workflow:createDefaultCharacterWorkflowV3()};
}
export function CharacterStudioPage({gateway,context}: {gateway:TeachingTaskGateway;context:TeachingAuthorContext}) {
  const [courseId,setCourseId]=useState(firstCourse),[workspace,setWorkspace]=useState<CharacterStudioWorkspaceV3|null>(null);
  const [characters,setCharacters]=useState<CharacterBlueprintV3[]>([]),[selected,setSelected]=useState<string|null>(null),[activeNode,setActiveNode]=useState('understand');
  const [tab,setTab]=useState<'persona'|'knowledge'|'relations'|'art'>('persona'),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null);
  const [rights,setRights]=useState('我确认有权将此人物立绘用于本课程教学仿真。');
  const accept=(value:CharacterStudioWorkspaceV3)=>{setWorkspace(value);setCharacters(value.draft.characters);setSelected(current=>value.draft.characters.some(person=>person.id===current)?current:value.draft.characters[0]?.id??null);};
  useEffect(()=>{const controller=new AbortController();setError(null);setWorkspace(null);if(!gateway.studioWorkspace){setError('当前连接未启用人物课程导演。');return;}
    gateway.studioWorkspace(courseId,controller.signal).then(value=>{if(!controller.signal.aborted)accept(value);}).catch(cause=>{if(!controller.signal.aborted)setError(cause instanceof Error?cause.message:'课程配置读取失败');});return()=>controller.abort();},[gateway,courseId]);
  const person=characters.find(person=>person.id===selected),dirty=workspace?JSON.stringify(characters)!==JSON.stringify(workspace.draft.characters):false;
  const patch=(change:Partial<CharacterBlueprintV3>)=>setCharacters(current=>current.map(value=>value.id===selected?{...value,...change}:value));
  const perform=async(label:string,action:()=>Promise<void>)=>{setBusy(label);setError(null);setNotice(null);try{await action();}catch(cause){setError(cause instanceof Error?cause.message:'人物配置未完成，请保留输入再试。');}finally{setBusy(null);}};
  const save=()=>void perform('保存',async()=>{if(!workspace||!gateway.saveStudio)throw new Error('人物保存接口未启用');const result=characters.map(person=>CharacterBlueprintV3Schema.safeParse(person));const invalid=result.find(result=>!result.success);if(invalid&&!invalid.success)throw new Error('请补全人物配置：'+invalid.error.issues[0]?.message);accept(await gateway.saveStudio(context,workspace.draft,characters));setNotice('人物配置已保存，可以审阅并发布。');});
  const publish=()=>void perform('发布',async()=>{if(!workspace||!gateway.publishStudio)throw new Error('人物发布接口未启用');accept(await gateway.publishStudio(context,workspace.draft));setNotice('已发布。之后新开的课程将使用这份人物配置；正在进行的场次保持原版本。');});
  const upload=(file:File)=>void perform('上传立绘',async()=>{if(!person||!gateway.uploadStudioArt)throw new Error('立绘上传未启用');if(file.type!=='image/png'||file.size>2_000_000)throw new Error('请选择不超过 2MB 的透明 PNG 立绘。');
    const dataUrl=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('图片读取失败'));reader.readAsDataURL(file);});
    const image=await gateway.uploadStudioArt(context,courseId,{name:file.name,dataUrl,rightsStatement:rights});patch({appearance:{image,x:person.appearance.x,y:person.appearance.y,height:person.appearance.height}});setNotice('立绘已进入课程素材库，保存并发布后即可出现在新场次。');});
  const active=person?.workflow.nodes.find(node=>node.id===activeNode)??person?.workflow.nodes[0];
  return <main className="character-studio"><header className="studio-heading"><div><span>TEACHING STUDIO / CHARACTER AUTHORING</span><h1>让人物走进课堂</h1><p>围绕岗位任务配置人物，在开课之前设计他们的知识、关系与回应方式。</p></div><div><button type="button" disabled={!!busy||!dirty} onClick={save}><Save/>保存配置</button><button type="button" className="primary" disabled={!!busy||dirty||!workspace?.draft.revision||workspace.publication?.draftRevision===workspace.draft.revision} onClick={publish}><Send/>发布到新开课程</button></div></header>
    {(error||notice)?<p className={error?'studio-error':'studio-notice'} role={error?'alert':'status'}>{busy?<LoaderCircle className="spin"/>:null}{error??notice}</p>:null}
    {!workspace&&!error?<p className="studio-loading">正在打开课程工作室…</p>:null}
    {workspace?<div className="studio-layout"><aside className="studio-library"><label>本次配置的课程<select value={courseId} disabled={!!busy} onChange={event=>{if(!dirty||window.confirm('当前配置尚未保存。确认切换课程并放弃这些修改？'))setCourseId(event.target.value);}}>{workspace.courses.map(course=><option key={course.courseId} value={course.courseId}>{course.region} · {course.title}</option>)}</select></label>
      <div className="studio-library-title"><h2>本课人物</h2><button type="button" aria-label="新增课程人物" disabled={!!busy} onClick={()=>{const next=initialCharacter(workspace);setCharacters(current=>[...current,next]);setSelected(next.id);setTab('persona');}}><Plus/></button></div>
      {characters.length?<div className="studio-cast">{characters.map(character=><button type="button" className={person?.id===character.id?'selected':''} key={character.id} onClick={()=>setSelected(character.id)}><UserRound/><span><strong>{character.name}</strong><small>{character.role}</small></span><ChevronRight/></button>)}</div>:<p className="studio-empty-small">从一个有明确岗位和知识边界的人物开始。</p>}
      <details className="studio-existing"><summary>基础课程人物 · {workspace.people.length}</summary>{workspace.people.map(person=><p key={person.id}><strong>{person.name}</strong><small>{person.role}</small></p>)}</details>
      <div className="studio-release"><BookOpen/><span>{workspace.publication?`已发布配置 R${workspace.publication.draftRevision}`:'尚未发布自定义人物'}<small>在学课程使用开课时冻结的版本</small></span></div>
    </aside><section className="studio-canvas">{person?<><header><div><span>CHARACTER FLOW</span><h2>{person.name}<small>{person.role}</small></h2></div><button type="button" className="studio-delete" disabled={!!busy} onClick={()=>{if(window.confirm(`从当前草案移除${person.name}？已发布场次不会受影响。`)){setCharacters(current=>current.filter(value=>value.id!==person.id));setSelected(null);}}}><Trash2/>移除</button></header>
      <div className="studio-flow" aria-label="人物智能体流程">{person.workflow.nodes.map((node,index)=><div key={node.id}><button type="button" className={`${active?.id===node.id?'active':''} ${node.enabled?'':'disabled'}`} onClick={()=>setActiveNode(node.id)}><span>{String(index+1).padStart(2,'0')}</span><strong>{node.label}</strong><small>{node.enabled?'已启用':'未启用'}</small></button>{index<5?<ArrowRight/>:null}</div>)}</div>
      {active?<section className="studio-node-editor"><header><GitBranch/><h3>{active.label}</h3>{!['understand','decide','reply'].includes(active.kind)?<label><input type="checkbox" checked={active.enabled} onChange={event=>patch({workflow:{...person.workflow,nodes:person.workflow.nodes.map(node=>node.id===active.id?{...node,enabled:event.target.checked}:node)}})}/>启用此节点</label>:<small>必要节点</small>}</header><p>{({understand:'理解学生此刻的来意，区分提问、商量与明确行动请求。',knowledge:'仅检索人物被授予的课程资料，保留不知道的边界。',memory:'承接这名学生与人物过去的有效交流和关系。',decide:'结合人物目标、意愿和条件判断接下来怎样回应。',tools:'通过受控工具记录认识、加好友与引荐，拒绝不成立的动作。',reply:'给出自然的现场回应，不将未完成的动作说成已经成功。'} as const)[active.kind]}</p>
        <textarea rows={5} aria-label="节点教学指令" placeholder="可补充该节点的具体要求；留空使用默认流程。" maxLength={1600} value={active.instruction} onChange={event=>patch({workflow:{...person.workflow,nodes:person.workflow.nodes.map(node=>node.id===active.id?{...node,instruction:event.target.value}:node)}})}/>
        {active.kind==='memory'?<label className="studio-inline">近期对话保留轮数<input type="number" min={1} max={16} value={person.workflow.memoryWindow} onChange={event=>patch({workflow:{...person.workflow,memoryWindow:Number(event.target.value)}})}/><small>长期摘要按话题相关性择取</small></label>:null}
      </section>:null}<p className="studio-boundary"><Check/>默认流程可以直接运行。节点调整在保存时检查，发布后交由同一现场内核运行。</p></>:<div className="studio-empty"><UserRound/><h2>设计一位有话可说的人物</h2><p>添加人物后，在这里查看默认流程，并逐项调整理解、知识、记忆和行动方式。</p><button type="button" onClick={()=>{const next=initialCharacter(workspace);setCharacters([...characters,next]);setSelected(next.id);}}><Plus/>添加人物</button></div>}</section>
    <aside className="studio-properties">{person?<><nav>{([['persona','人设'],['knowledge','知识'],['relations','关系'],['art','立绘']] as const).map(([id,title])=><button type="button" className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{title}</button>)}</nav>
      {tab==='persona'?<div className="studio-fields"><label>名称<input value={person.name} maxLength={40} onChange={event=>patch({name:event.target.value})}/></label><label>岗位身份<input value={person.role} maxLength={80} onChange={event=>patch({role:event.target.value})}/></label><label>出现的位置<select value={person.nodeId} onChange={event=>patch({nodeId:event.target.value})}>{workspace.nodes.map(node=><option key={node.id} value={node.id}>{node.title}</option>)}</select></label><label>当下目标<textarea rows={3} value={person.goal} onChange={event=>patch({goal:event.target.value})}/></label><label>性格与表达习惯<textarea rows={5} value={person.personality} onChange={event=>patch({personality:event.target.value})}/></label><label>知识和承诺边界<textarea rows={3} value={person.unknown} onChange={event=>patch({unknown:event.target.value})}/></label><label>初次招呼<textarea rows={3} value={person.greeting} onChange={event=>patch({greeting:event.target.value})}/></label></div>:null}
      {tab==='knowledge'?<div className="studio-fields"><h3>可以谈论的事情</h3>{person.topics.map((topic,index)=><section className="studio-topic" key={index}><label>话题<input value={topic.title} onChange={event=>patch({topics:person.topics.map((item,i)=>i===index?{...item,title:event.target.value}:item)})}/></label><label>识别词（用逗号分开）<input value={topic.keywords.join('，')} onChange={event=>patch({topics:person.topics.map((item,i)=>i===index?{...item,keywords:event.target.value.split(/[,，]/u)}:item)})}/></label><label>人物掌握的内容<textarea rows={5} value={topic.response} onChange={event=>patch({topics:person.topics.map((item,i)=>i===index?{...item,response:event.target.value}:item)})}/></label><label>资料性质<select value={topic.sourceKind} onChange={event=>patch({topics:person.topics.map((item,i)=>i===index?{...item,sourceKind:event.target.value as typeof topic.sourceKind}:item)})}><option value="simulation">教师编排的仿真经历</option><option value="reference_guide">有公开来源的方法资料</option></select></label><label>资料名称<input value={topic.sourceTitle} onChange={event=>patch({topics:person.topics.map((item,i)=>i===index?{...item,sourceTitle:event.target.value}:item)})}/></label>{topic.sourceKind==='reference_guide'?<label>原始资料链接<input type="url" value={topic.sourceUrl??''} onChange={event=>patch({topics:person.topics.map((item,i)=>i===index?{...item,sourceUrl:event.target.value||null}:item)})}/></label>:null}{person.topics.length>1?<button type="button" onClick={()=>patch({topics:person.topics.filter((_,i)=>i!==index)})}>移除此话题</button>:null}</section>)}<button type="button" className="studio-add-topic" onClick={()=>patch({topics:[...person.topics,{id:'topic-'+crypto.randomUUID().slice(0,8),title:'新话题',keywords:['问题'],response:'请在这里写入人物确实掌握的具体内容和范围。',sourceKind:'simulation',sourceTitle:'教师配置的现场材料',sourceUrl:null}]})}><Plus/>增加话题</button><h3>连接课程资料库</h3><p>选中的资料进入人物检索范围。</p>{workspace.knowledge.length?workspace.knowledge.map(knowledge=><label className="studio-check" key={knowledge.knowledgeId}><input type="checkbox" checked={person.knowledgeIds.includes(knowledge.knowledgeId)} onChange={event=>patch({knowledgeIds:event.target.checked?[...person.knowledgeIds,knowledge.knowledgeId]:person.knowledgeIds.filter(id=>id!==knowledge.knowledgeId)})}/><span>{knowledge.title}</span></label>):<p>本课程暂无可连接的数据库条目，可以先编排仿真话题。</p>}</div>:null}
      {tab==='relations'?<div className="studio-fields"><label className="studio-check"><input type="checkbox" checked={person.social.supportsContact} onChange={event=>patch({social:{...person.social,supportsContact:event.target.checked}})}/>愿意在条件满足后加好友</label>{([['initialTrust','初次交流的开放程度'],['contactThreshold','加好友所需的关系程度'],['referralThreshold','愿意引荐所需的关系程度']] as const).map(([field,label])=><label key={field}>{label}<input type="range" min={0} max={100} value={person.social[field]} onChange={event=>patch({social:{...person.social,[field]:Number(event.target.value)}})}/><small>{person.social[field]} / 100 · 是仿真关系参数，不是学生评分</small></label>)}<label>暂不愿意时如何回应<textarea rows={4} value={person.social.refusal} onChange={event=>patch({social:{...person.social,refusal:event.target.value}})}/></label><h3>能够介绍的人</h3>{[...workspace.people,...characters].filter(value=>value.id!==person.id).map(target=><label className="studio-check" key={target.id}><input type="checkbox" checked={person.social.referralTargets.includes(target.id)} onChange={event=>patch({social:{...person.social,referralTargets:event.target.checked?[...person.social.referralTargets,target.id]:person.social.referralTargets.filter(id=>id!==target.id)}})}/>{target.name}</label>)}</div>:null}
      {tab==='art'?<div className="studio-fields"><div className="studio-art-preview"><div style={{'--art-columns':person.appearance.atlas?.columns??1,'--art-index':person.appearance.atlas?.index??0} as CSSProperties}><img src={person.appearance.image} alt={`${person.name}立绘`}/></div></div><label>素材库人物<select value={person.appearance.atlas?.index??0} onChange={event=>{const region=workspace.courses.find(course=>course.courseId===courseId)!.regionId;patch({appearance:{...person.appearance,image:`/assets/v3/${region}-actors.png`,atlas:{columns:3,rows:1,index:Number(event.target.value)}}});}}><option value={0}>立绘一</option><option value={1}>立绘二</option><option value={2}>立绘三</option></select></label><label>自有立绘使用说明<textarea rows={2} value={rights} onChange={event=>setRights(event.target.value)}/></label><label className="studio-upload"><FileImage/>上传透明 PNG<input type="file" accept="image/png" disabled={!!busy} onChange={event=>{const file=event.target.files?.[0];event.target.value='';if(file)upload(file);}}/></label><small>不超过 2MB；人物需完整、背景透明。</small>{([['x','场景水平位置',.1,.9],['y','站立基线',.55,1],['height','人物大小',.25,.85]] as const).map(([field,label,min,max])=><label key={field}>{label}<input type="range" step={.01} min={min} max={max} value={person.appearance[field]} onChange={event=>patch({appearance:{...person.appearance,[field]:Number(event.target.value)}})}/></label>)}</div>:null}
    </>:<div className="studio-properties-empty"><GripVertical/><p>选择或添加人物后编辑属性。</p></div>}</aside></div>:null}
  </main>;
}
