import {expect,test} from '@playwright/test';
import {readFile} from 'node:fs/promises';
test.use({video:'off',trace:'off'});
test('公开导览：仓库子路径、三地区、私人笔记与作品导出',async({page},info)=>{
  test.setTimeout(120000);
  const errors:string[]=[],apiRequests:string[]=[],lessonRequests:string[]=[],imageRequests:string[]=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('request',request=>{const path=new URL(request.url()).pathname;if(path.startsWith('/api/'))apiRequests.push(request.url());if(path.includes('/lessons/'))lessonRequests.push(path);if(request.resourceType()==='image')imageRequests.push(path);});
  await page.goto('/ganglian-zhixun/');
  await expect(page.locator('.v3-archive')).toHaveAttribute('data-ready','true');
  await expect(page.locator('.archive-render-message')).toHaveCount(0);
  expect(lessonRequests).toEqual([]);
  await expect(page.locator('.archive-field-canvas')).toHaveAttribute('data-target-fps','30');
  await page.screenshot({path:info.outputPath('public-home.png')});
  await page.getByRole('button',{name:'展开档案',exact:true}).click();
  await page.getByRole('button',{name:'查看档案：蟳埔 · 社区深度采访',exact:true}).click();
  await page.getByRole('button',{name:'进入课程导览',exact:true}).click();
  await expect(page.getByRole('heading',{name:'巷口',exact:true})).toBeVisible();
  await expect(page.locator('.tour-scene')).toHaveAttribute('data-loaded','true');
  expect(lessonRequests).toHaveLength(1);
  await page.getByRole('button',{name:'采访本',exact:true}).click();
  await page.getByRole('textbox',{name:'采访笔记'}).fill('我的私人笔记，不默认提交。');
  await expect.poll(()=>page.evaluate(()=>localStorage.getItem('ganglian-public-student-v1'))).toContain('我的私人笔记');
  await page.getByRole('button',{name:'关闭',exact:true}).click();
  await page.reload();
  await page.getByRole('button',{name:'采访本',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'采访笔记'})).toHaveValue('我的私人笔记，不默认提交。');
  await page.getByRole('button',{name:'关闭',exact:true}).click();
  await page.getByRole('button',{name:'作品草稿',exact:true}).click();
  await page.locator('.tour-field textarea').first().fill('在这里记录自己核实后的报道角度。');
  const downloaded=page.waitForEvent('download');
  await page.getByRole('button',{name:'导出作品草稿',exact:true}).click();
  const file=await downloaded;
  const content=await readFile((await file.path())!,'utf8');
  expect(content).toContain('自己核实后的报道角度');
  expect(content).not.toContain('我的私人笔记');
  await page.getByRole('button',{name:'关闭',exact:true}).click();
  await page.getByRole('button',{name:'地图',exact:true}).click();
  await expect(page.locator('.tour-map button')).toHaveCount(20);
  await page.locator('.tour-map button').filter({hasText:'花材准备场'}).click();
  await expect(page.getByRole('heading',{name:'花材准备场',exact:true})).toBeVisible();
  await expect(page.locator('.tour-scene')).toHaveAttribute('data-loaded','true');
  await page.screenshot({path:info.outputPath('public-tour.png')});
  for(const [label,title] of [['榕江 · 赛事采编','赛事广场'],['山地景区 · 暴雨服务报道','游客中心前场']]) {
    await page.getByRole('button',{name:'课程档案',exact:true}).click();
    await page.getByRole('button',{name:'展开档案',exact:true}).click();
    await page.getByRole('button',{name:'查看档案：'+label,exact:true}).click();
    await page.getByRole('button',{name:'进入课程导览',exact:true}).click();
    await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();
    await expect(page.locator('.tour-scene')).toHaveAttribute('data-loaded','true');
  }
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:info.outputPath('public-mobile.png')});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);
  expect(apiRequests).toEqual([]);expect(errors).toEqual([]);
  expect(imageRequests.filter(path=>path.endsWith('.png'))).toEqual([]);
});
