import {
  ScenarioExperienceSchemaVersion,
  ScenarioPackageSchema,
  type RoleContract,
  type ScenarioDirectorEventTemplate,
  type ScenarioExperienceDesign,
  type ScenarioNode,
  type ScenarioNodeExperienceMapping,
  type ScenarioPackage,
} from "@ronggang/contracts";
import {
  createResourceAudience,
  hashContent,
} from "@ronggang/context-engine";
import { demoScenario } from "./scenario.js";

const flagshipVersion = "1.1.0";
const flagshipPatchVersion = "1.1.1";
const transferScenarioId = "scenario-rain-closure-briefing-v1";
const transferCourseId = "course-converged-media-transfer";
const transferVersion = "1.0.0";
const teamId = "team-jiangnan-01";

function nodeExperience(input: {
  nodeId: string;
  task: ScenarioNodeExperienceMapping["operationTasks"][number];
  opportunity: ScenarioNodeExperienceMapping["worldOpportunities"][number];
  gap: ScenarioNodeExperienceMapping["npcInformationGaps"][number];
  contribution: ScenarioNodeExperienceMapping["agentContributions"][number];
  dynamicEvent: ScenarioNodeExperienceMapping["dynamicEvents"][number];
  deliverable: ScenarioNodeExperienceMapping["stageDeliverables"][number];
  evidence: ScenarioNodeExperienceMapping["capabilityEvidence"][number];
}): ScenarioNodeExperienceMapping {
  return {
    nodeId: input.nodeId,
    operationTasks: [input.task],
    worldOpportunities: [input.opportunity],
    npcInformationGaps: [input.gap],
    agentContributions: [input.contribution],
    dynamicEvents: [input.dynamicEvent],
    stageDeliverables: [input.deliverable],
    capabilityEvidence: [input.evidence],
  };
}

const flagshipNodeMappings: ScenarioNodeExperienceMapping[] = [
  nodeExperience({
    nodeId: "brief",
    task: {
      taskId: "flagship-task-topic-plan",
      label: "提交选题、受众与信源计划",
      description: "记者与责任编辑共同确认选题价值、目标受众、首轮信源、岗位边界和三项风险假设。",
      roleIds: ["responsible_editor", "reporter"],
      expectedOutput: "选题调研卡、岗位分工和首轮信源计划",
      completionSignal: "任务卡形成可追溯修订",
    },
    opportunity: {
      opportunityId: "flagship-opportunity-chief-brief",
      sceneId: "scene-newsroom-brief",
      hotspotId: "hotspot-chief-brief",
      label: "向总编确认选题与发布门",
      choiceRefs: ["editor-chief-gate", "editor-chief-commit"],
      studentVisibleConsequence: "总编的证据门和不放行承诺进入共享待办，决定后续可采访人物与发布边界。",
    },
    gap: {
      gapId: "flagship-gap-chief-gate",
      npcActorId: "agent-chief",
      knownInformation: "总编知道首发时限、三个发布门和可接受的降级方案。",
      withheldInformation: "总编不会在学生未说明风险和证据缺口时主动给出完整放行标准。",
      revealCondition: "责任编辑明确客流、版权和平台三项不确定性并请求终审承诺。",
      resultingObjectKinds: ["角色承诺", "发布门禁", "正式待办"],
    },
    contribution: {
      contributionId: "flagship-contribution-task-plan",
      templateId: "assistant/task-planning",
      plane: "student_assistance",
      trigger: "选题调研卡或证据缺口发生变化时成为按需候选。",
      outputKind: "advisory_only 任务优先级与缺失输入建议",
      authority: "advisory_only",
    },
    dynamicEvent: {
      dynamicEventId: "flagship-event-assignment-window",
      eventType: "session_started",
      triggerKind: "initial_state",
      triggerRef: "session_started",
      worldChanges: ["首发倒计时开始", "总编发布门生效", "选题与信源任务开放"],
      affectedTaskIds: ["flagship-task-topic-plan"],
      approvalPolicyId: null,
    },
    deliverable: {
      deliverableId: "flagship-deliverable-topic-plan",
      label: "选题调研与信源计划",
      objectKind: "course_task_revision",
      templateId: null,
      required: true,
    },
    evidence: {
      evidenceRequirementId: "flagship-evidence-topic-research",
      competencyId: "C-TOPIC-01",
      behavior: "学生根据受众、可得信源和风险假设修订选题，而不是直接套用既定标题。",
      evidenceKind: "选题版本、NPC问题与修订理由",
      sourceRefs: [
        "flagship-task-topic-plan",
        "flagship-deliverable-topic-plan",
        "flagship-event-assignment-window",
      ],
      successCriterion: "能够回指至少一项新信息如何改变选题或信源优先级。",
    },
  }),
  nodeExperience({
    nodeId: "source",
    task: {
      taskId: "flagship-task-npc-interview",
      label: "完成两轮NPC采访与信息边界标注",
      description: "记者先问制作流程，再追问客流口径；责任编辑接收可确认、不可确认和承诺三类交接。",
      roleIds: ["reporter", "responsible_editor"],
      expectedOutput: "两轮采访记录、声明—来源边界和岗位交接",
      completionSignal: "采访对象响应与承诺进入同一私有线程",
    },
    opportunity: {
      opportunityId: "flagship-opportunity-interviewee",
      sceneId: "scene-heritage-market",
      hotspotId: "hotspot-interviewee",
      label: "采访传承人与追问客流边界",
      choiceRefs: [
        "reporter-interview-process",
        "reporter-followup-visitors",
      ],
      studentVisibleConsequence: "采访对象说明可确认的制作流程、拒绝猜测精确客流，并承诺提供流程记录。",
    },
    gap: {
      gapId: "flagship-gap-interviewee-boundary",
      npcActorId: "agent-interviewee",
      knownInformation: "采访对象亲历展演流程并知道现场排队情况。",
      withheldInformation: "采访对象不知道去重后的精确客流，也不会替活动方确认统计口径。",
      revealCondition: "记者先完成流程采访，再明确询问哪些信息不能确认及下一核验来源。",
      resultingObjectKinds: ["采访线索", "拒绝边界", "角色承诺", "待核声明"],
    },
    contribution: {
      contributionId: "flagship-contribution-interview-structure",
      templateId: "assistant/interview-structuring",
      plane: "material_production",
      trigger: "采访转写形成固定材料版本后按请求岗位实例化。",
      outputKind: "采访纪要草稿、待确认声明与追问清单",
      authority: "advisory_only",
    },
    dynamicEvent: {
      dynamicEventId: "flagship-event-interview-refusal",
      eventType: "role_interaction_responded",
      triggerKind: "student_action",
      triggerRef: "reporter-followup-visitors",
      worldChanges: ["精确客流保持未确认", "新增流程记录承诺", "事实核验任务成为主线"],
      affectedTaskIds: [
        "flagship-task-npc-interview",
        "flagship-task-fact-verification",
      ],
      approvalPolicyId: null,
    },
    deliverable: {
      deliverableId: "flagship-deliverable-interview-record",
      label: "采访记录R1/R2与信源边界",
      objectKind: "production_artifact",
      templateId: "interview-record",
      required: true,
    },
    evidence: {
      evidenceRequirementId: "flagship-evidence-interview-verification",
      competencyId: "C-INTERVIEW-02",
      behavior: "学生对不能确认的数字继续追问来源并保留拒绝，不把NPC陈述升级为权威事实。",
      evidenceKind: "问题序列、拒绝、承诺和声明—来源链接",
      sourceRefs: [
        "reporter-followup-visitors",
        "flagship-contribution-interview-structure",
        "flagship-deliverable-interview-record",
      ],
      successCriterion: "记录同时包含可确认内容、不可确认内容和下一核验责任人。",
    },
  }),
  nodeExperience({
    nodeId: "verification",
    task: {
      taskId: "flagship-task-fact-verification",
      label: "完成客流事实二次核验",
      description: "对照初版快报、去重表和采访边界，保留18,000与12,600两版并请求教师确认。",
      roleIds: ["responsible_editor", "reporter"],
      expectedOutput: "更正前后对照、来源链和二次核验请求",
      completionSignal: "事实更正候选经教师门后写入世界",
    },
    opportunity: {
      opportunityId: "flagship-opportunity-verification-desk",
      sceneId: "scene-verification-desk",
      hotspotId: "hotspot-verification-board",
      label: "比对客流版本并选择是否请求更正",
      choiceRefs: ["flagship-task-fact-verification"],
      studentVisibleConsequence: "选择保留版本差异并补证时，权威事实可经教师批准更新；直接覆盖会失去证据链。",
    },
    gap: {
      gapId: "flagship-gap-chief-verification",
      npcActorId: "agent-chief",
      knownInformation: "总编知道只有可回指来源的当前版本才能进入首发。",
      withheldInformation: "总编不会替学生判断去重表是否足以成为权威事实。",
      revealCondition: "学生提交更正前后差异、来源和二次核验请求。",
      resultingObjectKinds: ["世界事实候选", "教师门", "版本差异"],
    },
    contribution: {
      contributionId: "flagship-contribution-fact-checker",
      templateId: "template:agent-fact-checker",
      plane: "professional_governance",
      trigger: "固定材料观察进入世界且包含可核验数据口径时运行。",
      outputKind: "事实更正或补证 AgentIntent",
      authority: "candidate_requires_teacher",
    },
    dynamicEvent: {
      dynamicEventId: "flagship-event-visitor-correction",
      eventType: "world_fact_updated",
      triggerKind: "agent_candidate",
      triggerRef: "flagship-contribution-fact-checker",
      worldChanges: ["客流权威版本由18,000更正为12,600", "旧版保留为superseded", "跨渠道内容必须同步"],
      affectedTaskIds: [
        "flagship-task-fact-verification",
        "flagship-task-rain-collaboration",
      ],
      approvalPolicyId: "teacher-world-event-review",
    },
    deliverable: {
      deliverableId: "flagship-deliverable-verification-note",
      label: "客流更正与二次核验说明",
      objectKind: "production_artifact_revision",
      templateId: "article-main",
      required: true,
    },
    evidence: {
      evidenceRequirementId: "flagship-evidence-fact-version",
      competencyId: "C-FACT-01",
      behavior: "学生保留前后版本、解释旧口径失效原因并请求权威确认。",
      evidenceKind: "事实版本、材料引用、教师批准和跨稿同步",
      sourceRefs: [
        "flagship-task-fact-verification",
        "flagship-event-visitor-correction",
        "flagship-deliverable-verification-note",
      ],
      successCriterion: "所有关键表述只引用经批准的当前版本，同时能回放旧版及更正原因。",
    },
  }),
  nodeExperience({
    nodeId: "production",
    task: {
      taskId: "flagship-task-rain-collaboration",
      label: "暴雨突发下重排双岗任务与内容",
      description: "记者更新现场、路线和采访材料；责任编辑调整选题、时限、平台优先级及多渠道R2。",
      roleIds: ["responsible_editor", "reporter"],
      expectedOutput: "暴雨应变分工、现场更新和跨渠道R2",
      completionSignal: "突发事件后的任务、材料和成果版本均发生可追溯变化",
    },
    opportunity: {
      opportunityId: "flagship-opportunity-rain-response",
      sceneId: "scene-rain-transition",
      hotspotId: "hotspot-rain-command",
      label: "在停演、疏散与首发压力间重新分工",
      choiceRefs: ["flagship-task-rain-collaboration"],
      studentVisibleConsequence: "是否先核对疏散事实、是否调整渠道和是否冻结旧稿，会改变NPC反馈、平台风险与可交付版本。",
    },
    gap: {
      gapId: "flagship-gap-rain-interviewee",
      npcActorId: "agent-interviewee",
      knownInformation: "采访对象知道展演暂停和现场人员转移方向。",
      withheldInformation: "采访对象不知道主办方最终恢复时间，也不能确认全部游客已安全离场。",
      revealCondition: "记者以安全状态、时间版本和可确认范围重新提问。",
      resultingObjectKinds: ["突发线索", "时间约束", "现场材料", "任务重排"],
    },
    contribution: {
      contributionId: "flagship-contribution-scene-director-rain",
      templateId: "template:agent-scene-director",
      plane: "teaching_direction",
      trigger: "事实更正完成且团队进入生产节点后，从发布版白名单选择暴雨压力路线。",
      outputKind: "待教师批准的 ScenarioIntervention",
      authority: "candidate_requires_teacher",
    },
    dynamicEvent: {
      dynamicEventId: "flagship-event-rain-escalation",
      eventType: "scenario_intervention_applied",
      triggerKind: "agent_candidate",
      triggerRef: "flagship-contribution-scene-director-rain",
      worldChanges: ["场景转为暴雨应急状态", "剩余时间与采访窗口缩短", "记者和责任编辑任务优先级改变", "平台风险升级"],
      affectedTaskIds: [
        "flagship-task-rain-collaboration",
        "flagship-task-copyright-governance",
        "flagship-task-release-decision",
      ],
      approvalPolicyId: "teacher-world-event-review",
    },
    deliverable: {
      deliverableId: "flagship-deliverable-rain-r2",
      label: "暴雨应变短视频与渠道R2",
      objectKind: "production_artifact_revision",
      templateId: "short-video-plan",
      required: true,
    },
    evidence: {
      evidenceRequirementId: "flagship-evidence-collaboration-response",
      competencyId: "C-COLLAB-03",
      behavior: "双岗在突发后重新分工、更新来源和版本，并明确时效不能替代核验。",
      evidenceKind: "任务重排、岗位交接、R1/R2差异与事件后果",
      sourceRefs: [
        "flagship-task-rain-collaboration",
        "flagship-event-rain-escalation",
        "flagship-deliverable-rain-r2",
      ],
      successCriterion: "记者与责任编辑均有独立行为证据，且成果修订能回指暴雨造成的约束变化。",
    },
  }),
  nodeExperience({
    nodeId: "copyright",
    task: {
      taskId: "flagship-task-copyright-governance",
      label: "执行四域治理并处置争议素材",
      description: "核对事实、版权、内容安全和平台规则，选择补授权、替换、冻结或降级渠道。",
      roleIds: ["responsible_editor", "reporter"],
      expectedOutput: "四域Finding、争议素材处置和治理请求",
      completionSignal: "固定材料版本的治理分支完成并由教师逐项复核",
    },
    opportunity: {
      opportunityId: "flagship-opportunity-copyright-owner",
      sceneId: "scene-governance-desk",
      hotspotId: "hotspot-copyright-owner",
      label: "向版权方确认商业渠道授权边界",
      choiceRefs: [
        "editor-copyright-scope",
        "editor-copyright-decision",
      ],
      studentVisibleConsequence: "版权方拒绝当前商业使用后，现场图进入争议状态，旧渠道版本必须冻结或替换。",
    },
    gap: {
      gapId: "flagship-gap-copyright-scope",
      npcActorId: "agent-copyright",
      knownInformation: "版权方知道当前授权只覆盖课程内展示以及补充授权所需字段。",
      withheldInformation: "在学生未说明渠道、用途、期限和地域前，版权方不会给出最终结论。",
      revealCondition: "责任编辑提交结构化用途并请求明确授权或拒绝。",
      resultingObjectKinds: ["版权拒绝", "风险Finding", "冻结约束", "替换任务"],
    },
    contribution: {
      contributionId: "flagship-contribution-copyright-governance",
      templateId: "governance/copyright",
      plane: "professional_governance",
      trigger: "固定材料版本进入治理案件的版权分支。",
      outputKind: "版权范围 GovernanceFinding",
      authority: "deterministic",
    },
    dynamicEvent: {
      dynamicEventId: "flagship-event-copyright-dispute",
      eventType: "copyright_risk_flagged",
      triggerKind: "agent_candidate",
      triggerRef: "flagship-contribution-copyright-governance",
      worldChanges: ["现场图转为争议状态", "商业渠道版本被阻断", "补授权或替换成为正式任务"],
      affectedTaskIds: [
        "flagship-task-copyright-governance",
        "flagship-task-release-decision",
      ],
      approvalPolicyId: "teacher-world-event-review",
    },
    deliverable: {
      deliverableId: "flagship-deliverable-governance-record",
      label: "四域治理与争议素材处置记录",
      objectKind: "governance_case",
      templateId: "article-main",
      required: true,
    },
    evidence: {
      evidenceRequirementId: "flagship-evidence-governance",
      competencyId: "C-GOV-03",
      behavior: "学生根据精确授权范围冻结、替换或补证，而不是用首发时限绕过高风险门。",
      evidenceKind: "Finding、素材版本、处置动作与教师治理决定",
      sourceRefs: [
        "editor-copyright-decision",
        "flagship-event-copyright-dispute",
        "flagship-deliverable-governance-record",
      ],
      successCriterion: "四域结论均固定到同一材料版本，高风险争议在教师决定前不进入发布。",
    },
  }),
  nodeExperience({
    nodeId: "release",
    task: {
      taskId: "flagship-task-release-decision",
      label: "冻结精确版本并完成治理发布决定",
      description: "提交平台预检、人工复核回执和精确成果修订，说明发布、暂缓或替换的职业判断。",
      roleIds: ["responsible_editor", "reporter"],
      expectedOutput: "冻结版本、平台回执、发布决定和后果说明",
      completionSignal: "平台升级经教师批准且责任编辑形成正式发布动作",
    },
    opportunity: {
      opportunityId: "flagship-opportunity-platform-review",
      sceneId: "scene-platform-release",
      hotspotId: "hotspot-platform-operator",
      label: "请求平台预检与人工复核升级",
      choiceRefs: [
        "editor-platform-precheck",
        "editor-platform-escalation",
      ],
      studentVisibleConsequence: "平台运营的回执使待发版本进入人工复核；继续推送、暂停或替换会产生不同关系和后续风险。",
    },
    gap: {
      gapId: "flagship-gap-platform-review",
      npcActorId: "agent-platform",
      knownInformation: "平台运营知道预检材料、人工复核门槛和必须保留的回执。",
      withheldInformation: "平台不会在版本未冻结、事实和素材处置未留痕时承诺进入人工复核。",
      revealCondition: "责任编辑提交精确版本号、事实更正、素材处置和渠道信息。",
      resultingObjectKinds: ["平台回执", "人工复核候选", "发布约束", "后续事件"],
    },
    contribution: {
      contributionId: "flagship-contribution-platform-agent",
      templateId: "template:agent-platform",
      plane: "world_role",
      trigger: "责任编辑完成第二轮平台互动并提交冻结版本。",
      outputKind: "RoleResponseIntent 与平台升级候选",
      authority: "candidate_requires_teacher",
    },
    dynamicEvent: {
      dynamicEventId: "flagship-event-platform-escalation",
      eventType: "node_activated",
      triggerKind: "student_action",
      triggerRef: "editor-platform-escalation",
      worldChanges: ["待发版本进入人工复核", "平台关系状态改为等待回执", "继续推送被阻断", "发布倒计时继续"],
      affectedTaskIds: [
        "flagship-task-release-decision",
        "flagship-task-evaluation-review",
      ],
      approvalPolicyId: "teacher-world-event-review",
    },
    deliverable: {
      deliverableId: "flagship-deliverable-release-package",
      label: "治理发布包与渠道差异说明",
      objectKind: "production_submission",
      templateId: "channel-variant",
      required: true,
    },
    evidence: {
      evidenceRequirementId: "flagship-evidence-release-judgment",
      competencyId: "C-RELEASE-04",
      behavior: "学生把平台回执、治理结论和精确成果版本组合成可解释的发布或暂缓决定。",
      evidenceKind: "平台线程、发布动作、成果哈希与世界后果",
      sourceRefs: [
        "editor-platform-escalation",
        "flagship-event-platform-escalation",
        "flagship-deliverable-release-package",
      ],
      successCriterion: "发布决定可回指同一冻结版本和全部高风险门，不把已提交审核写成已通过。",
    },
  }),
  nodeExperience({
    nodeId: "review",
    task: {
      taskId: "flagship-task-evaluation-review",
      label: "完成固定评价、教师终评与迁移复盘",
      description: "沿同一时间线解释选题、采访、事实、暴雨、治理和发布的行为—证据—后果。",
      roleIds: ["responsible_editor", "reporter"],
      expectedOutput: "逐维复盘、教师终评理由和迁移训练计划",
      completionSignal: "固定评价案件经确定性仲裁和教师逐维终评",
    },
    opportunity: {
      opportunityId: "flagship-opportunity-evaluation-court",
      sceneId: "scene-evaluation-court",
      hotspotId: "hotspot-evaluation-timeline",
      label: "沿因果时间线解释职业判断",
      choiceRefs: ["flagship-task-evaluation-review"],
      studentVisibleConsequence: "学生能看到每项评价如何回到本人的行动、证据和世界后果，教师覆盖保留旧决定。",
    },
    gap: {
      gapId: "flagship-gap-chief-review",
      npcActorId: "agent-chief",
      knownInformation: "总编知道发布结果与职业门是否满足。",
      withheldInformation: "总编不会替学生完成反事实解释或个人贡献归因。",
      revealCondition: "学生用时间线证据说明若缺少关键动作会产生什么后果。",
      resultingObjectKinds: ["评价案件", "教师终评", "反事实说明", "迁移计划"],
    },
    contribution: {
      contributionId: "flagship-contribution-evaluation-review",
      templateId: "assistant/evaluation-review",
      plane: "teacher_assistance",
      trigger: "固定评价案件完成仲裁并出现逐维分歧时运行。",
      outputKind: "advisory_only 分歧摘要与复核顺序",
      authority: "advisory_only",
    },
    dynamicEvent: {
      dynamicEventId: "flagship-event-teacher-final",
      eventType: "teacher_reviewed",
      triggerKind: "teacher_decision",
      triggerRef: "review_assessment",
      worldChanges: ["教师逐维终评生效", "模型意见保持非最终", "能力画像与迁移任务开放"],
      affectedTaskIds: ["flagship-task-evaluation-review"],
      approvalPolicyId: null,
    },
    deliverable: {
      deliverableId: "flagship-deliverable-reflection",
      label: "证据复盘与迁移训练计划",
      objectKind: "evaluation_reflection",
      templateId: null,
      required: true,
    },
    evidence: {
      evidenceRequirementId: "flagship-evidence-reflection-transfer",
      competencyId: "C-REFLECT-01",
      behavior: "学生按时间线解释选择、智能体贡献、世界后果和本人修订，不使用无证据套话。",
      evidenceKind: "评价案件、教师覆盖、反事实回答与迁移计划",
      sourceRefs: [
        "flagship-task-evaluation-review",
        "flagship-event-teacher-final",
        "flagship-deliverable-reflection",
      ],
      successCriterion: "六个能力域均能定位个人行为证据，教师最终决定与模型建议明确分离。",
    },
  }),
];

const flagshipExperienceDesign: ScenarioExperienceDesign = {
  schemaVersion: ScenarioExperienceSchemaVersion,
  contentVersion: flagshipVersion,
  kind: "flagship",
  summary: "以七个连续课程节点把课程操作任务、NPC私有信息、世界后果、按需智能体贡献和固定能力证据接入同一旗舰黄金路径。",
  scenes: [
    {
      sceneId: "scene-newsroom-brief",
      title: "融媒体中心选题台",
      description: "学生确认选题、受众、信源、岗位分工与首发门禁。",
      visualMode: "fixed_2_5d",
      nodeIds: ["brief"],
    },
    {
      sceneId: "scene-heritage-market",
      title: "非遗市集采访区",
      description: "记者面对可回答流程但拒绝确认精确客流的采访对象。",
      visualMode: "fixed_2_5d",
      nodeIds: ["source"],
    },
    {
      sceneId: "scene-verification-desk",
      title: "事实核验台",
      description: "团队比对快报、采访和去重表，保留更正前后版本。",
      visualMode: "structured_cards",
      nodeIds: ["verification"],
    },
    {
      sceneId: "scene-rain-transition",
      title: "暴雨应急现场",
      description: "暴雨改变活动安排、采访窗口、岗位优先级和平台风险。",
      visualMode: "fixed_2_5d",
      nodeIds: ["production"],
    },
    {
      sceneId: "scene-governance-desk",
      title: "四域治理台",
      description: "固定材料版本进入事实、版权、内容安全和平台规则治理。",
      visualMode: "structured_cards",
      nodeIds: ["copyright"],
    },
    {
      sceneId: "scene-platform-release",
      title: "平台发布与人工复核台",
      description: "冻结版本、治理结论和平台回执共同决定发布后果。",
      visualMode: "fixed_2_5d",
      nodeIds: ["release"],
    },
    {
      sceneId: "scene-evaluation-court",
      title: "评价法庭与因果时间线",
      description: "固定证据案件、模型分歧、教师终评和迁移复盘汇聚。",
      visualMode: "structured_cards",
      nodeIds: ["review"],
    },
  ],
  npcInstances: [
    {
      actorId: "agent-chief",
      roleId: "editor_in_chief",
      displayName: "总编·沈砚",
      sceneIds: [
        "scene-newsroom-brief",
        "scene-platform-release",
        "scene-evaluation-court",
      ],
      privatePerspective: {
        knownInformation: ["首发时限", "事实与版权发布门", "终审责任"],
        withheldInformation: ["完整放行标准", "对学生职业判断的最终看法"],
        disclosureRules: ["学生必须先陈述风险与证据缺口", "终评前不替学生完成反事实解释"],
      },
    },
    {
      actorId: "agent-interviewee",
      roleId: "interviewee",
      displayName: "采访对象·叶师傅",
      sceneIds: ["scene-heritage-market", "scene-rain-transition"],
      privatePerspective: {
        knownInformation: ["非遗展演流程", "现场排队与停演变化"],
        withheldInformation: ["精确客流", "主办方最终恢复时间"],
        disclosureRules: ["只回答亲历范围", "明确拒绝未经活动方确认的统计结论"],
      },
    },
    {
      actorId: "agent-copyright",
      roleId: "copyright_owner",
      displayName: "版权方·苏禾影像",
      sceneIds: ["scene-governance-desk"],
      privatePerspective: {
        knownInformation: ["当前授权用途、渠道、期限和地域"],
        withheldInformation: ["学生未提交结构化用途前的最终授权决定"],
        disclosureRules: ["超出课程内展示范围时拒绝默认授权", "允许补充授权或替换素材"],
      },
    },
    {
      actorId: "agent-platform",
      roleId: "platform_operator",
      displayName: "平台运营·乔安",
      sceneIds: ["scene-rain-transition", "scene-platform-release"],
      privatePerspective: {
        knownInformation: ["平台预检规则", "人工复核所需记录"],
        withheldInformation: ["材料不完整时的升级承诺", "人工审核最终结果"],
        disclosureRules: ["冻结版本和治理记录齐全后才承诺升级", "不得把提交审核表述为审核通过"],
      },
    },
  ],
  hotspots: [
    {
      hotspotId: "hotspot-chief-brief",
      sceneId: "scene-newsroom-brief",
      label: "总编终审席",
      description: "确认选题边界、风险优先级和发布门。",
      targetActorId: "agent-chief",
      visibleToRoleIds: ["responsible_editor", "reporter"],
      interactionOptionIds: ["editor-chief-gate", "editor-chief-commit"],
    },
    {
      hotspotId: "hotspot-interviewee",
      sceneId: "scene-heritage-market",
      label: "传承人采访点",
      description: "完成流程采访与客流边界追问。",
      targetActorId: "agent-interviewee",
      visibleToRoleIds: ["reporter", "responsible_editor"],
      interactionOptionIds: [
        "reporter-interview-process",
        "reporter-followup-visitors",
      ],
    },
    {
      hotspotId: "hotspot-verification-board",
      sceneId: "scene-verification-desk",
      label: "客流版本对照板",
      description: "对照18,000与12,600两版来源及状态。",
      targetActorId: null,
      visibleToRoleIds: ["responsible_editor", "reporter"],
      interactionOptionIds: [],
    },
    {
      hotspotId: "hotspot-rain-command",
      sceneId: "scene-rain-transition",
      label: "暴雨应变指挥点",
      description: "查看停演、疏散、时限与平台风险并重新分工。",
      targetActorId: null,
      visibleToRoleIds: ["responsible_editor", "reporter"],
      interactionOptionIds: [],
    },
    {
      hotspotId: "hotspot-copyright-owner",
      sceneId: "scene-governance-desk",
      label: "版权方沟通席",
      description: "提交结构化用途并取得明确授权边界。",
      targetActorId: "agent-copyright",
      visibleToRoleIds: ["responsible_editor"],
      interactionOptionIds: [
        "editor-copyright-scope",
        "editor-copyright-decision",
      ],
    },
    {
      hotspotId: "hotspot-platform-operator",
      sceneId: "scene-platform-release",
      label: "平台人工复核入口",
      description: "提交冻结版本、治理记录与渠道信息。",
      targetActorId: "agent-platform",
      visibleToRoleIds: ["responsible_editor", "reporter"],
      interactionOptionIds: [
        "editor-platform-precheck",
        "editor-platform-escalation",
      ],
    },
    {
      hotspotId: "hotspot-evaluation-timeline",
      sceneId: "scene-evaluation-court",
      label: "因果证据时间线",
      description: "逐项回看学生选择、智能体贡献、世界后果和教师终评。",
      targetActorId: null,
      visibleToRoleIds: ["responsible_editor", "reporter"],
      interactionOptionIds: [],
    },
  ],
  nodeMappings: flagshipNodeMappings,
  causalBranches: flagshipNodeMappings.map((mapping) => ({
    branchId: `flagship-branch-${mapping.nodeId}`,
    nodeId: mapping.nodeId,
    label: `${mapping.nodeId}节点主因果分支`,
    studentChoiceRef: mapping.worldOpportunities[0]!.choiceRefs[0]!,
    agentContributionRef: mapping.agentContributions[0]!.contributionId,
    worldConsequenceRef: mapping.dynamicEvents[0]!.dynamicEventId,
    capabilityEvidenceRef:
      mapping.capabilityEvidence[0]!.evidenceRequirementId,
  })),
  fixedEvaluation: {
    evaluationId: "flagship-fixed-evaluation-v110",
    rubricId: demoScenario.rubricId,
    rubricVersion: demoScenario.rubricVersion,
    evidenceRequirementIds: flagshipNodeMappings.map(
      (mapping) => mapping.capabilityEvidence[0]!.evidenceRequirementId,
    ),
    teacherFinalRequired: true,
  },
};

export const flagshipScenarioV110: ScenarioPackage = ScenarioPackageSchema.parse({
  ...structuredClone(demoScenario),
  version: flagshipVersion,
  roles: structuredClone(demoScenario.roles),
  description: "记者与责任编辑沿选题调研、NPC采访、事实核验、暴雨应变、双岗生产、四域治理发布和评价复盘七节点，完成同一权威世界中的双维度黄金路径。",
  materials: [
    ...structuredClone(demoScenario.materials),
    {
      materialId: "material-rain-alert",
      title: "气象预警与活动停演通知",
      mediaType: "document",
      source: "属地应急与活动主办方",
      sourceRef: "demo://materials/rain-alert-v1",
      version: "1.0",
      copyrightStatus: "authorized",
      visibleToRoles: [
        "teacher",
        "responsible_editor",
        "reporter",
        "interviewee",
        "platform_operator",
      ],
    },
  ],
  courseGuide: {
    ...structuredClone(demoScenario.courseGuide!),
    contentVersion: flagshipVersion,
  },
  experienceDesign: flagshipExperienceDesign,
  knowledgeChunks: [
    ...structuredClone(demoScenario.knowledgeChunks),
    {
      chunkId: "scenario-rain-response-v110",
      domain: "scenario",
      title: "暴雨突发下的双岗应变",
      content: "暴雨改变现场安排、采访窗口、任务优先级和平台风险时，记者先更新可确认现场事实，责任编辑再同步调整选题、渠道和冻结版本；时效不能替代核验与治理门。",
      courseId: demoScenario.courseId,
      nodeId: "production",
      roleId: null,
      competencyId: "C-COLLAB-03",
      ruleDomain: "emergency-response",
      mediaType: "text",
      source: "情境包/地方文旅融媒1.1",
      version: flagshipVersion,
      visibility: "assigned_team",
      contentHash: hashContent("暴雨改变现场安排、采访窗口、任务优先级和平台风险时，记者先更新可确认现场事实，责任编辑再同步调整选题、渠道和冻结版本；时效不能替代核验与治理门。"),
      corpusVersion: "tourism-media-corpus/1.1.0",
      status: "active",
      audience: createResourceAudience({
        scopes: ["assigned_team"],
        courseId: demoScenario.courseId,
        teamIds: [teamId],
        auditReadable: true,
      }),
    },
  ],
});

export const flagshipScenarioV110ContentHash =
  "100aa9b8fdba95cf88589629e2bf9d1b8a2dce84bcbe7a500234a5defae72e76";

const flagshipV111DirectorEventTemplates: ScenarioDirectorEventTemplate[] = [
  ...structuredClone(flagshipScenarioV110.directorEventTemplates ?? []),
  {
    routeId: "route-rain-escalation",
    kind: "challenge",
    title: "暴雨突发下的双岗应变",
    studentBrief: "气象预警升级，现场展演暂停并开始疏散。记者需重新确认现场状态与采访窗口，责任编辑需同步调整时限、渠道优先级和多渠道版本；未经确认的信息不得因抢时效进入发布稿。",
    competencyTarget: "C-COLLAB-03 突发情境下的双岗协作",
    expectedImpact: "场景转为暴雨应急状态，缩短采访与发布窗口，重排记者和责任编辑任务，并提升平台风险。",
    affectedRoleIds: ["responsible_editor", "reporter"],
    applicableNodeIds: ["production"],
    triggerEventTypes: ["node_activated"],
    teachingStrategies: ["challenge", "teacher_gate"],
    difficultyLevels: ["supportive", "standard", "challenging"],
    minimumEvidenceCount: 2,
    maximumEvidenceCount: null,
    riskLevel: "high",
    cooldownKey: "rain-escalation-pressure",
    cooldownEvents: 18,
    alternativeRouteIds: ["route-recovery-rain-brief"],
    sourceRefs: ["material-rain-alert", "scenario-rain-response-v110"],
    priority: 160,
    effectHandlerId: "director_intervention_v1",
    eventType: "scenario_intervention_applied",
    approvalPolicyId: "teacher-world-event-review",
  },
  {
    routeId: "route-recovery-rain-brief",
    kind: "recovery",
    title: "改为暴雨应变核对表",
    studentBrief: "教师未采用上一条暴雨压力事件。请保持当前世界事实不变，仅核对现场安全状态、信息确认时间、双岗分工、渠道调整和冻结版本，不直接进入公开发布。",
    competencyTarget: "C-COLLAB-03 突发应变核对",
    expectedImpact: "以低风险核对表恢复生产路线，保留双岗协作和证据门，不直接改变公开世界。",
    affectedRoleIds: ["responsible_editor", "reporter"],
    applicableNodeIds: ["production"],
    triggerEventTypes: ["director_recovery_requested"],
    teachingStrategies: [
      "no_intervention",
      "observe_more",
      "procedural_hint",
      "socratic_prompt",
      "scaffold",
      "challenge",
      "teacher_gate",
    ],
    difficultyLevels: ["supportive", "standard", "challenging"],
    minimumEvidenceCount: 0,
    maximumEvidenceCount: null,
    riskLevel: "low",
    cooldownKey: "rain-recovery",
    cooldownEvents: 8,
    alternativeRouteIds: [],
    sourceRefs: ["material-rain-alert", "scenario-rain-response-v110"],
    priority: 180,
    effectHandlerId: "director_intervention_v1",
    eventType: "scenario_intervention_applied",
    approvalPolicyId: "teacher-world-event-review",
  },
];

export const flagshipScenarioV111: ScenarioPackage = ScenarioPackageSchema.parse({
  ...structuredClone(flagshipScenarioV110),
  version: flagshipPatchVersion,
  description: "在1.1.0七节点黄金路径上补齐失效候选闭环兼容与暴雨专用导演路线，确保双岗位突发应变可由同一权威世界触发、审批和回放。",
  directorConfig: {
    ...structuredClone(flagshipScenarioV110.directorConfig!),
    allowedRouteIds: flagshipV111DirectorEventTemplates.map(
      (template) => template.routeId,
    ),
  },
  directorEventTemplates: flagshipV111DirectorEventTemplates,
  courseGuide: {
    ...structuredClone(flagshipScenarioV110.courseGuide!),
    contentVersion: flagshipPatchVersion,
  },
  experienceDesign: {
    ...structuredClone(flagshipScenarioV110.experienceDesign!),
    contentVersion: flagshipPatchVersion,
    fixedEvaluation: {
      ...structuredClone(flagshipScenarioV110.experienceDesign!.fixedEvaluation),
      evaluationId: "flagship-fixed-evaluation-v111",
    },
  },
});

export const flagshipScenarioV111ContentHash =
  "db3561089fabef485cff10a55730759e0d8b1702ba66e000b5b33f70a165e690";

function transferRole(
  actorId: string,
  patch: Partial<Pick<RoleContract, "displayName" | "purpose">> = {},
): RoleContract {
  const role = demoScenario.roles.find((candidate) => (
    candidate.agentId === actorId
  ));
  if (!role) throw new Error(`迁移情境缺少基线角色：${actorId}`);
  return {
    ...structuredClone(role),
    ...patch,
  };
}

const transferRoles: RoleContract[] = [
  transferRole("teacher-main"),
  transferRole("student-editor", {
    displayName: "责任编辑·林晓舟",
    purpose: "统筹古镇暴雨闭园通报、治理门与平台发布决定",
  }),
  transferRole("student-reporter", {
    displayName: "现场记者·陈野",
    purpose: "采访景区值班员并核定疏散、安置与未确认信息",
  }),
  transferRole("agent-interviewee", {
    displayName: "景区值班员·顾岚",
    purpose: "说明闭园、疏散和临时安置的亲历范围，不猜测伤情与恢复时间",
  }),
  transferRole("agent-platform", {
    displayName: "平台值守·乔安",
    purpose: "说明应急通报格式、人工复核与回执边界",
  }),
  transferRole("system"),
];

const transferNodes: ScenarioNode[] = [
  {
    nodeId: "brief",
    title: "核定闭园通报任务",
    objective: "明确受众、信源、双岗分工和高风险发布门",
    order: 0,
    status: "active",
    requiredEvidenceKinds: ["任务确认", "风险假设"],
    completionEvent: "role_interaction_requested",
  },
  {
    nodeId: "source",
    title: "采访疏散与安置",
    objective: "区分值班员亲历事实、待核伤情和平台所需材料",
    order: 1,
    status: "available",
    requiredEvidenceKinds: ["采访记录", "信息边界"],
    completionEvent: "role_interaction_responded",
  },
  {
    nodeId: "release",
    title: "治理发布与评价",
    objective: "经教师门形成精确通报版本、平台回执和固定评价",
    order: 2,
    status: "locked",
    requiredEvidenceKinds: ["治理决定", "教师终评"],
    completionEvent: "teacher_reviewed",
  },
];

const transferNodeMappings: ScenarioNodeExperienceMapping[] = [
  nodeExperience({
    nodeId: "brief",
    task: {
      taskId: "transfer-task-risk-plan",
      label: "提交暴雨闭园通报计划",
      description: "两岗确认服务对象、疏散信源、未确认伤情、发布时限和教师门。",
      roleIds: ["responsible_editor", "reporter"],
      expectedOutput: "闭园通报任务卡、岗位分工和风险假设",
      completionSignal: "任务卡形成首个固定版本",
    },
    opportunity: {
      opportunityId: "transfer-opportunity-brief-board",
      sceneId: "transfer-scene-command",
      hotspotId: "transfer-hotspot-brief-board",
      label: "选择先核定安全事实还是先写通报",
      choiceRefs: ["transfer-task-risk-plan"],
      studentVisibleConsequence: "先核定安全事实会开放值班员采访；直接写稿会保留伤情与恢复时间风险。",
    },
    gap: {
      gapId: "transfer-gap-platform-format",
      npcActorId: "agent-platform",
      knownInformation: "平台值守知道应急通报所需的时间、地点、路线和来源字段。",
      withheldInformation: "在学生未冻结版本前，不会承诺人工复核或给出最终平台状态。",
      revealCondition: "责任编辑先提交包含风险与来源的通报计划。",
      resultingObjectKinds: ["平台字段约束", "待办", "风险假设"],
    },
    contribution: {
      contributionId: "transfer-contribution-course-navigation",
      templateId: "assistant/course-navigation",
      plane: "student_assistance",
      trigger: "进入三节点迁移情境时解释当前任务与不可越过的教师门。",
      outputKind: "advisory_only 当前节点入口",
      authority: "advisory_only",
    },
    dynamicEvent: {
      dynamicEventId: "transfer-event-rain-warning",
      eventType: "node_activated",
      triggerKind: "student_action",
      triggerRef: "transfer-task-risk-plan",
      worldChanges: ["学生先核定安全事实", "景区闭园突发事件进入当前会话", "值班员采访任务开放"],
      affectedTaskIds: ["transfer-task-risk-plan"],
      approvalPolicyId: "teacher-transfer-event-review",
    },
    deliverable: {
      deliverableId: "transfer-deliverable-risk-plan",
      label: "闭园通报计划",
      objectKind: "course_task_revision",
      templateId: null,
      required: true,
    },
    evidence: {
      evidenceRequirementId: "transfer-evidence-risk-plan",
      competencyId: "C-TOPIC-TRANSFER",
      behavior: "学生先识别未确认伤情、恢复时间和路线版本，再形成通报计划。",
      evidenceKind: "任务版本、风险假设与岗位分工",
      sourceRefs: [
        "transfer-task-risk-plan",
        "transfer-event-rain-warning",
        "transfer-deliverable-risk-plan",
      ],
      successCriterion: "计划明确两个岗位、两个NPC和必须经过教师门的高风险信息。",
    },
  }),
  nodeExperience({
    nodeId: "source",
    task: {
      taskId: "transfer-task-shelter-interview",
      label: "采访景区值班员并结构化纪要",
      description: "记者核定闭园时间、疏散路线和临时安置点，明确伤情与恢复时间仍待官方确认。",
      roleIds: ["reporter", "responsible_editor"],
      expectedOutput: "采访纪要、待核声明和交接清单",
      completionSignal: "NPC私有线程形成响应并进入采访结构化任务",
    },
    opportunity: {
      opportunityId: "transfer-opportunity-duty-officer",
      sceneId: "transfer-scene-shelter",
      hotspotId: "transfer-hotspot-duty-officer",
      label: "追问闭园、疏散与不可确认信息",
      choiceRefs: ["transfer-reporter-shelter-interview"],
      studentVisibleConsequence: "值班员只确认亲历的闭园与路线，伤情和恢复时间保持待核并进入责任编辑待办。",
    },
    gap: {
      gapId: "transfer-gap-duty-officer",
      npcActorId: "agent-interviewee",
      knownInformation: "值班员亲历北门关闭、游客转移和临时安置点开放。",
      withheldInformation: "值班员不知道伤情统计和景区最终恢复时间。",
      revealCondition: "记者分别询问亲历事实、不能确认的内容和下一权威来源。",
      resultingObjectKinds: ["采访线索", "拒绝边界", "待核声明", "岗位交接"],
    },
    contribution: {
      contributionId: "transfer-contribution-interview-structure",
      templateId: "assistant/interview-structuring",
      plane: "material_production",
      trigger: "采访转写或纪要材料形成固定版本后按请求岗位实例化。",
      outputKind: "采访纪要草稿、待确认声明与追问清单",
      authority: "advisory_only",
    },
    dynamicEvent: {
      dynamicEventId: "transfer-event-interview-boundary",
      eventType: "role_interaction_responded",
      triggerKind: "student_action",
      triggerRef: "transfer-reporter-shelter-interview",
      worldChanges: ["闭园与疏散事实进入工作流", "伤情保持未确认", "平台通报任务获得结构化输入"],
      affectedTaskIds: [
        "transfer-task-shelter-interview",
        "transfer-task-governed-release",
      ],
      approvalPolicyId: null,
    },
    deliverable: {
      deliverableId: "transfer-deliverable-interview-note",
      label: "疏散采访纪要",
      objectKind: "interview_note",
      templateId: null,
      required: true,
    },
    evidence: {
      evidenceRequirementId: "transfer-evidence-interview-boundary",
      competencyId: "C-INTERVIEW-TRANSFER",
      behavior: "学生保留NPC拒绝和信息边界，把待核声明交给责任编辑而不补造。",
      evidenceKind: "采访线程、结构化纪要和待核声明",
      sourceRefs: [
        "transfer-reporter-shelter-interview",
        "transfer-contribution-interview-structure",
        "transfer-deliverable-interview-note",
      ],
      successCriterion: "纪要清楚区分亲历事实、待核信息和下一权威来源。",
    },
  }),
  nodeExperience({
    nodeId: "release",
    task: {
      taskId: "transfer-task-governed-release",
      label: "提交精确通报并请求平台人工复核",
      description: "责任编辑冻结通报版本、标注未确认伤情并提交平台；教师决定是否允许世界后果生效。",
      roleIds: ["responsible_editor", "reporter"],
      expectedOutput: "闭园通报、平台回执、治理决定和固定评价",
      completionSignal: "平台升级候选经教师门且固定Rubric进入教师终评",
    },
    opportunity: {
      opportunityId: "transfer-opportunity-platform-gate",
      sceneId: "transfer-scene-release",
      hotspotId: "transfer-hotspot-platform",
      label: "提交通报并请求平台加急复核",
      choiceRefs: ["editor-platform-escalation"],
      studentVisibleConsequence: "平台候选只有在教师批准后才进入人工复核；未确认伤情继续被阻断。",
    },
    gap: {
      gapId: "transfer-gap-platform-review",
      npcActorId: "agent-platform",
      knownInformation: "平台值守知道应急通报人工复核的字段、版本和回执要求。",
      withheldInformation: "在教师批准和版本冻结前，不会宣称审核通过。",
      revealCondition: "责任编辑提交固定版本、采访边界和未确认信息标记。",
      resultingObjectKinds: ["平台回执", "待审世界事件", "发布约束", "评价证据"],
    },
    contribution: {
      contributionId: "transfer-contribution-platform-agent",
      templateId: "template:agent-platform",
      plane: "world_role",
      trigger: "责任编辑选择平台加急复核并提交精确通报版本。",
      outputKind: "RoleResponseIntent 与平台升级候选",
      authority: "candidate_requires_teacher",
    },
    dynamicEvent: {
      dynamicEventId: "transfer-event-platform-escalation",
      eventType: "node_activated",
      triggerKind: "student_action",
      triggerRef: "editor-platform-escalation",
      worldChanges: ["暴雨通报进入人工复核", "未确认伤情保持阻断", "平台回执进入同一评价案件"],
      affectedTaskIds: ["transfer-task-governed-release"],
      approvalPolicyId: "teacher-transfer-event-review",
    },
    deliverable: {
      deliverableId: "transfer-deliverable-release-case",
      label: "暴雨闭园通报与教师终评案件",
      objectKind: "fixed_evaluation_case",
      templateId: null,
      required: true,
    },
    evidence: {
      evidenceRequirementId: "transfer-evidence-governed-release",
      competencyId: "C-GOV-TRANSFER",
      behavior: "学生只发布可确认事实，保留平台回执和教师决定，并解释为何未确认伤情不能写入。",
      evidenceKind: "精确版本、候选、教师门、平台后果与终评",
      sourceRefs: [
        "editor-platform-escalation",
        "transfer-event-platform-escalation",
        "transfer-deliverable-release-case",
      ],
      successCriterion: "固定评价能回到采访边界、学生发布选择、世界后果和教师最终决定。",
    },
  }),
];

const transferExperienceDesign: ScenarioExperienceDesign = {
  schemaVersion: ScenarioExperienceSchemaVersion,
  contentVersion: transferVersion,
  kind: "micro_transfer",
  summary: "以同一专业领域的古镇暴雨闭园通报验证两个学生岗位、两个私有NPC、三节点、学生触发事件、教师门和固定评价均可由配置建立。",
  scenes: [
    {
      sceneId: "transfer-scene-command",
      title: "古镇应急融媒指挥台",
      description: "学生接收暴雨闭园任务并明确双岗分工、受众和风险门。",
      visualMode: "structured_cards",
      nodeIds: ["brief"],
    },
    {
      sceneId: "transfer-scene-shelter",
      title: "临时安置点采访区",
      description: "记者采访景区值班员，区分亲历事实与待核伤情。",
      visualMode: "fixed_2d",
      nodeIds: ["source"],
    },
    {
      sceneId: "transfer-scene-release",
      title: "应急通报发布台",
      description: "责任编辑提交冻结版本、平台回执并进入教师终评。",
      visualMode: "structured_cards",
      nodeIds: ["release"],
    },
  ],
  npcInstances: [
    {
      actorId: "agent-interviewee",
      roleId: "interviewee",
      displayName: "景区值班员·顾岚",
      sceneIds: ["transfer-scene-shelter"],
      privatePerspective: {
        knownInformation: ["北门关闭时间", "游客转移路线", "临时安置点状态"],
        withheldInformation: ["伤情统计", "最终恢复时间"],
        disclosureRules: ["只回答亲历范围", "无法确认时给出下一权威来源"],
      },
    },
    {
      actorId: "agent-platform",
      roleId: "platform_operator",
      displayName: "平台值守·乔安",
      sceneIds: ["transfer-scene-command", "transfer-scene-release"],
      privatePerspective: {
        knownInformation: ["应急通报字段", "人工复核门", "回执要求"],
        withheldInformation: ["材料不完整时的升级承诺", "最终审核结果"],
        disclosureRules: ["固定版本与来源齐全后才提出升级候选", "审核提交与审核通过严格分离"],
      },
    },
  ],
  hotspots: [
    {
      hotspotId: "transfer-hotspot-brief-board",
      sceneId: "transfer-scene-command",
      label: "闭园任务板",
      description: "确认岗位、受众、来源和高风险信息。",
      targetActorId: null,
      visibleToRoleIds: ["responsible_editor", "reporter"],
      interactionOptionIds: [],
    },
    {
      hotspotId: "transfer-hotspot-duty-officer",
      sceneId: "transfer-scene-shelter",
      label: "景区值班员",
      description: "采访闭园、疏散与信息边界。",
      targetActorId: "agent-interviewee",
      visibleToRoleIds: ["responsible_editor", "reporter"],
      interactionOptionIds: ["transfer-reporter-shelter-interview"],
    },
    {
      hotspotId: "transfer-hotspot-platform",
      sceneId: "transfer-scene-release",
      label: "平台加急复核入口",
      description: "提交冻结版本与采访边界，请求人工复核。",
      targetActorId: "agent-platform",
      visibleToRoleIds: ["responsible_editor", "reporter"],
      interactionOptionIds: ["editor-platform-escalation"],
    },
  ],
  nodeMappings: transferNodeMappings,
  causalBranches: transferNodeMappings.map((mapping) => ({
    branchId: `transfer-branch-${mapping.nodeId}`,
    nodeId: mapping.nodeId,
    label: `${mapping.nodeId}节点主因果分支`,
    studentChoiceRef: mapping.worldOpportunities[0]!.choiceRefs[0]!,
    agentContributionRef: mapping.agentContributions[0]!.contributionId,
    worldConsequenceRef: mapping.dynamicEvents[0]!.dynamicEventId,
    capabilityEvidenceRef:
      mapping.capabilityEvidence[0]!.evidenceRequirementId,
  })),
  fixedEvaluation: {
    evaluationId: "transfer-rain-closure-fixed-evaluation",
    rubricId: "rubric-rain-closure-transfer",
    rubricVersion: transferVersion,
    evidenceRequirementIds: transferNodeMappings.map(
      (mapping) => mapping.capabilityEvidence[0]!.evidenceRequirementId,
    ),
    teacherFinalRequired: true,
  },
};

const transferCourseAudience = createResourceAudience({
  scopes: ["assigned_team"],
  courseId: transferCourseId,
  teamIds: [teamId],
  auditReadable: true,
});

export const transferScenarioV100: ScenarioPackage = ScenarioPackageSchema.parse({
  schemaVersion: demoScenario.schemaVersion,
  runtimeProfileId: demoScenario.runtimeProfileId,
  scenarioId: transferScenarioId,
  courseId: transferCourseId,
  version: transferVersion,
  title: "古镇暴雨闭园应急融媒通报",
  description: "两个学生岗位在三个连续节点中采访两个私有NPC，处理暴雨闭园信息边界，经平台候选与教师门形成固定评价。",
  startVirtualTime: "16:10",
  durationMinutes: 18,
  nodes: transferNodes,
  roles: transferRoles,
  materials: [
    {
      materialId: "transfer-material-rain-warning",
      title: "古镇橙色暴雨预警",
      mediaType: "document",
      source: "属地气象与应急部门",
      sourceRef: "demo://transfer/rain-warning-v1",
      version: "1.0",
      copyrightStatus: "authorized",
      visibleToRoles: [
        "teacher",
        "responsible_editor",
        "reporter",
        "interviewee",
        "platform_operator",
      ],
    },
    {
      materialId: "transfer-material-shelter-map",
      title: "闭园疏散与临时安置图",
      mediaType: "image",
      source: "古镇景区值班台",
      sourceRef: "demo://transfer/shelter-map-v1",
      version: "1.0",
      copyrightStatus: "authorized",
      visibleToRoles: [
        "teacher",
        "responsible_editor",
        "reporter",
        "interviewee",
      ],
    },
    {
      materialId: "transfer-material-platform-checklist",
      title: "应急通报人工复核清单",
      mediaType: "document",
      source: "平台值守台",
      sourceRef: "demo://transfer/platform-checklist-v1",
      version: "1.0",
      copyrightStatus: "authorized",
      visibleToRoles: [
        "teacher",
        "responsible_editor",
        "reporter",
        "platform_operator",
      ],
    },
  ],
  bootstrap: {
    entryNodeId: "brief",
    initialFacts: [
      {
        factId: "transfer-fact-rain-warning",
        domain: "emergency",
        statement: "属地已发布橙色暴雨预警，古镇景区已启动闭园预案，正式闭园通报仍待值班核定。",
        status: "verified",
        sourceRefs: ["transfer-material-rain-warning"],
        version: "1.0",
        visibility: "assigned_team",
      },
      {
        factId: "transfer-fact-injury-unknown",
        domain: "safety",
        statement: "当前尚无经权威来源确认的伤情统计和恢复开放时间。",
        status: "unverified",
        sourceRefs: ["transfer-material-rain-warning"],
        version: "1.0",
        visibility: "assigned_team",
      },
    ],
    openingMessages: [
      {
        actorId: "agent-interviewee",
        roleId: "interviewee",
        displayName: "景区值班员·顾岚",
        content: "我能说明北门关闭、游客转移和临时安置点情况；伤情与恢复时间请向应急部门核定。",
        visibility: ["role_private", "audit_only"],
        visibleToActorIds: ["student-reporter"],
      },
      {
        actorId: "agent-platform",
        roleId: "platform_operator",
        displayName: "平台值守·乔安",
        content: "应急通报必须固定时间、地点、路线、来源和未确认项，版本冻结后才能申请人工复核。",
        visibility: ["role_private", "audit_only"],
        visibleToActorIds: ["student-editor"],
      },
    ],
    memorySeeds: [
      {
        actorId: "agent-interviewee",
        kind: "episodic",
        content: "16:08北门开始关闭，游客被引导至游客中心和东侧停车区；未收到权威伤情统计。",
      },
      {
        actorId: "agent-platform",
        kind: "working",
        content: "人工复核要求精确版本号、权威预警来源、疏散路线和未确认信息标记。",
      },
    ],
  },
  roleInteractions: [
    {
      optionId: "transfer-reporter-shelter-interview",
      initiatorActorId: "student-reporter",
      targetActorId: "agent-interviewee",
      targetRoleId: "interviewee",
      kind: "question",
      topic: "visitor_count",
      label: "采访闭园与疏散边界",
      description: "请值班员说明亲历的闭园、路线、安置情况以及不能确认的信息。",
      content: "请分别说明你亲历的闭园时间、游客转移路线、临时安置状态，以及目前不能确认的伤情和恢复时间。",
      prerequisites: [],
    },
    {
      optionId: "editor-platform-escalation",
      initiatorActorId: "student-editor",
      targetActorId: "agent-platform",
      targetRoleId: "platform_operator",
      kind: "request_commitment",
      topic: "platform_review",
      label: "请求应急通报人工复核",
      description: "提交冻结版本、权威预警和采访边界，请平台说明人工复核与回执。",
      content: "当前闭园通报已固定版本，并标注伤情与恢复时间未确认。请确认是否进入人工复核以及必须保留的回执。",
      prerequisites: [{
        kind: "interaction_responded",
        optionId: "transfer-reporter-shelter-interview",
        disabledReason: "先完成景区值班员采访与信息边界交接",
      }],
    },
  ],
  rubricId: "rubric-rain-closure-transfer",
  rubricVersion: transferVersion,
  rubric: [
    {
      criterionId: "transfer-source-boundary",
      label: "采访与信息边界",
      weight: 0.4,
      rule: "保留值班员亲历范围和未确认伤情，不补造恢复时间。",
      evaluation: {
        kind: "event_exists",
        eventType: "role_interaction_responded",
      },
    },
    {
      criterionId: "transfer-teacher-gate",
      label: "治理与教师门",
      weight: 0.35,
      rule: "平台候选必须经教师批准后才改变发布世界状态。",
      evaluation: {
        kind: "event_exists",
        eventType: "candidate_event_approved",
      },
    },
    {
      criterionId: "transfer-world-consequence",
      label: "发布后果",
      weight: 0.25,
      rule: "精确通报版本进入人工复核并保留回执。",
      evaluation: {
        kind: "event_exists",
        eventType: "node_activated",
      },
    },
  ],
  interactionGates: [],
  eventPolicies: [
    {
      policyId: "transfer-platform-escalation",
      sourceIntentType: "propose_platform_escalation",
      sourceRoleId: "platform_operator",
      requiredOptionId: "editor-platform-escalation",
      effectHandlerId: "platform_escalation_v1",
      eventType: "node_activated",
      title: "暴雨闭园通报转人工复核",
      competencyTarget: "应急信息治理与发布判断",
      expectedImpact: "经教师批准后进入发布节点，并保留未确认伤情阻断与平台回执。",
      approvalPolicyId: "teacher-transfer-event-review",
    },
  ],
  approvalPolicies: [
    {
      approvalPolicyId: "teacher-transfer-event-review",
      label: "应急通报世界后果教师复核",
      reviewMode: "teacher_required",
      allowReject: true,
      reasonRequired: true,
      minimumEvidenceCount: 0,
    },
  ],
  courseGuide: {
    contentVersion: transferVersion,
    finalDeliverable: "形成一份固定版本的古镇暴雨闭园应急通报，附值班员采访纪要、未确认信息标记、平台人工复核回执和教师逐维终评。",
    learningObjectives: [
      {
        objectiveId: "transfer-objective-boundary",
        label: "核定应急信息边界",
        competencyId: "C-INTERVIEW-TRANSFER",
        description: "区分NPC亲历事实、权威预警和未确认伤情，不用时效压力替代核验。",
        evidenceKinds: ["采访线程", "待核声明", "来源引用"],
      },
      {
        objectiveId: "transfer-objective-governance",
        label: "完成治理发布决定",
        competencyId: "C-GOV-TRANSFER",
        description: "冻结精确版本，经平台候选和教师门形成可解释发布后果。",
        evidenceKinds: ["精确版本", "教师决定", "平台回执"],
      },
    ],
    roleBriefs: [
      {
        roleId: "responsible_editor",
        mission: "统筹闭园通报，确认信息边界、冻结版本并承担治理发布决定。",
        responsibilities: ["接收记者交接", "标记未确认信息", "请求平台复核", "提交教师终评"],
        collaborationRoleIds: ["reporter", "interviewee", "platform_operator"],
        primaryNodeIds: ["brief", "source", "release"],
        deliverableTemplateIds: [],
        successSignals: ["未确认伤情未进入权威表述", "平台与教师决定固定到精确版本"],
        decisionBoundaries: ["不得把人工复核写成审核通过", "不得由模型替代教师终评"],
      },
      {
        roleId: "reporter",
        mission: "采访景区值班员，核定闭园、疏散和安置信息并完成可追溯交接。",
        responsibilities: ["提出边界问题", "保留拒绝与待核项", "形成采访纪要", "向责任编辑交接"],
        collaborationRoleIds: ["responsible_editor", "interviewee"],
        primaryNodeIds: ["brief", "source"],
        deliverableTemplateIds: [],
        successSignals: ["亲历事实与待核信息明确分开", "纪要能回指原互动"],
        decisionBoundaries: ["不得替NPC补充伤情或恢复时间", "不得越权承诺平台发布结果"],
      },
    ],
    nodeGuides: [
      {
        nodeId: "brief",
        situation: "橙色暴雨预警已生效，景区启动闭园，但伤情与恢复时间尚无权威确认。",
        studentGoal: "完成双岗分工、受众、信源和风险门计划。",
        requiredOutputs: ["闭园通报任务卡", "岗位分工", "风险假设"],
        requiredMaterialIds: ["transfer-material-rain-warning"],
        suggestedArtifactTemplateIds: [],
        decisionQuestions: ["哪些信息可立即使用？", "哪些信息必须等待权威来源？"],
        teacherFocus: ["观察学生是否把时效视为约束而不是越过核验门的理由"],
      },
      {
        nodeId: "source",
        situation: "值班员亲历北门关闭与游客转移，但不能确认伤情和最终恢复时间。",
        studentGoal: "形成采访纪要、待核声明与岗位交接。",
        requiredOutputs: ["采访纪要", "信息边界", "下一权威来源"],
        requiredMaterialIds: ["transfer-material-shelter-map"],
        suggestedArtifactTemplateIds: [],
        decisionQuestions: ["NPC能确认到什么程度？", "拒绝之后应向谁核验？"],
        teacherFocus: ["观察记者是否保留拒绝并将待核项交给责任编辑"],
      },
      {
        nodeId: "release",
        situation: "平台要求冻结版本和未确认信息标记，世界后果必须经过教师门。",
        studentGoal: "提交精确通报、取得平台回执并完成固定评价。",
        requiredOutputs: ["闭园通报", "平台回执", "教师终评"],
        requiredMaterialIds: [
          "transfer-material-rain-warning",
          "transfer-material-platform-checklist",
        ],
        suggestedArtifactTemplateIds: [],
        decisionQuestions: ["哪些信息仍需阻断？", "平台提交与审核通过有何区别？"],
        teacherFocus: ["逐维核对采访边界、学生选择、世界后果和个人贡献"],
      },
    ],
    debrief: {
      completionChecklist: ["三节点行为进入同一时间线", "两个NPC私有信息未交叉泄漏", "教师终评固定到同一Rubric"],
      reflectionPrompts: ["若值班员猜测伤情会怎样处理？", "若平台拒绝加急复核，通报如何降级？"],
      transferPrompt: "把同一信息边界和教师门方法迁移到另一类应急融媒通报。",
    },
  },
  experienceDesign: transferExperienceDesign,
  knowledgeChunks: [
    {
      chunkId: "transfer-chunk-emergency-source-boundary",
      domain: "course",
      title: "应急报道信息边界",
      content: "应急报道必须区分权威预警、岗位亲历、未经确认的伤情与恢复时间；不能确认的内容应显式标记并寻找下一权威来源。",
      courseId: transferCourseId,
      nodeId: "source",
      roleId: null,
      competencyId: "C-INTERVIEW-TRANSFER",
      ruleDomain: "emergency-journalism",
      mediaType: "text",
      source: "迁移课程知识库/应急信息边界",
      version: transferVersion,
      visibility: "assigned_team",
      contentHash: hashContent("应急报道必须区分权威预警、岗位亲历、未经确认的伤情与恢复时间；不能确认的内容应显式标记并寻找下一权威来源。"),
      corpusVersion: "transfer-rain-closure/1.0.0",
      status: "active",
      audience: transferCourseAudience,
    },
    {
      chunkId: "transfer-chunk-platform-gate",
      domain: "governance",
      title: "应急通报平台与教师门",
      content: "平台人工复核只表示进入审核流程，不等于审核通过；高风险世界后果和教师终评必须固定到精确版本并由教师确认。",
      courseId: transferCourseId,
      nodeId: "release",
      roleId: "responsible_editor",
      competencyId: "C-GOV-TRANSFER",
      ruleDomain: "platform-governance",
      mediaType: "text",
      source: "迁移课程知识库/平台治理",
      version: transferVersion,
      visibility: "assigned_team",
      contentHash: hashContent("平台人工复核只表示进入审核流程，不等于审核通过；高风险世界后果和教师终评必须固定到精确版本并由教师确认。"),
      corpusVersion: "transfer-rain-closure/1.0.0",
      status: "active",
      audience: createResourceAudience({
        ...transferCourseAudience,
        scopes: ["assigned_team"],
        roleIds: ["responsible_editor"],
      }),
    },
  ],
});

export const transferScenarioV100ContentHash =
  "bab4410c33c4d2a92082310e3d0651b20054d3d05411b527138a34ee72cd45f1";
