import { createMigrationCourse } from "./migration-course-builder.js";
import { defineMigrationSection } from "./migration-section-factory.js";
import { aiCopyrightKnowledgeRecords } from "./migration-knowledge.js";

const sections = [
  defineMigrationSection({
    sectionId: "ai-copyright-source-ledger",
    title: "AI 视觉素材来源台账",
    typicalWorkTask: "登记文旅视觉素材的来源、生成过程与权利状态",
    objectives: [
      "区分创作者、权利人、授权人与生成服务角色",
      "记录提示词版本、参数、筛选与人工修改",
      "识别公开可见、可下载与可发布授权的差异",
    ],
    competencyRefs: ["素材来源管理", "版权基础", "生成过程记录"],
    taskBrief: "为一组仿真文旅海报素材建立来源台账。逐项记录原始素材、AI 生成环节、人类贡献、权利主体、许可范围和待补证事项。",
    sourceKnowledgeIds: [
      "ai-k001-human-contribution-ledger",
      "ai-k003-authorship-and-network-rights",
      "ai-k004-author-and-ownership-boundary",
      "ai-k005-lawful-source-and-ip-duty",
      "ai-k009-metadata-provenance",
    ],
    hiddenFacts: [
      {
        key: "screenshot-only-source",
        summary: "仿真素材包只保留社交平台截图，原始上传页面和作者信息已经丢失。",
        revealCondition: "学生登记第三项素材时触发。",
      },
      {
        key: "paid-account-myth",
        summary: "仿真供应商声称购买生成工具会员即自动取得所有商业发布权，但未提供条款版本。",
        revealCondition: "学生把付费凭证填写为商业许可时触发。",
      },
    ],
    actions: [
      {
        key: "register",
        label: "登记来源与权利主体",
        intent: "register_source_ledger",
        guidance: "分别填写原作者、权利人、授权人、获取地址、许可范围和缺失字段。",
        knowledgeIds: ["ai-k003-authorship-and-network-rights", "ai-k004-author-and-ownership-boundary"],
        evidenceKey: "source",
      },
      {
        key: "trace",
        label: "追踪生成与人工贡献",
        intent: "request_evidence",
        guidance: "记录提示词、参数、模型版本、筛选、重绘与导出元数据，不把工具付费等同授权。",
        knowledgeIds: ["ai-k001-human-contribution-ledger", "ai-k005-lawful-source-and-ip-duty", "ai-k009-metadata-provenance"],
        evidenceKey: "decision",
      },
      {
        key: "freeze",
        label: "冻结素材台账",
        intent: "submit_source_ledger",
        guidance: "将缺失授权和无法追溯的素材标为不可发布，保留补证路径。",
        knowledgeIds: ["ai-k003-authorship-and-network-rights"],
        evidenceKey: "output",
      },
    ],
    primaryActionKey: "freeze",
    event: {
      key: "metadata-loss",
      triggerKind: "on_action",
      triggerKey: "trace",
      studentBrief: "仿真导出文件丢失生成元数据，只剩操作截图。请决定补证、限制用途或拒绝入库。",
      hiddenPayload: "仿真溯源事件：服务端生成编号可请求，但当前素材包未携带该编号。",
      affectedAgentIds: ["agent-copyright", "agent-fact-checker"],
      candidateAgentIds: ["agent-copyright", "agent-fact-checker", "agent-governance-copyright"],
      teacherApprovalRequired: false,
    },
    agentSelection: {
      affectedAgentIds: ["agent-copyright", "agent-fact-checker"],
      candidateAgentIds: ["agent-copyright", "agent-fact-checker", "agent-governance-copyright"],
      selectWhen: "来源、权利主体、许可范围或生成记录缺失时选择能够补充当前判断的智能体。",
      skipWhen: "建议只推测权利结论、不能提供条款或来源依据时跳过。",
      maximumSelectedAgents: 2,
    },
    artifact: {
      label: "AI 文旅视觉素材来源台账",
      format: "structured_form",
      completionCriteria: ["每项素材有来源与权利主体", "生成和人工贡献可追溯", "缺失项含用途限制与补证动作"],
      finalCourseArtifact: false,
    },
    evidenceFocus: {
      source: "原始地址、作者/权利人、许可条款版本与生成元数据。",
      decision: "对来源缺失与会员授权说法作出采纳、补证或拒绝决定。",
      output: "含可发布、限制使用和不可使用状态的版本化素材台账。",
    },
    rubricFocus: {
      accuracy: "创作者、权利人和授权范围未混同，来源均可定位。",
      reasoning: "能够解释为何调用或跳过核查、版权与版权治理智能体。",
      deliverable: "台账可支持后续生成判断、权利检查和平台审核。",
      transfer: "能迁移到视频、配乐或数字人素材台账。",
      failClosedWhen: "把公开可下载或工具会员凭证直接视为商业发布授权",
    },
    teacherGate: {
      label: "素材入库来源门",
      trigger: "before_section_complete",
      checks: ["来源定位完整", "权利主体分离", "生成记录与用途限制清晰"],
      minimumEvidenceCount: 3,
      rejectReturnsToActionKey: "trace",
    },
    reflection: {
      prompt: "若素材来自同事转发且无法找到原页面，台账应如何保留线索并限制使用？",
      targetContext: "组织内部共享的视觉与音频素材",
      comparisonDimensions: ["来源链", "权利主体", "许可范围", "补证成本"],
    },
  }),
  defineMigrationSection({
    sectionId: "ai-copyright-generation-assessment",
    title: "生成属性与人类贡献判断",
    typicalWorkTask: "判断混合视觉作品的生成环节与人工创作贡献",
    objectives: [
      "区分生成属性判断与著作权结论",
      "按组件记录真人拍摄、AI 生成和人工后期",
      "对检测结果、元数据与过程证据进行交叉核验",
    ],
    competencyRefs: ["AI 内容识别", "创作过程分析", "证据推理"],
    taskBrief: "分析一张由真人照片、AI 背景和人工排版组成的仿真文旅海报，给出组件级生成判断、证据强度和仍需核验的问题。",
    sourceKnowledgeIds: [
      "ai-k001-human-contribution-ledger",
      "ai-k002-case-specific-copyright-judgement",
      "ai-k005-lawful-source-and-ip-duty",
    ],
    hiddenFacts: [
      {
        key: "mixed-production",
        summary: "仿真海报的主体照片为人工拍摄，背景由生成工具创建，文字与版式由设计者后期完成。",
        revealCondition: "学生提交整体二选一判断后触发组件拆分提示。",
      },
      {
        key: "detector-conflict",
        summary: "两个仿真检测器给出相反置信度，且都未说明适用模型版本。",
        revealCondition: "学生引用检测分数作唯一结论时触发。",
      },
    ],
    actions: [
      {
        key: "decompose",
        label: "拆分视觉组件",
        intent: "decompose_generation_components",
        guidance: "按主体、背景、文字、版式和后期分别登记生成方式与证据。",
        knowledgeIds: ["ai-k001-human-contribution-ledger"],
        evidenceKey: "source",
      },
      {
        key: "compare",
        label: "比较过程与检测证据",
        intent: "request_evidence",
        guidance: "比较生成记录、文件元数据、人工修改和检测结果，不把置信度当法律结论。",
        knowledgeIds: ["ai-k002-case-specific-copyright-judgement", "ai-k005-lawful-source-and-ip-duty"],
        evidenceKey: "decision",
      },
      {
        key: "assess",
        label: "提交生成属性评估",
        intent: "submit_generation_assessment",
        guidance: "逐组件写明判断、证据强度、不确定性和下一步补证。",
        knowledgeIds: ["ai-k001-human-contribution-ledger", "ai-k002-case-specific-copyright-judgement"],
        evidenceKey: "output",
      },
    ],
    primaryActionKey: "assess",
    event: {
      key: "conflicting-detectors",
      triggerKind: "on_action",
      triggerKey: "compare",
      studentBrief: "两个仿真检测结果相互冲突。请决定补证或限制结论，不得用单一分数盖棺定论。",
      hiddenPayload: "仿真检测事件：检测工具训练范围未知，生成过程日志可提供更直接证据。",
      affectedAgentIds: ["agent-fact-checker", "agent-governance-content-safety"],
      candidateAgentIds: ["agent-fact-checker", "agent-governance-content-safety", "agent-copyright"],
      teacherApprovalRequired: false,
    },
    agentSelection: {
      affectedAgentIds: ["agent-fact-checker", "agent-governance-content-safety"],
      candidateAgentIds: ["agent-fact-checker", "agent-governance-content-safety", "agent-copyright"],
      selectWhen: "生成过程、检测结果或组件判断存在冲突时选择必要智能体。",
      skipWhen: "候选只给无来源概率或把生成属性直接等同权利结论时跳过。",
      maximumSelectedAgents: 2,
    },
    artifact: {
      label: "组件级生成属性评估表",
      format: "structured_form",
      completionCriteria: ["至少拆分四类组件", "证据强弱与不确定性明确", "生成判断与权利判断分栏"],
      finalCourseArtifact: false,
    },
    evidenceFocus: {
      source: "生成日志、文件元数据、人工修改记录与检测条件。",
      decision: "对冲突检测建议作出决定并写明证据优先级。",
      output: "组件级判断、置信边界和补证计划。",
    },
    rubricFocus: {
      accuracy: "生成过程与权利结论严格分开，检测工具适用边界明确。",
      reasoning: "冲突证据的权重和智能体选择理由可复核。",
      deliverable: "评估表可供下一节权利检查直接引用。",
      transfer: "能迁移到混合生成视频或数字人作品。",
      failClosedWhen: "用一个检测分数认定整件作品的生成属性或版权归属",
    },
    teacherGate: {
      label: "生成判断证据门",
      trigger: "before_section_complete",
      checks: ["组件拆分充分", "检测条件已记录", "权利结论未越界"],
      minimumEvidenceCount: 3,
      rejectReturnsToActionKey: "compare",
    },
    reflection: {
      prompt: "当作品包含生成式补帧或局部修复时，组件拆分和证据等级应怎样变化？",
      targetContext: "混合生成视频和修复类图像",
      comparisonDimensions: ["组件边界", "过程证据", "工具适用性", "结论强度"],
    },
  }),
  defineMigrationSection({
    sectionId: "ai-copyright-rights-check",
    title: "版权与许可范围检查",
    typicalWorkTask: "核验视觉素材的权利归属、许可范围与发布风险",
    objectives: [
      "核对署名、修改、完整和网络传播等权利",
      "识别提示词、参考素材和输出中的第三方权利",
      "在许可冲突时提出替换、补证或限制使用方案",
    ],
    competencyRefs: ["版权审核", "许可解释", "风险处置"],
    taskBrief: "根据来源台账和生成评估，对仿真海报执行发布前权利检查，分别判断参考素材、输出画面、字体、标识和传播渠道。",
    sourceKnowledgeIds: [
      "ai-k002-case-specific-copyright-judgement",
      "ai-k003-authorship-and-network-rights",
      "ai-k004-author-and-ownership-boundary",
      "ai-k005-lawful-source-and-ip-duty",
      "ai-k012-complaint-evidence-preservation",
    ],
    hiddenFacts: [
      {
        key: "protected-character-reference",
        summary: "仿真提示词要求高度接近一个受保护角色，但台账只登记了生成工具。",
        revealCondition: "学生只检查输出文件作者时触发。",
      },
      {
        key: "internal-preview-license",
        summary: "仿真供应合同只允许内部提案预览，不包含公开网络传播。",
        revealCondition: "学生准备标记可发布时触发。",
      },
    ],
    actions: [
      {
        key: "ownership",
        label: "核对权利主体",
        intent: "check_rights_ownership",
        guidance: "分别核对创作者、权利人、被许可人和第三方素材权利。",
        knowledgeIds: ["ai-k003-authorship-and-network-rights", "ai-k004-author-and-ownership-boundary"],
        evidenceKey: "source",
      },
      {
        key: "scope",
        label: "检查许可与传播范围",
        intent: "request_evidence",
        guidance: "对照渠道、地域、期限、修改、转授权和署名要求，记录冲突。",
        knowledgeIds: ["ai-k005-lawful-source-and-ip-duty", "ai-k012-complaint-evidence-preservation"],
        evidenceKey: "decision",
      },
      {
        key: "dispose",
        label: "提交权利处置方案",
        intent: "submit_rights_disposition",
        guidance: "对每项风险选择替换、补证、限制使用或拒绝发布。",
        knowledgeIds: ["ai-k002-case-specific-copyright-judgement", "ai-k003-authorship-and-network-rights"],
        evidenceKey: "output",
      },
    ],
    primaryActionKey: "dispose",
    event: {
      key: "license-conflict",
      triggerKind: "on_action",
      triggerKey: "scope",
      studentBrief: "合同只授权内部预览，但仿真发布计划包含公开平台。请停止自动通过并提交处置方案。",
      hiddenPayload: "仿真许可事件：公开网络传播未授权，存在可替换的自制背景素材。",
      affectedAgentIds: ["agent-copyright", "agent-governance-copyright"],
      candidateAgentIds: ["agent-copyright", "agent-governance-copyright", "agent-chief", "agent-evidence-assessor"],
      teacherApprovalRequired: true,
    },
    agentSelection: {
      affectedAgentIds: ["agent-copyright", "agent-governance-copyright"],
      candidateAgentIds: ["agent-copyright", "agent-governance-copyright", "agent-chief", "agent-evidence-assessor"],
      selectWhen: "权利主体、许可范围或第三方要素影响发布决定时选择相应智能体。",
      skipWhen: "候选不能指出具体权利、条款或替代行动时跳过。",
      maximumSelectedAgents: 3,
    },
    artifact: {
      label: "视觉作品版权检查与处置单",
      format: "evidence_bundle",
      completionCriteria: ["权利要素逐项核验", "许可范围与发布渠道匹配", "每项风险有可执行处置"],
      finalCourseArtifact: false,
    },
    evidenceFocus: {
      source: "作者、权利人、合同条款、参考素材和授权定位。",
      decision: "对许可冲突建议作出补证、替换或拒绝决定。",
      output: "包含风险级别、处置动作和教师门状态的版权检查单。",
    },
    rubricFocus: {
      accuracy: "权利类型、主体和许可范围均有具体依据。",
      reasoning: "能说明哪些智能体对发布决定产生必要贡献。",
      deliverable: "处置单可直接驱动替换、补授权或停止发布。",
      transfer: "能迁移到音乐、字体、商标和人物肖像检查。",
      failClosedWhen: "许可只覆盖内部预览却仍标记公开发布可用",
    },
    teacherGate: {
      label: "高风险权利发布门",
      trigger: "before_publish",
      checks: ["公开传播权范围明确", "第三方要素已处置", "替代或补证路径可执行"],
      minimumEvidenceCount: 3,
      rejectReturnsToActionKey: "scope",
    },
    reflection: {
      prompt: "如果同一素材改用于商业广告而非公益课程，许可检查会增加哪些字段？",
      targetContext: "商业传播与跨平台再许可",
      comparisonDimensions: ["用途", "渠道", "期限", "修改与转授权"],
    },
  }),
  defineMigrationSection({
    sectionId: "ai-copyright-labeling",
    title: "显式与隐式标识方案",
    typicalWorkTask: "为生成合成视觉内容设计并验证双层标识",
    objectives: [
      "区分公众可见的显式标识与文件内隐式标识",
      "按图片和视频形态确定标识位置与持续时间",
      "验证转码、裁切和再发布后的标识完整性",
    ],
    competencyRefs: ["AI 内容标识", "媒体技术", "合规验证"],
    taskBrief: "为仿真海报及其短视频版本设计显式、隐式标识方案，执行裁切和转码测试，并记录失效后的补救措施。",
    sourceKnowledgeIds: [
      "ai-k006-generated-content-label-duty",
      "ai-k007-explicit-and-implicit-definitions",
      "ai-k008-modality-label-placement",
      "ai-k009-metadata-provenance",
      "ai-k010-platform-verification-and-user-declaration",
    ],
    hiddenFacts: [
      {
        key: "visible-label-cropped",
        summary: "仿真竖屏裁切会移除横版海报右下角的显式 AI 标识。",
        revealCondition: "学生完成多尺寸导出后触发。",
      },
      {
        key: "implicit-label-lost",
        summary: "仿真转码流程会丢失原文件中的隐式标识字段。",
        revealCondition: "学生只检查源文件元数据时触发。",
      },
    ],
    actions: [
      {
        key: "design",
        label: "设计双层标识",
        intent: "design_ai_labels",
        guidance: "分别写明图片、视频的显式位置、文案、隐式字段和用户声明。",
        knowledgeIds: ["ai-k006-generated-content-label-duty", "ai-k007-explicit-and-implicit-definitions", "ai-k008-modality-label-placement"],
        evidenceKey: "source",
      },
      {
        key: "test",
        label: "执行裁切与转码测试",
        intent: "request_evidence",
        guidance: "检查各尺寸的可见性、播放阶段和导出后元数据保留情况。",
        knowledgeIds: ["ai-k009-metadata-provenance", "ai-k010-platform-verification-and-user-declaration"],
        evidenceKey: "decision",
      },
      {
        key: "freeze",
        label: "冻结标识发布清单",
        intent: "submit_label_plan",
        guidance: "记录每个平台的标识状态、失败补救和发布者声明。",
        knowledgeIds: ["ai-k006-generated-content-label-duty", "ai-k010-platform-verification-and-user-declaration"],
        evidenceKey: "output",
      },
    ],
    primaryActionKey: "freeze",
    event: {
      key: "transcode-loss",
      triggerKind: "on_action",
      triggerKey: "test",
      studentBrief: "仿真平台转码后隐式标识丢失且竖屏裁切遮挡显式标识。请修订发布版本。",
      hiddenPayload: "仿真标识事件：可通过安全区重排显式标识并在上传流程重新写入隐式字段。",
      affectedAgentIds: ["agent-governance-content-safety", "agent-governance-platform-rule"],
      candidateAgentIds: ["agent-governance-content-safety", "agent-governance-platform-rule", "agent-platform"],
      teacherApprovalRequired: false,
    },
    agentSelection: {
      affectedAgentIds: ["agent-governance-content-safety", "agent-governance-platform-rule"],
      candidateAgentIds: ["agent-governance-content-safety", "agent-governance-platform-rule", "agent-platform"],
      selectWhen: "标识位置、元数据或平台上传验证发生失效时选择必要智能体。",
      skipWhen: "候选建议不能改变标识可见性、可验证性或平台状态时跳过。",
      maximumSelectedAgents: 2,
    },
    artifact: {
      label: "AI 视觉双层标识发布清单",
      format: "structured_form",
      completionCriteria: ["显式与隐式标识分栏", "图片和视频均完成测试", "失效补救与用户声明明确"],
      finalCourseArtifact: false,
    },
    evidenceFocus: {
      source: "标识办法条款定位、原文件与转码文件的检测记录。",
      decision: "对裁切和元数据丢失建议作出修订或补证决定。",
      output: "按平台、模态和版本记录的双层标识清单。",
    },
    rubricFocus: {
      accuracy: "显式、隐式标识的定义和模态要求没有混淆。",
      reasoning: "能说明治理、规则和平台智能体的必要性。",
      deliverable: "清单能指导编辑完成上传前后验证。",
      transfer: "能迁移到音频、数字人和直播生成内容。",
      failClosedWhen: "任一发布版本的显式与隐式标识均不可验证",
    },
    teacherGate: {
      label: "AI 标识完整性门",
      trigger: "before_publish",
      checks: ["显式标识可见", "隐式字段可检", "转码失效有补救"],
      minimumEvidenceCount: 3,
      rejectReturnsToActionKey: "test",
    },
    reflection: {
      prompt: "当平台会自动添加提示时，发布者自己的标识和声明还应保留哪些部分？",
      targetContext: "第三方平台自动标识与跨平台再传播",
      comparisonDimensions: ["责任主体", "显式位置", "隐式字段", "转码验证"],
    },
  }),
  defineMigrationSection({
    sectionId: "ai-copyright-platform-review",
    title: "平台规则预审与发布决定",
    typicalWorkTask: "综合版权、标识和平台规则完成发布预审",
    objectives: [
      "校验用户声明、隐式标识和检测结果的一致性",
      "区分提交成功、审核通过与正式发布状态",
      "在规则冲突时维持人工门和失败关闭",
    ],
    competencyRefs: ["平台内容审核", "发布状态管理", "人工决策"],
    taskBrief: "把版权检查单与标识清单装配成平台预审包，解释每条规则的证据，并对冲突、缺失和驳回状态作出发布决定。",
    sourceKnowledgeIds: [
      "ai-k006-generated-content-label-duty",
      "ai-k008-modality-label-placement",
      "ai-k010-platform-verification-and-user-declaration",
      "ai-k011-lifecycle-trace-and-complaint",
    ],
    hiddenFacts: [
      {
        key: "declaration-conflict",
        summary: "仿真上传者选择“非 AI 生成”，但文件元数据和来源台账均记录生成背景。",
        revealCondition: "学生执行平台预检时触发。",
      },
      {
        key: "submitted-not-approved",
        summary: "仿真接口只返回“已提交审核”，尚未获得平台通过状态。",
        revealCondition: "学生将提交成功标为正式发布时触发。",
      },
    ],
    actions: [
      {
        key: "preflight",
        label: "装配平台预审包",
        intent: "assemble_platform_review",
        guidance: "对照权利、标识、声明和平台字段建立证据矩阵。",
        knowledgeIds: ["ai-k006-generated-content-label-duty", "ai-k008-modality-label-placement", "ai-k010-platform-verification-and-user-declaration"],
        evidenceKey: "source",
      },
      {
        key: "resolve",
        label: "处理声明与状态冲突",
        intent: "request_evidence",
        guidance: "更正用户声明，区分草稿、已提交、待审核、驳回和已发布。",
        knowledgeIds: ["ai-k010-platform-verification-and-user-declaration", "ai-k011-lifecycle-trace-and-complaint"],
        evidenceKey: "decision",
      },
      {
        key: "submit",
        label: "提交人工发布决定",
        intent: "submit_platform_decision",
        guidance: "在证据齐全时提交通过建议；冲突未解时明确失败关闭。",
        knowledgeIds: ["ai-k011-lifecycle-trace-and-complaint"],
        evidenceKey: "output",
      },
    ],
    primaryActionKey: "submit",
    event: {
      key: "review-conflict",
      triggerKind: "on_action",
      triggerKey: "resolve",
      studentBrief: "仿真平台返回审核冲突，原因是用户声明与隐式标识不一致。请修订并进入教师发布门。",
      hiddenPayload: "仿真审核事件：平台尚未批准，任何世界发布写入都必须保持关闭。",
      affectedAgentIds: ["agent-platform", "agent-governance-platform-rule"],
      candidateAgentIds: ["agent-platform", "agent-governance-platform-rule", "agent-governance-content-safety", "agent-chief"],
      teacherApprovalRequired: true,
    },
    agentSelection: {
      affectedAgentIds: ["agent-platform", "agent-governance-platform-rule"],
      candidateAgentIds: ["agent-platform", "agent-governance-platform-rule", "agent-governance-content-safety", "agent-chief"],
      selectWhen: "用户声明、标识检测或平台状态发生冲突时选择必要智能体。",
      skipWhen: "候选只重复技术状态、不能改变发布证据或决定时跳过。",
      maximumSelectedAgents: 3,
    },
    artifact: {
      label: "AI 文旅作品平台预审包",
      format: "evidence_bundle",
      completionCriteria: ["规则—证据矩阵完整", "提交与审核状态分离", "人工发布决定可追溯"],
      finalCourseArtifact: false,
    },
    evidenceFocus: {
      source: "版权检查、双层标识、用户声明和平台状态回执。",
      decision: "对声明冲突和平台规则建议作出修订、补证或拒绝决定。",
      output: "包含状态机、失败原因和人工门结果的预审包。",
    },
    rubricFocus: {
      accuracy: "规则、声明、标识和平台状态相互一致且有证据。",
      reasoning: "被选择智能体确实解决当前冲突，未全量调用。",
      deliverable: "预审包能区分可提交、待审核、驳回与可发布。",
      transfer: "能迁移到另一平台的规则与状态字段。",
      failClosedWhen: "把已提交审核伪装为平台已通过或正式发布",
    },
    teacherGate: {
      label: "平台正式发布门",
      trigger: "before_publish",
      checks: ["用户声明一致", "标识验证通过", "权利与平台状态允许发布"],
      minimumEvidenceCount: 3,
      rejectReturnsToActionKey: "resolve",
    },
    reflection: {
      prompt: "如果另一平台使用不同声明字段，哪些证据可以复用，哪些必须重新验证？",
      targetContext: "生成内容的跨平台发布",
      comparisonDimensions: ["规则字段", "标识验证", "审核状态", "人工门"],
    },
  }),
  defineMigrationSection({
    sectionId: "ai-copyright-complaint-correction",
    title: "版权投诉与公开更正",
    typicalWorkTask: "受理版权投诉、冻结证据并实施多端更正",
    objectives: [
      "核验投诉主体、权属材料与涉嫌侵权版本",
      "区分临时下架、补授权、替换和公开更正",
      "确保所有再发布渠道同步处置并保留证据",
    ],
    competencyRefs: ["投诉处置", "证据保全", "更正传播"],
    taskBrief: "处理一项仿真海报版权投诉。冻结当前及历史版本，核验权属材料，制定临时措施与最终更正，并检查所有转载渠道。",
    sourceKnowledgeIds: [
      "ai-k011-lifecycle-trace-and-complaint",
      "ai-k012-complaint-evidence-preservation",
    ],
    hiddenFacts: [
      {
        key: "valid-authorship-evidence",
        summary: "仿真投诉人提交了可相互印证的底稿、登记材料和早期发布记录。",
        revealCondition: "学生完成投诉材料初审后触发。",
      },
      {
        key: "repost-still-live",
        summary: "主账号已下架仿真海报，但一个合作账号仍保留旧版转载。",
        revealCondition: "学生标记处置完成时触发。",
      },
    ],
    actions: [
      {
        key: "freeze",
        label: "冻结投诉证据",
        intent: "freeze_complaint_evidence",
        guidance: "保存权属材料定位、发布时间线、各端版本和处置前状态。",
        knowledgeIds: ["ai-k011-lifecycle-trace-and-complaint", "ai-k012-complaint-evidence-preservation"],
        evidenceKey: "source",
      },
      {
        key: "decide",
        label: "决定临时与最终处置",
        intent: "decide_agent_contribution",
        guidance: "根据证据选择临时下架、补证、替换、补授权或拒绝投诉，并写明依据。",
        knowledgeIds: ["ai-k012-complaint-evidence-preservation"],
        evidenceKey: "decision",
      },
      {
        key: "correct",
        label: "发布并同步更正",
        intent: "publish_correction",
        guidance: "生成不扩大未经证实指控的更正说明，逐端回写处置结果。",
        knowledgeIds: ["ai-k011-lifecycle-trace-and-complaint"],
        evidenceKey: "output",
      },
    ],
    primaryActionKey: "correct",
    event: {
      key: "complaint-with-repost",
      triggerKind: "on_action",
      triggerKey: "decide",
      studentBrief: "仿真投诉材料通过初核，但合作账号仍传播旧版。请同步临时处置和公开更正。",
      hiddenPayload: "仿真投诉事件：投诉人的权属证据较强，合作账号转载版本需纳入处置范围。",
      affectedAgentIds: ["agent-copyright", "agent-platform"],
      candidateAgentIds: ["agent-copyright", "agent-platform", "agent-evidence-assessor", "agent-learning"],
      teacherApprovalRequired: true,
    },
    agentSelection: {
      affectedAgentIds: ["agent-copyright", "agent-platform"],
      candidateAgentIds: ["agent-copyright", "agent-platform", "agent-evidence-assessor", "agent-learning"],
      selectWhen: "权属证据、处置范围或跨端更正需要专业判断时选择必要智能体。",
      skipWhen: "建议不能增加证据、明确范围或改变处置动作时跳过。",
      maximumSelectedAgents: 3,
    },
    artifact: {
      label: "AI 文旅视觉作品投诉处置与更正包",
      format: "evidence_bundle",
      completionCriteria: ["投诉证据与版本链完整", "临时和最终措施分离", "全部发布渠道有回执"],
      finalCourseArtifact: true,
    },
    evidenceFocus: {
      source: "权属材料、历史版本、发布时间线和各端当前状态。",
      decision: "对投诉、下架、补证与更正建议作出有依据的决定。",
      output: "处置单、公开更正、各端同步回执与课程最终作品。",
    },
    rubricFocus: {
      accuracy: "投诉材料、版本和渠道状态可追溯，未扩大未证实指控。",
      reasoning: "版权、平台与证据智能体的贡献均能回指实际处置。",
      deliverable: "更正包覆盖主账号、合作账号和后续防复发动作。",
      transfer: "能迁移到误标识、事实错误或肖像权投诉。",
      failClosedWhen: "未冻结证据即覆盖旧版，或仍有已知转载渠道未处置却宣称完成",
    },
    teacherGate: {
      label: "投诉结案与公开更正门",
      trigger: "before_publish",
      checks: ["权属证据充分", "处置范围覆盖全部渠道", "更正文案准确克制"],
      minimumEvidenceCount: 3,
      rejectReturnsToActionKey: "decide",
    },
    reflection: {
      prompt: "如果投诉证据不足但风险较高，临时措施与公开表述应如何调整？",
      targetContext: "版权、肖像或事实争议的快速处置",
      comparisonDimensions: ["证据强度", "临时措施", "公开表述", "渠道同步"],
    },
  }),
] as const;

export const aiCopyrightCourseRelease = createMigrationCourse({
  courseId: "course-ai-tourism-copyright-governance",
  releaseId: "release-course-ai-tourism-copyright-governance-2.0.0-content.1",
  version: "2.0.0-content.1",
  title: "AI 文旅视觉版权与内容治理",
  summary: "围绕文旅海报的来源、生成属性、版权、显隐式标识、平台预审和投诉更正，训练记者在智能体协作下作出可追溯的人类决定；案例冲突均为教学仿真。",
  durationMinutes: 180,
  courseOutcomes: [
    "能建立 AI 视觉素材来源、生成过程与权利台账",
    "能区分生成判断、版权判断和平台规则判断",
    "能验证显式与隐式标识在裁切、转码和发布后的完整性",
    "能完成投诉证据保全、跨端处置与公开更正",
  ],
  sections,
  knowledgeRecords: aiCopyrightKnowledgeRecords,
});

export const aiCopyrightSectionCount = aiCopyrightCourseRelease.sections.length;
