import { createMigrationCourse } from "./migration-course-builder.js";
import { defineMigrationSection } from "./migration-section-factory.js";
import { rainEmergencyKnowledgeRecords } from "./migration-knowledge.js";

const sections = [
  defineMigrationSection({
    sectionId: "rain-warning-verification",
    title: "暴雨预警核验与影响判断",
    typicalWorkTask: "核验气象预警并形成景区影响清单",
    objectives: [
      "核对预警发布机构、等级、时间和影响范围",
      "区分气象预警、景区管理决定和记者观察",
      "将预警变化转化为下一步采集任务",
    ],
    competencyRefs: ["突发信息核验", "气象风险理解", "任务拆解"],
    taskBrief: "仿真景区所在区域出现暴雨预警。请核验官方信号、建立版本时间线，并列出对开放状态、交通、游客服务和采访安全的影响。",
    sourceKnowledgeIds: [
      "rain-k001-warning-levels-and-thresholds",
      "rain-k002-warning-defense-guidance",
      "rain-k003-check-open-status-before-travel",
      "rain-k012-warning-feedback-loop",
    ],
    hiddenFacts: [
      {
        key: "old-warning-screenshot",
        summary: "仿真群聊截图来自前一日蓝色预警，当前官方页面已更新为更高级别。",
        revealCondition: "学生把截图作为当前预警时触发。",
      },
      {
        key: "status-not-yet-closure",
        summary: "仿真景区正在会商，尚未形成闭园决定，不能把预警自动写成已闭园。",
        revealCondition: "学生提交影响清单时触发。",
      },
    ],
    actions: [
      {
        key: "collect",
        label: "采集官方预警信号",
        intent: "collect_warning_sources",
        guidance: "记录发布机构、等级、发布时间、生效时间、区域和原始链接。",
        knowledgeIds: ["rain-k001-warning-levels-and-thresholds", "rain-k002-warning-defense-guidance"],
        evidenceKey: "source",
      },
      {
        key: "compare",
        label: "比较版本与开放状态",
        intent: "request_evidence",
        guidance: "核对截图与当前页面，另行查询景区开放状态和管理决定。",
        knowledgeIds: ["rain-k003-check-open-status-before-travel", "rain-k012-warning-feedback-loop"],
        evidenceKey: "decision",
      },
      {
        key: "brief",
        label: "提交影响与采集清单",
        intent: "submit_warning_brief",
        guidance: "分列已确认、待确认、不可推断和下一次核验时间。",
        knowledgeIds: ["rain-k012-warning-feedback-loop"],
        evidenceKey: "output",
      },
    ],
    primaryActionKey: "brief",
    event: {
      key: "warning-upgrade",
      triggerKind: "on_action",
      triggerKey: "compare",
      studentBrief: "仿真官方预警升级，请更新影响清单并决定哪些智能体需要重新评估。",
      hiddenPayload: "仿真世界事件：预警等级已升级，景区管理决定仍待会商。",
      affectedAgentIds: ["agent-fact-checker", "agent-scene-director"],
      candidateAgentIds: ["agent-fact-checker", "agent-scene-director", "agent-chief"],
      teacherApprovalRequired: false,
    },
    agentSelection: {
      affectedAgentIds: ["agent-fact-checker", "agent-scene-director"],
      candidateAgentIds: ["agent-fact-checker", "agent-scene-director", "agent-chief"],
      selectWhen: "预警等级、时间或影响范围变化时选择核查与情境导演智能体。",
      skipWhen: "候选无法提供新的官方信号、影响集合或采访安全动作时跳过。",
      maximumSelectedAgents: 2,
    },
    artifact: {
      label: "预警版本与景区影响清单",
      format: "structured_form",
      completionCriteria: ["官方信号字段完整", "预警与管理决定分离", "下一次核验任务明确"],
      finalCourseArtifact: false,
    },
    evidenceFocus: {
      source: "气象官方页面、景区开放状态和各版本时间戳。",
      decision: "对预警升级建议作出采纳、补证或拒绝决定。",
      output: "含已确认、待确认、不可推断和下一步任务的影响清单。",
    },
    rubricFocus: {
      accuracy: "预警等级、时间、区域和来源准确，未自动推断闭园。",
      reasoning: "智能体选择与当前预警变化和影响集合一致。",
      deliverable: "清单可直接驱动闭园快讯与游客服务采集。",
      transfer: "能迁移到高温、台风或地质灾害预警报道。",
      failClosedWhen: "使用过期截图或把气象预警直接写成景区已经闭园",
    },
    teacherGate: {
      label: "预警事实核准门",
      trigger: "before_section_complete",
      checks: ["官方来源有效", "版本关系清楚", "预警与景区决定未混同"],
      minimumEvidenceCount: 3,
      rejectReturnsToActionKey: "compare",
    },
    reflection: {
      prompt: "若不同区县同时发布不同等级预警，报道范围和标题应如何避免过度概括？",
      targetContext: "跨区域极端天气报道",
      comparisonDimensions: ["发布主体", "空间范围", "时间版本", "管理决定"],
    },
  }),
  defineMigrationSection({
    sectionId: "rain-closure-brief",
    title: "闭园快讯与状态更正",
    typicalWorkTask: "依据管理决定发布闭园快讯并维护状态版本",
    objectives: [
      "核验闭园决定的发布主体、范围和生效时间",
      "写出包含游客服务信息的短快讯",
      "在范围变化时同步更正所有版本",
    ],
    competencyRefs: ["突发快讯", "管理信息核验", "多端更正"],
    taskBrief: "收到仿真景区管理决定后，发布一条闭园快讯。必须写明适用区域、生效时间、咨询/退票入口和下一次更新时间。",
    sourceKnowledgeIds: [
      "rain-k001-warning-levels-and-thresholds",
      "rain-k004-close-and-transfer-visitors",
      "rain-k005-multichannel-warning-release",
      "rain-k007-timely-and-accurate-reporting",
    ],
    hiddenFacts: [
      {
        key: "partial-then-full",
        summary: "仿真首份通知只关闭山地区域，十分钟后管理方决定全园闭园。",
        revealCondition: "学生发布首版闭园快讯后触发。",
      },
      {
        key: "refund-link-delayed",
        summary: "仿真退票入口尚未更新，旧链接会显示常规退改规则。",
        revealCondition: "学生把旧链接放入快讯时触发。",
      },
    ],
    actions: [
      {
        key: "draft",
        label: "起草闭园快讯",
        intent: "draft_closure_brief",
        guidance: "按谁决定、何时生效、关闭范围、游客动作和下次更新组织文本。",
        knowledgeIds: ["rain-k004-close-and-transfer-visitors", "rain-k005-multichannel-warning-release"],
        evidenceKey: "source",
      },
      {
        key: "verify",
        label: "核验决定与服务入口",
        intent: "request_evidence",
        guidance: "核对管理方原文、范围、退票入口和咨询电话的当前状态。",
        knowledgeIds: ["rain-k001-warning-levels-and-thresholds", "rain-k007-timely-and-accurate-reporting"],
        evidenceKey: "decision",
      },
      {
        key: "publish",
        label: "发布并维护闭园状态",
        intent: "publish_closure_brief",
        guidance: "发布当前版本；范围变化时回指旧版并同步更正。",
        knowledgeIds: ["rain-k005-multichannel-warning-release", "rain-k007-timely-and-accurate-reporting"],
        evidenceKey: "output",
      },
    ],
    primaryActionKey: "publish",
    event: {
      key: "closure-scope-update",
      triggerKind: "on_action",
      triggerKey: "publish",
      studentBrief: "仿真管理方把局部关闭升级为全园闭园。请立即更正范围并保留首版关系。",
      hiddenPayload: "仿真管理事件：全园闭园决定现已生效，退票新入口将在下一版本提供。",
      affectedAgentIds: ["agent-fact-checker", "agent-platform"],
      candidateAgentIds: ["agent-fact-checker", "agent-platform", "agent-chief", "agent-scene-director"],
      teacherApprovalRequired: false,
    },
    agentSelection: {
      affectedAgentIds: ["agent-fact-checker", "agent-platform"],
      candidateAgentIds: ["agent-fact-checker", "agent-platform", "agent-chief", "agent-scene-director"],
      selectWhen: "闭园主体、范围、时间或多端版本发生变化时选择必要智能体。",
      skipWhen: "候选不能改变事实核验、服务信息或更正范围时跳过。",
      maximumSelectedAgents: 2,
    },
    artifact: {
      label: "闭园快讯与更正记录",
      format: "article",
      completionCriteria: ["闭园五要素齐全", "游客服务入口状态准确", "范围变化可追溯"],
      finalCourseArtifact: false,
    },
    evidenceFocus: {
      source: "闭园决定、服务入口、咨询方式与版本时间戳。",
      decision: "对范围更新和服务信息建议作出明确决定。",
      output: "首版快讯、更正版和多端同步记录。",
    },
    rubricFocus: {
      accuracy: "闭园主体、范围、时间和服务信息均可核验。",
      reasoning: "说明核查、平台和主编智能体被选或跳过的原因。",
      deliverable: "快讯简洁、行动清楚并可持续更新。",
      transfer: "能迁移到交通停运或活动取消快讯。",
      failClosedWhen: "闭园范围或生效时间未经管理方确认，或旧退票链接被写成当前入口",
    },
    teacherGate: {
      label: "闭园快讯发布门",
      trigger: "before_publish",
      checks: ["管理决定可定位", "范围与时间准确", "游客行动信息可用"],
      minimumEvidenceCount: 3,
      rejectReturnsToActionKey: "verify",
    },
    reflection: {
      prompt: "当管理决定只覆盖部分设施时，标题、导语和服务信息如何避免制造全园闭园误解？",
      targetContext: "局部停运与分阶段关闭信息",
      comparisonDimensions: ["决定主体", "适用范围", "服务影响", "更正策略"],
    },
  }),
  defineMigrationSection({
    sectionId: "rain-visitor-guidance",
    title: "游客疏导与服务指引",
    typicalWorkTask: "核验并发布避险路线、安置点和游客服务信息",
    objectives: [
      "把泛化安全提示转化为可执行服务信息",
      "核验路线、安置点容量和责任联系人",
      "区分管理指令、现场观察和个体描述",
    ],
    competencyRefs: ["公共服务信息", "现场核验", "风险沟通"],
    taskBrief: "根据仿真闭园状态，为园内、在途和计划前往的游客分别编写行动指引，核验疏散路线、安置点、交通与退票信息。",
    sourceKnowledgeIds: [
      "rain-k003-check-open-status-before-travel",
      "rain-k004-close-and-transfer-visitors",
      "rain-k006-evacuation-route-and-shelter",
      "rain-k008-follow-on-site-evacuation",
    ],
    hiddenFacts: [
      {
        key: "shelter-full",
        summary: "仿真东门安置点容量已满，管理方正在启用第二安置点。",
        revealCondition: "学生选择东门作为唯一安置点时触发。",
      },
      {
        key: "route-flooded",
        summary: "仿真北侧步道出现积水，旧疏散图仍将其标为可通行。",
        revealCondition: "学生引用旧路线图时触发。",
      },
    ],
    actions: [
      {
        key: "map",
        label: "建立分人群服务地图",
        intent: "map_visitor_guidance",
        guidance: "分别列出园内、在途和计划出行游客的地点、行动和查询入口。",
        knowledgeIds: ["rain-k003-check-open-status-before-travel", "rain-k004-close-and-transfer-visitors"],
        evidenceKey: "source",
      },
      {
        key: "capacity",
        label: "核验路线与安置容量",
        intent: "request_evidence",
        guidance: "核对现场管理口径、路线当前状态、安置点容量和责任联系人。",
        knowledgeIds: ["rain-k006-evacuation-route-and-shelter", "rain-k008-follow-on-site-evacuation"],
        evidenceKey: "decision",
      },
      {
        key: "publish",
        label: "发布游客行动指引",
        intent: "publish_visitor_guidance",
        guidance: "使用短句、优先级和明确入口，标注下次更新时间。",
        knowledgeIds: ["rain-k006-evacuation-route-and-shelter"],
        evidenceKey: "output",
      },
    ],
    primaryActionKey: "publish",
    event: {
      key: "route-blocked",
      triggerKind: "on_action",
      triggerKey: "capacity",
      studentBrief: "仿真北侧路线被积水阻断，东门安置点已满。请更新分人群指引与替代路线。",
      hiddenPayload: "仿真服务事件：南门通道可用，第二安置点已由管理方确认开放。",
      affectedAgentIds: ["agent-scene-director", "agent-platform"],
      candidateAgentIds: ["agent-scene-director", "agent-platform", "agent-fact-checker", "agent-chief"],
      teacherApprovalRequired: false,
    },
    agentSelection: {
      affectedAgentIds: ["agent-scene-director", "agent-platform"],
      candidateAgentIds: ["agent-scene-director", "agent-platform", "agent-fact-checker", "agent-chief"],
      selectWhen: "路线、容量或多端服务信息变化时选择能影响当前行动的智能体。",
      skipWhen: "候选只提供泛化安全提示、没有地点与责任依据时跳过。",
      maximumSelectedAgents: 2,
    },
    artifact: {
      label: "分人群游客疏导卡",
      format: "structured_form",
      completionCriteria: ["覆盖三类游客", "路线与安置容量经核验", "联系方式和更新时间完整"],
      finalCourseArtifact: false,
    },
    evidenceFocus: {
      source: "当前路线、安置点容量、管理方指令和服务入口。",
      decision: "对路线变化与容量建议作出补证或更新决定。",
      output: "园内、在途、计划出行三类游客的可执行指引。",
    },
    rubricFocus: {
      accuracy: "路线、容量与管理指令均为当前版本。",
      reasoning: "调用智能体与实际受影响集合一致。",
      deliverable: "每类游客都能知道现在做什么、去哪里、向谁查询。",
      transfer: "能迁移到大型活动疏散或交通中断服务。",
      failClosedWhen: "推荐已阻断路线或容量已满的安置点",
    },
    teacherGate: {
      label: "游客服务信息门",
      trigger: "before_publish",
      checks: ["分人群行动明确", "路线与容量为当前状态", "责任入口可用"],
      minimumEvidenceCount: 3,
      rejectReturnsToActionKey: "capacity",
    },
    reflection: {
      prompt: "如果通信不稳定，只能发布一条 80 字短信，哪些行动信息必须保留？",
      targetContext: "低带宽应急公共服务信息",
      comparisonDimensions: ["人群", "行动优先级", "地点", "更新时间"],
    },
  }),
  defineMigrationSection({
    sectionId: "rain-rumor-check",
    title: "灾情传言拆解与核查",
    typicalWorkTask: "核查灾情传言并发布克制的查证说明",
    objectives: [
      "把复合传言拆解为可核验主张",
      "为伤亡、失联、复开和积水等主张匹配权威来源",
      "避免重复传播未证实细节和旧画面",
    ],
    competencyRefs: ["谣言核查", "灾情伦理", "更正写作"],
    taskBrief: "仿真群聊出现‘景区已复开且有人被困’的语音和视频。请拆解主张、核验来源，发布不放大传言的查证说明。",
    sourceKnowledgeIds: [
      "rain-k002-warning-defense-guidance",
      "rain-k008-follow-on-site-evacuation",
      "rain-k009-rumor-verification-boundary",
    ],
    hiddenFacts: [
      {
        key: "fabricated-voice-note",
        summary: "仿真语音由匿名账号二次转述，没有现场身份或原始录音。",
        revealCondition: "学生把语音写入事实时间线时触发。",
      },
      {
        key: "old-flood-video",
        summary: "仿真视频来自另一地点的往年积水，画面标识与当前景区不符。",
        revealCondition: "学生执行画面核查时触发。",
      },
    ],
    actions: [
      {
        key: "claims",
        label: "拆解传言主张",
        intent: "decompose_rumor_claims",
        guidance: "把复开、被困、地点、时间和人数分别列为待核主张。",
        knowledgeIds: ["rain-k009-rumor-verification-boundary"],
        evidenceKey: "source",
      },
      {
        key: "crosscheck",
        label: "执行多源交叉核验",
        intent: "request_evidence",
        guidance: "核对主管部门通报、景区状态、现场管理口径和画面时空线索。",
        knowledgeIds: ["rain-k002-warning-defense-guidance", "rain-k008-follow-on-site-evacuation"],
        evidenceKey: "decision",
      },
      {
        key: "explain",
        label: "发布查证说明",
        intent: "publish_verification_note",
        guidance: "只重复核查所需最少传言内容，分列已证伪、待核与已确认信息。",
        knowledgeIds: ["rain-k009-rumor-verification-boundary"],
        evidenceKey: "output",
      },
    ],
    primaryActionKey: "explain",
    event: {
      key: "rumor-spike",
      triggerKind: "on_action",
      triggerKey: "crosscheck",
      studentBrief: "仿真旧视频转发量迅速上升。请优先发布核查说明，但不得声称未知的伤亡结论。",
      hiddenPayload: "仿真舆情事件：画面已证实非当前景区，人员情况仍待主管部门通报。",
      affectedAgentIds: ["agent-fact-checker", "agent-governance-content-safety"],
      candidateAgentIds: ["agent-fact-checker", "agent-governance-content-safety", "agent-scene-director", "agent-platform"],
      teacherApprovalRequired: false,
    },
    agentSelection: {
      affectedAgentIds: ["agent-fact-checker", "agent-governance-content-safety"],
      candidateAgentIds: ["agent-fact-checker", "agent-governance-content-safety", "agent-scene-director", "agent-platform"],
      selectWhen: "传言包含高风险人身信息、旧画面或传播升级时选择必要智能体。",
      skipWhen: "候选只复述传言、没有新增核验依据或会扩大伤害时跳过。",
      maximumSelectedAgents: 2,
    },
    artifact: {
      label: "灾情传言核查说明",
      format: "article",
      completionCriteria: ["主张逐项拆解", "画面和来源核验完整", "已证伪、待核、已确认分层"],
      finalCourseArtifact: false,
    },
    evidenceFocus: {
      source: "原始语音/视频线索、主管部门通报与画面时空核验记录。",
      decision: "对核查和内容安全建议作出有证据的决定。",
      output: "不放大传言且清楚标记不确定性的查证说明。",
    },
    rubricFocus: {
      accuracy: "旧画面、匿名转述和权威信息被明确分层。",
      reasoning: "能解释高风险传言下的智能体选择与跳过理由。",
      deliverable: "说明可快速纠正误导且不新增未经证实细节。",
      transfer: "能迁移到公共卫生或交通事故传言核查。",
      failClosedWhen: "发布未经权威确认的伤亡、失联或复开结论",
    },
    teacherGate: {
      label: "高风险查证发布门",
      trigger: "before_publish",
      checks: ["高风险主张有权威依据", "旧画面核验完成", "文案不放大传言"],
      minimumEvidenceCount: 3,
      rejectReturnsToActionKey: "crosscheck",
    },
    reflection: {
      prompt: "当暂时无法证伪一段高热度视频时，查证说明应如何表达不确定性？",
      targetContext: "高传播、低证据的突发传言",
      comparisonDimensions: ["主张风险", "证据强度", "传播速度", "表述边界"],
    },
  }),
  defineMigrationSection({
    sectionId: "rain-reopen-criteria",
    title: "复开条件与未开放区域说明",
    typicalWorkTask: "核验雨后风险评估并形成复开报道条件表",
    objectives: [
      "区分雨停、响应降级和景区复开决定",
      "核对风险评估、隐患处置和开放范围",
      "在不完整检查和复开压力下维持人工门",
    ],
    competencyRefs: ["复开信息核验", "风险评估解读", "人工审批"],
    taskBrief: "仿真降雨减弱后，建立复开条件表，逐项核验道路、边坡、设施、积水、人员和未开放区域，不得仅凭天气好转宣布复开。",
    sourceKnowledgeIds: [
      "rain-k010-reopen-risk-assessment",
      "rain-k011-partial-area-safety-controls",
    ],
    hiddenFacts: [
      {
        key: "inspection-incomplete",
        summary: "仿真降雨已经减弱，但边坡和栈道检查尚未完成。",
        revealCondition: "学生把雨停标为复开条件全部满足时触发。",
      },
      {
        key: "partial-areas-closed",
        summary: "仿真主游线通过检查，但涉水步道仍需关闭并设置警示。",
        revealCondition: "学生拟写全园复开标题时触发。",
      },
    ],
    actions: [
      {
        key: "criteria",
        label: "建立复开条件表",
        intent: "build_reopen_criteria",
        guidance: "列出风险评估、隐患处置、设施检查、开放范围和管理决定。",
        knowledgeIds: ["rain-k010-reopen-risk-assessment", "rain-k011-partial-area-safety-controls"],
        evidenceKey: "source",
      },
      {
        key: "inspect",
        label: "核验检查与开放范围",
        intent: "request_evidence",
        guidance: "分别记录已完成、未完成、未通过和有条件通过项目。",
        knowledgeIds: ["rain-k010-reopen-risk-assessment", "rain-k011-partial-area-safety-controls"],
        evidenceKey: "decision",
      },
      {
        key: "submit",
        label: "提交复开报道建议",
        intent: "submit_reopen_recommendation",
        guidance: "只有管理决定与关键检查齐全时建议发布，否则保持待复核。",
        knowledgeIds: ["rain-k011-partial-area-safety-controls"],
        evidenceKey: "output",
      },
    ],
    primaryActionKey: "submit",
    event: {
      key: "premature-reopen-pressure",
      triggerKind: "on_action",
      triggerKey: "inspect",
      studentBrief: "仿真运营方希望尽快宣布全园复开，但边坡检查尚未完成。请保持失败关闭并进入教师门。",
      hiddenPayload: "仿真治理事件：主游线可评估部分复开，边坡和涉水步道仍无通过记录。",
      affectedAgentIds: ["agent-chief", "agent-fact-checker"],
      candidateAgentIds: ["agent-chief", "agent-fact-checker", "agent-scene-director", "agent-evidence-assessor"],
      teacherApprovalRequired: true,
    },
    agentSelection: {
      affectedAgentIds: ["agent-chief", "agent-fact-checker"],
      candidateAgentIds: ["agent-chief", "agent-fact-checker", "agent-scene-director", "agent-evidence-assessor"],
      selectWhen: "检查证据、开放范围或运营压力影响复开结论时选择必要智能体。",
      skipWhen: "候选不能提供检查证据、范围判断或人工决策依据时跳过。",
      maximumSelectedAgents: 3,
    },
    artifact: {
      label: "复开条件与开放范围核验表",
      format: "evidence_bundle",
      completionCriteria: ["条件逐项有状态", "开放与未开放区域分列", "管理决定与教师门可追溯"],
      finalCourseArtifact: false,
    },
    evidenceFocus: {
      source: "风险评估、隐患处置、设施检查和管理决定记录。",
      decision: "对提前复开建议作出补证或拒绝决定。",
      output: "有状态、有范围、有审批的复开条件表。",
    },
    rubricFocus: {
      accuracy: "雨停、检查通过和管理决定未被混同。",
      reasoning: "对运营压力、证据缺口和人工门的处理清楚。",
      deliverable: "条件表能支持部分复开或继续关闭的明确报道。",
      transfer: "能迁移到设施检修后的分区恢复开放。",
      failClosedWhen: "关键检查未完成却建议全园复开",
    },
    teacherGate: {
      label: "景区复开报道门",
      trigger: "before_publish",
      checks: ["关键检查有结果", "开放范围准确", "管理决定与风险提示齐全"],
      minimumEvidenceCount: 3,
      rejectReturnsToActionKey: "inspect",
    },
    reflection: {
      prompt: "部分复开时，如何在标题和首屏同时表达开放区域与持续风险？",
      targetContext: "公共设施的分阶段恢复开放",
      comparisonDimensions: ["检查状态", "开放范围", "残余风险", "管理决定"],
    },
  }),
  defineMigrationSection({
    sectionId: "rain-multiplatform-continuous-update",
    title: "多平台连续更新与应急复盘",
    typicalWorkTask: "维护跨平台状态账本并完成应急报道复盘",
    objectives: [
      "让预警、闭园、疏导、核谣和复开版本保持一致",
      "发现缓存旧版与漏同步渠道",
      "评价协作必要性、证据覆盖和教师修订",
    ],
    competencyRefs: ["连续报道", "跨平台版本管理", "应急复盘"],
    taskBrief: "把整条仿真应急报道链整理为统一时间线，向客户端、短视频与社交平台同步最终状态，并提交证据、作品和协作复盘。",
    sourceKnowledgeIds: [
      "rain-k005-multichannel-warning-release",
      "rain-k007-timely-and-accurate-reporting",
      "rain-k011-partial-area-safety-controls",
      "rain-k012-warning-feedback-loop",
    ],
    hiddenFacts: [
      {
        key: "stale-cache",
        summary: "仿真搜索缓存仍显示旧闭园标题，一个合作账号也遗漏复开更正。",
        revealCondition: "学生标记全渠道同步完成时触发。",
      },
      {
        key: "partial-reopen-final",
        summary: "仿真最终状态为主游线复开、涉水步道继续关闭，并非全园恢复。",
        revealCondition: "学生生成最终摘要时触发。",
      },
    ],
    actions: [
      {
        key: "timeline",
        label: "冻结权威状态时间线",
        intent: "freeze_emergency_timeline",
        guidance: "连接预警、闭园、疏导、核谣、检查和复开决定及其证据。",
        knowledgeIds: ["rain-k007-timely-and-accurate-reporting", "rain-k012-warning-feedback-loop"],
        evidenceKey: "source",
      },
      {
        key: "sync",
        label: "核对全渠道同步",
        intent: "decide_agent_contribution",
        guidance: "逐端检查标题、状态、开放范围、服务入口和旧版更正关系。",
        knowledgeIds: ["rain-k005-multichannel-warning-release", "rain-k011-partial-area-safety-controls"],
        evidenceKey: "decision",
      },
      {
        key: "review",
        label: "提交最终作品与复盘",
        intent: "submit_emergency_review",
        guidance: "整合作品、证据、协作选择、教师门、漏同步修复和迁移反思。",
        knowledgeIds: ["rain-k012-warning-feedback-loop"],
        evidenceKey: "output",
      },
    ],
    primaryActionKey: "review",
    event: {
      key: "reopen-with-stale-channel",
      triggerKind: "on_action",
      triggerKey: "sync",
      studentBrief: "仿真主游线部分复开，但缓存与合作账号仍显示全园闭园。请同步更正并保留未开放区域。",
      hiddenPayload: "仿真最终事件：部分复开已确认，旧缓存和合作账号构成两个待修复渠道。",
      affectedAgentIds: ["agent-platform", "agent-evidence-assessor"],
      candidateAgentIds: ["agent-platform", "agent-governance-platform-rule", "agent-evidence-assessor", "agent-learning"],
      teacherApprovalRequired: true,
    },
    agentSelection: {
      affectedAgentIds: ["agent-platform", "agent-evidence-assessor"],
      candidateAgentIds: ["agent-platform", "agent-governance-platform-rule", "agent-evidence-assessor", "agent-learning"],
      selectWhen: "渠道状态、证据覆盖或学习复盘出现缺口时选择相应智能体。",
      skipWhen: "候选只输出技术日志、不能改变同步动作或复盘结论时跳过。",
      maximumSelectedAgents: 3,
    },
    artifact: {
      label: "景区暴雨应急连续报道与证据复盘包",
      format: "evidence_bundle",
      completionCriteria: ["权威时间线完整", "全部渠道状态已核", "作品、证据、协作与教师修订可追溯"],
      finalCourseArtifact: true,
    },
    evidenceFocus: {
      source: "全链路事件、管理决定、各端版本和状态回执。",
      decision: "对平台同步、证据评价和学习建议作出有依据的决定。",
      output: "最终连续报道、渠道更正、证据包和应急复盘。",
    },
    rubricFocus: {
      accuracy: "最终开放范围与每个平台状态一致，旧版关系可追溯。",
      reasoning: "协作必要性、无关调用和教师修订均有证据。",
      deliverable: "复盘包可支撑 8—12 分钟完整演示和下一次演练。",
      transfer: "能迁移到台风、火情或公共设施故障连续报道。",
      failClosedWhen: "仍有已知渠道显示错误状态却宣称全链路完成",
    },
    teacherGate: {
      label: "应急报道最终验收门",
      trigger: "before_section_complete",
      checks: ["权威时间线无冲突", "渠道同步有回执", "部分复开范围表达准确"],
      minimumEvidenceCount: 3,
      rejectReturnsToActionKey: "sync",
    },
    reflection: {
      prompt: "若下一次事件没有明确复开时点，应如何设计持续更新的结束条件？",
      targetContext: "状态长期不确定的公共安全连续报道",
      comparisonDimensions: ["权威状态", "渠道一致性", "结束条件", "证据与复盘"],
    },
  }),
] as const;

export const rainEmergencyCourseRelease = createMigrationCourse({
  courseId: "course-scenic-rain-emergency-reporting",
  releaseId: "release-course-scenic-rain-emergency-reporting-2.0.0-content.1",
  version: "2.0.0-content.1",
  title: "景区暴雨闭园与复开应急报道",
  summary: "从气象预警到闭园、游客疏导、传言核查、复开条件和多平台连续更新，训练记者维护权威状态时间线、证据链和教师人工门；现场细节均为教学仿真。",
  durationMinutes: 180,
  courseOutcomes: [
    "能核验预警、管理决定和景区开放状态的版本关系",
    "能发布可执行的闭园、疏导、核谣和复开信息",
    "能在高风险事实与证据缺口下保持失败关闭",
    "能维护多平台连续报道并完成协作与证据复盘",
  ],
  sections,
  knowledgeRecords: rainEmergencyKnowledgeRecords,
});

export const rainEmergencySectionCount = rainEmergencyCourseRelease.sections.length;
