import { createMigrationCourse } from "./migration-course-builder.js";
import { defineMigrationSection } from "./migration-section-factory.js";
import { villageSuperKnowledgeRecords } from "./migration-knowledge.js";

const sections = [
  defineMigrationSection({
    sectionId: "village-super-platform-map",
    title: "平台受众与报道任务地图",
    typicalWorkTask: "分析多平台受众并拆解同一报道任务",
    objectives: [
      "区分客户端、短视频、直播与社交平台的受众需求",
      "为同一真实事实设定可核验的平台目标",
      "登记跨账号协作、素材流向与发布责任",
    ],
    competencyRefs: ["媒体用户分析", "传播策划", "协同生产管理"],
    taskBrief: "你是村超专题记者。请依据公开案例建立平台—受众—内容目标地图，保留同一事实底座，并明确每个平台下一步需要采集的证据。",
    sourceKnowledgeIds: [
      "village-k001-platform-goal-and-audience",
      "village-k004-tag-matrix",
      "village-k005-collaborative-distribution-matrix",
      "village-k007-official-multiplatform-showcase",
    ],
    hiddenFacts: [
      {
        key: "analytics-window-mismatch",
        summary: "两份平台数据使用了不同统计时间窗，不能直接比较播放量。",
        revealCondition: "学生提交第一版平台地图后，由事实核查建议提示统计口径冲突。",
      },
      {
        key: "sponsor-copy-pressure",
        summary: "仿真合作方希望四个平台复制同一宣传口号，未说明受众差异。",
        revealCondition: "学生查看协作账号分工时触发。",
      },
    ],
    actions: [
      {
        key: "map",
        label: "建立平台任务地图",
        intent: "map_platform_audience",
        guidance: "逐个平台填写受众、公共价值、内容形态、成功指标与责任账号。",
        knowledgeIds: ["village-k001-platform-goal-and-audience", "village-k007-official-multiplatform-showcase"],
        evidenceKey: "source",
      },
      {
        key: "verify",
        label: "核对指标与协作边界",
        intent: "request_evidence",
        guidance: "核对数据时间窗、标签用途、素材来源和每个账号的发布责任。",
        knowledgeIds: ["village-k004-tag-matrix", "village-k005-collaborative-distribution-matrix"],
        evidenceKey: "decision",
      },
      {
        key: "freeze",
        label: "冻结平台地图版本",
        intent: "submit_platform_map",
        guidance: "记录已采纳、请求补证或拒绝的智能体建议，再提交可追溯版本。",
        knowledgeIds: ["village-k001-platform-goal-and-audience"],
        evidenceKey: "output",
      },
    ],
    primaryActionKey: "freeze",
    event: {
      key: "live-window-change",
      triggerKind: "on_action",
      triggerKey: "verify",
      studentBrief: "直播平台将仿真首发窗口提前 20 分钟，请重新判断任务优先级，不得改写已核验事实。",
      hiddenPayload: "仿真调度变更：短视频素材仍按原窗口交付，直播口播需先完成来源核验。",
      affectedAgentIds: ["agent-platform", "agent-chief"],
      candidateAgentIds: ["agent-platform", "agent-chief", "agent-fact-checker"],
      teacherApprovalRequired: false,
    },
    agentSelection: {
      affectedAgentIds: ["agent-platform", "agent-chief"],
      candidateAgentIds: ["agent-platform", "agent-chief", "agent-fact-checker"],
      selectWhen: "出现平台窗口、受众目标或指标口径冲突时，仅选择能够解释当前冲突的智能体。",
      skipWhen: "事实、平台和责任边界已由公开来源与学生记录覆盖时跳过其余候选。",
      maximumSelectedAgents: 2,
    },
    artifact: {
      label: "村超多平台任务地图",
      format: "structured_form",
      completionCriteria: ["至少覆盖三类平台", "每个平台含受众、目标、事实底座和证据缺口", "标记数据口径与发布责任"],
      finalCourseArtifact: false,
    },
    evidenceFocus: {
      source: "带定位的官方案例、平台数据口径与账号责任记录。",
      decision: "对平台智能体建议作出采纳、补证或拒绝决定并写明证据。",
      output: "含版本号、统计时间窗和责任人的平台任务地图。",
    },
    rubricFocus: {
      accuracy: "平台目标与受众结论均可回指公开来源，统计口径没有混用。",
      reasoning: "能解释为何选择或跳过平台、主编与核查智能体。",
      deliverable: "地图可直接指导后续选题、采集和分发。",
      transfer: "能将方法迁移到另一项县域公共文化活动。",
      failClosedWhen: "把不同统计时间窗的数据直接排序，或把仿真合作要求写成真实事实",
    },
    teacherGate: {
      label: "平台任务地图核准",
      trigger: "before_section_complete",
      checks: ["事实底座一致", "平台目标可量化", "责任与证据缺口明确"],
      minimumEvidenceCount: 3,
      rejectReturnsToActionKey: "verify",
    },
    reflection: {
      prompt: "若同一赛事改为社区健康主题，平台目标与核验指标应如何变化？",
      targetContext: "县域公共服务活动的多平台传播",
      comparisonDimensions: ["受众需求", "公共价值", "平台指标", "协作责任"],
    },
  }),
  defineMigrationSection({
    sectionId: "village-super-story-angle",
    title: "社区本位的专题角度",
    typicalWorkTask: "从赛事热点中形成有公共价值的报道角度",
    objectives: [
      "区分竞技、文化、生活、情感与文旅叙事支柱",
      "以社区主体和可核验问题构造选题",
      "识别宣传诉求与新闻判断之间的边界",
    ],
    competencyRefs: ["新闻选题策划", "社区叙事", "编辑判断"],
    taskBrief: "比较三个候选角度，选择一个能够呈现社区主体、赛事现场与地方文化关系的专题方向，并列出反证与待访对象。",
    sourceKnowledgeIds: [
      "village-k002-five-story-pillars",
      "village-k009-community-centered-story",
      "village-k011-audiovisual-production-workflow",
    ],
    hiddenFacts: [
      {
        key: "tourism-only-request",
        summary: "仿真合作方要求删去社区治理问题，只保留旅游宣传角度。",
        revealCondition: "学生选定社区本位角度后触发主编建议。",
      },
      {
        key: "viral-clip-unverified",
        summary: "一段高热度欢呼视频无法确认拍摄日期与比赛场次。",
        revealCondition: "学生把热度作为选题依据时触发核查建议。",
      },
    ],
    actions: [
      {
        key: "compare",
        label: "比较候选角度",
        intent: "compare_story_angles",
        guidance: "按公共价值、社区主体、可视化程度和可核验性比较三个角度。",
        knowledgeIds: ["village-k002-five-story-pillars", "village-k009-community-centered-story"],
        evidenceKey: "source",
      },
      {
        key: "challenge",
        label: "提出反证与补访",
        intent: "request_evidence",
        guidance: "为首选角度列出至少两项可能推翻判断的证据和对应采访对象。",
        knowledgeIds: ["village-k011-audiovisual-production-workflow"],
        evidenceKey: "decision",
      },
      {
        key: "pitch",
        label: "提交专题选题卡",
        intent: "submit_story_pitch",
        guidance: "写清核心问题、事实边界、人物类型、镜头机会和不采用的角度。",
        knowledgeIds: ["village-k009-community-centered-story"],
        evidenceKey: "output",
      },
    ],
    primaryActionKey: "pitch",
    event: {
      key: "community-voice-missing",
      triggerKind: "on_action",
      triggerKey: "pitch",
      studentBrief: "编辑发现首版选题卡没有社区参与者的一手声音，请决定补访还是说明拒绝理由。",
      hiddenPayload: "仿真审稿：现有素材只有赛事组织方口径，社区主体证据为空。",
      affectedAgentIds: ["agent-chief", "agent-interviewee"],
      candidateAgentIds: ["agent-chief", "agent-interviewee", "agent-fact-checker"],
      teacherApprovalRequired: false,
    },
    agentSelection: {
      affectedAgentIds: ["agent-chief", "agent-interviewee"],
      candidateAgentIds: ["agent-chief", "agent-interviewee", "agent-fact-checker"],
      selectWhen: "角度缺少主体声音、存在宣传替代新闻或关键素材无法核实时选择对应智能体。",
      skipWhen: "建议无法增加角度的公共价值、可核验性或主体完整性时跳过。",
      maximumSelectedAgents: 2,
    },
    artifact: {
      label: "社区本位专题选题卡",
      format: "structured_form",
      completionCriteria: ["一句话核心问题", "至少两类社区主体", "反证、补访与不采用角度齐全"],
      finalCourseArtifact: false,
    },
    evidenceFocus: {
      source: "五类叙事支柱、社区主体和选题依据的来源定位。",
      decision: "对缺失主体声音的建议及补访范围作出明确决定。",
      output: "包含问题、主体、反证、镜头与采访计划的选题卡。",
    },
    rubricFocus: {
      accuracy: "选题依据来自已登记案例，不使用无法确认场次的热视频作事实。",
      reasoning: "能够解释选中角度与放弃宣传化角度的原因。",
      deliverable: "选题卡足以指导记者进入采访与分镜阶段。",
      transfer: "能比较赛事报道与非赛事社区报道的主体差异。",
      failClosedWhen: "核心角度依赖无法核验的视频，或将仿真合作方诉求写成真实案例事实",
    },
    teacherGate: {
      label: "专题角度审题",
      trigger: "before_section_complete",
      checks: ["社区主体不被工具化", "核心问题可核验", "反证与补访对象明确"],
      minimumEvidenceCount: 3,
      rejectReturnsToActionKey: "challenge",
    },
    reflection: {
      prompt: "若热点从足球转为村晚，哪些主体和反证仍然适用，哪些必须重建？",
      targetContext: "地方文化活动专题选题",
      comparisonDimensions: ["主体", "事实问题", "视听机会", "宣传边界"],
    },
  }),
  defineMigrationSection({
    sectionId: "village-super-storyboard",
    title: "视听脚本与分镜证据链",
    typicalWorkTask: "把专题角度转化为可采集、可核验的视听脚本",
    objectives: [
      "把事实、采访、画面和声音组织成分镜",
      "为每个镜头登记来源与使用权状态",
      "在突发素材变更时维持叙事和证据连续性",
    ],
    competencyRefs: ["视听脚本创作", "素材管理", "现场采编"],
    taskBrief: "依据已核准选题设计 90 秒短视频分镜。每个镜头必须说明叙事作用、采集方式、来源核验和备选方案。",
    sourceKnowledgeIds: [
      "village-k002-five-story-pillars",
      "village-k008-live-interview-and-short-video",
      "village-k009-community-centered-story",
      "village-k011-audiovisual-production-workflow",
    ],
    hiddenFacts: [
      {
        key: "old-highlight-clip",
        summary: "素材包中的高光镜头来自上一届仿真赛事，服装相似但时间不符。",
        revealCondition: "学生在分镜中采用高光镜头时触发。",
      },
      {
        key: "music-rights-missing",
        summary: "仿真表演音频只有现场录音，没有获得后续平台传播授权。",
        revealCondition: "学生完成声音设计后触发版权建议。",
      },
    ],
    actions: [
      {
        key: "beats",
        label: "搭建叙事节拍",
        intent: "draft_storyboard",
        guidance: "用开场、冲突、主体声音、事实解释和收束五个节拍安排镜头。",
        knowledgeIds: ["village-k002-five-story-pillars", "village-k009-community-centered-story"],
        evidenceKey: "source",
      },
      {
        key: "rights",
        label: "核验镜头与声音",
        intent: "request_evidence",
        guidance: "逐项核验日期、场次、人物同意、音乐授权和替代素材。",
        knowledgeIds: ["village-k008-live-interview-and-short-video", "village-k011-audiovisual-production-workflow"],
        evidenceKey: "decision",
      },
      {
        key: "freeze",
        label: "冻结拍摄分镜",
        intent: "submit_storyboard",
        guidance: "保留删改原因、待采证据和应急替代镜头，提交拍摄版。",
        knowledgeIds: ["village-k011-audiovisual-production-workflow"],
        evidenceKey: "output",
      },
    ],
    primaryActionKey: "freeze",
    event: {
      key: "replacement-clip",
      triggerKind: "on_action",
      triggerKey: "rights",
      studentBrief: "现场传来一段当天替代镜头，但只有拍摄者昵称。你需要先补证还是调整分镜？",
      hiddenPayload: "仿真素材变更：文件时间与当天一致，人物授权和拍摄者身份尚未确认。",
      affectedAgentIds: ["agent-copyright", "agent-fact-checker"],
      candidateAgentIds: ["agent-copyright", "agent-fact-checker", "agent-governance-content-safety", "agent-chief"],
      teacherApprovalRequired: true,
    },
    agentSelection: {
      affectedAgentIds: ["agent-copyright", "agent-fact-checker"],
      candidateAgentIds: ["agent-copyright", "agent-fact-checker", "agent-governance-content-safety", "agent-chief"],
      selectWhen: "素材日期、人物同意、音乐授权或叙事完整性出现缺口时选择必要智能体。",
      skipWhen: "候选建议只重复已完成核验或与当前分镜无关时跳过。",
      maximumSelectedAgents: 3,
    },
    artifact: {
      label: "90 秒专题拍摄分镜",
      format: "script",
      completionCriteria: ["五个叙事节拍完整", "每镜含事实与权利状态", "存在可执行的替代镜头"],
      finalCourseArtifact: false,
    },
    evidenceFocus: {
      source: "镜头日期、场次、采访对象和公开案例的核验表。",
      decision: "对替代素材及版权建议作出采纳、补证或拒绝决定。",
      output: "含镜号、时长、画面、声音、来源、权利状态和备选的分镜。",
    },
    rubricFocus: {
      accuracy: "每个事实性镜头可回指来源，旧届素材未伪装成当届现场。",
      reasoning: "能够按当前缺口选择核查、版权或内容安全智能体。",
      deliverable: "分镜可由现场记者按序采集并在素材缺失时切换。",
      transfer: "能把证据链方法迁移到直播切片或图文图集。",
      failClosedWhen: "使用日期不符或授权不明的素材作为必需镜头",
    },
    teacherGate: {
      label: "拍摄前素材与权利门",
      trigger: "before_publish",
      checks: ["镜头日期与场次已核", "人物与音乐权利状态明确", "无证据镜头有替代方案"],
      minimumEvidenceCount: 3,
      rejectReturnsToActionKey: "rights",
    },
    reflection: {
      prompt: "当短视频改为三分钟人物报道时，哪些证据字段可以复用，哪些需要扩展？",
      targetContext: "人物专题与直播切片制作",
      comparisonDimensions: ["时长结构", "素材来源", "权利状态", "备选镜头"],
    },
  }),
  defineMigrationSection({
    sectionId: "village-super-live-update",
    title: "直播快讯与时间线核验",
    typicalWorkTask: "在连续赛事变化中发布带时间戳的直播快讯",
    objectives: [
      "维护比分、事件、来源和更正状态时间线",
      "区分现场观察、官方确认与网络线索",
      "在速度压力下完成必要核验与版本更新",
    ],
    competencyRefs: ["直播采编", "事实核查", "版本管理"],
    taskBrief: "接管 15 分钟仿真直播窗口，建立事件账本并发布三条快讯。每条快讯必须标记时间、来源等级和下次核验点。",
    sourceKnowledgeIds: [
      "village-k003-high-frequency-production",
      "village-k005-collaborative-distribution-matrix",
      "village-k008-live-interview-and-short-video",
      "village-k012-live-and-data-job-loop",
    ],
    hiddenFacts: [
      {
        key: "score-rumor",
        summary: "仿真群聊把一次射门误写为进球，官方记分板尚未变化。",
        revealCondition: "学生准备第二条比分快讯时触发。",
      },
      {
        key: "late-correction",
        summary: "仿真现场播报随后更正球员号码，需要回溯已发版本。",
        revealCondition: "学生提交第三条快讯后触发。",
      },
    ],
    actions: [
      {
        key: "ledger",
        label: "开启直播事件账本",
        intent: "open_live_ledger",
        guidance: "登记虚拟时间、观察者、官方信号、待核项和已发版本。",
        knowledgeIds: ["village-k003-high-frequency-production", "village-k012-live-and-data-job-loop"],
        evidenceKey: "source",
      },
      {
        key: "verify",
        label: "核验比分与人物",
        intent: "request_evidence",
        guidance: "优先比对官方记分板、现场观察和第二独立来源，不用群聊替代确认。",
        knowledgeIds: ["village-k005-collaborative-distribution-matrix"],
        evidenceKey: "decision",
      },
      {
        key: "publish",
        label: "发布并回写快讯",
        intent: "publish_live_update",
        guidance: "发布当前已核事实，保留不确定项并把更正同步到事件账本。",
        knowledgeIds: ["village-k003-high-frequency-production", "village-k008-live-interview-and-short-video"],
        evidenceKey: "output",
      },
    ],
    primaryActionKey: "publish",
    event: {
      key: "score-change",
      triggerKind: "on_action",
      triggerKey: "verify",
      studentBrief: "仿真官方记分板确认比分变化，但群聊仍传播旧说法。请发布当前版本并说明更正关系。",
      hiddenPayload: "仿真世界事件：新比分已获官方信号确认，球员号码仍待复核。",
      affectedAgentIds: ["agent-fact-checker", "agent-platform"],
      candidateAgentIds: ["agent-fact-checker", "agent-platform", "agent-scene-director", "agent-chief"],
      teacherApprovalRequired: false,
    },
    agentSelection: {
      affectedAgentIds: ["agent-fact-checker", "agent-platform"],
      candidateAgentIds: ["agent-fact-checker", "agent-platform", "agent-scene-director", "agent-chief"],
      selectWhen: "比分、人物、时间或已发版本发生冲突时选择核查和分发智能体。",
      skipWhen: "候选智能体无法提供新增来源、版本影响或行动建议时跳过。",
      maximumSelectedAgents: 2,
    },
    artifact: {
      label: "直播快讯时间线",
      format: "structured_form",
      completionCriteria: ["至少三条带时间戳快讯", "来源等级与待核项完整", "更正能回指旧版本"],
      finalCourseArtifact: false,
    },
    evidenceFocus: {
      source: "官方信号、现场观察、群聊线索及其时间戳对照。",
      decision: "对比分核查建议作出决定，并说明速度与准确性的取舍。",
      output: "三条快讯、事件账本和可追溯的更正关系。",
    },
    rubricFocus: {
      accuracy: "比分、人物与时间均有相应来源等级，线索未写成已确认事实。",
      reasoning: "只在当前冲突需要时调用核查、分发或导演智能体。",
      deliverable: "快讯短、准、可更新，时间线能支持下一班记者接手。",
      transfer: "能迁移到突发发布会或文旅活动直播更新。",
      failClosedWhen: "把群聊比分直接发布为官方结果，或更正不回指旧版本",
    },
    teacherGate: {
      label: "直播快讯发布门",
      trigger: "before_publish",
      checks: ["官方确认与线索分层", "版本时间戳完整", "更正关系清楚"],
      minimumEvidenceCount: 3,
      rejectReturnsToActionKey: "verify",
    },
    reflection: {
      prompt: "若现场没有记分板，直播快讯的最低双重核验组合应如何调整？",
      targetContext: "基层活动与突发事件的连续快讯",
      comparisonDimensions: ["来源等级", "时间压力", "版本更正", "交接字段"],
    },
  }),
  defineMigrationSection({
    sectionId: "village-super-platform-adaptation",
    title: "同一事实底座的多端适配",
    typicalWorkTask: "把已核稿件改编为多平台视听版本",
    objectives: [
      "保持多端版本的核心事实一致",
      "按平台受众调整标题、节奏、标签与字幕",
      "识别算法建议、平台规则和版权边界",
    ],
    competencyRefs: ["平台适配", "视听编辑", "平台合规"],
    taskBrief: "把同一条村超报道改编为客户端导语、短视频口播和直播预告，建立字段级事实对照表并解释差异。",
    sourceKnowledgeIds: [
      "village-k004-tag-matrix",
      "village-k006-feedback-and-algorithm-boundary",
      "village-k007-official-multiplatform-showcase",
      "village-k010-cross-platform-streaming",
    ],
    hiddenFacts: [
      {
        key: "source-label-deletion",
        summary: "仿真平台建议为提高完播率删除画面中的来源说明和无障碍字幕。",
        revealCondition: "学生生成短视频版本后触发。",
      },
      {
        key: "logo-rights-gap",
        summary: "仿真直播预告模板含未登记授权的商业标识。",
        revealCondition: "学生执行平台预检时触发。",
      },
    ],
    actions: [
      {
        key: "variants",
        label: "生成三端版本",
        intent: "adapt_platform_versions",
        guidance: "先冻结事实字段，再分别调整标题、节奏、标签、字幕和行动提示。",
        knowledgeIds: ["village-k004-tag-matrix", "village-k007-official-multiplatform-showcase"],
        evidenceKey: "source",
      },
      {
        key: "preflight",
        label: "检查规则与权利",
        intent: "request_evidence",
        guidance: "检查来源说明、字幕、标识授权、平台声明和算法建议的适用边界。",
        knowledgeIds: ["village-k006-feedback-and-algorithm-boundary", "village-k010-cross-platform-streaming"],
        evidenceKey: "decision",
      },
      {
        key: "approve",
        label: "提交多端发布包",
        intent: "submit_platform_package",
        guidance: "保留字段差异表与建议决定，确保每端都能回指同一核验事实。",
        knowledgeIds: ["village-k010-cross-platform-streaming"],
        evidenceKey: "output",
      },
    ],
    primaryActionKey: "approve",
    event: {
      key: "rule-conflict",
      triggerKind: "on_action",
      triggerKey: "preflight",
      studentBrief: "仿真平台的时长建议与来源说明、字幕完整性冲突。请决定压缩其他内容、补证或拒绝建议。",
      hiddenPayload: "仿真规则冲突：平台仅建议时长，不要求删除来源与无障碍信息。",
      affectedAgentIds: ["agent-platform", "agent-governance-platform-rule"],
      candidateAgentIds: ["agent-platform", "agent-governance-platform-rule", "agent-copyright", "agent-chief"],
      teacherApprovalRequired: false,
    },
    agentSelection: {
      affectedAgentIds: ["agent-platform", "agent-governance-platform-rule"],
      candidateAgentIds: ["agent-platform", "agent-governance-platform-rule", "agent-copyright", "agent-chief"],
      selectWhen: "平台格式、规则、标识权利或核心事实一致性发生冲突时选择必要智能体。",
      skipWhen: "建议只追求流量且会削弱来源、字幕或事实完整性时跳过并记录理由。",
      maximumSelectedAgents: 3,
    },
    artifact: {
      label: "客户端、短视频与直播三端发布包",
      format: "script",
      completionCriteria: ["三端核心事实一致", "差异表覆盖标题、节奏、标签与字幕", "权利与规则预检完成"],
      finalCourseArtifact: false,
    },
    evidenceFocus: {
      source: "三端事实字段、标签依据和平台公开案例对照。",
      decision: "对时长、字幕、来源和标识建议作出有依据的决定。",
      output: "三端脚本、字段差异表与发布预检结果。",
    },
    rubricFocus: {
      accuracy: "三端人物、时间、场次与事实结论一致且可回指来源。",
      reasoning: "平台规则、版权和算法建议的选择理由清晰。",
      deliverable: "各端版本符合对应使用场景且保留必要来源和字幕。",
      transfer: "能迁移到图文、音频或长视频版本。",
      failClosedWhen: "为适配平台删除关键来源、无障碍字幕或使用未授权标识",
    },
    teacherGate: {
      label: "多端发布一致性门",
      trigger: "before_publish",
      checks: ["事实字段一致", "平台差异有目的", "来源、字幕与权利信息保留"],
      minimumEvidenceCount: 3,
      rejectReturnsToActionKey: "preflight",
    },
    reflection: {
      prompt: "如果新增音频播客版本，哪些事实字段不可改变，哪些表达可以重构？",
      targetContext: "同一报道的跨媒介生产",
      comparisonDimensions: ["事实底座", "受众", "媒介语法", "合规字段"],
    },
  }),
  defineMigrationSection({
    sectionId: "village-super-data-review",
    title: "传播数据与作品质量复盘",
    typicalWorkTask: "综合数据、证据和编辑质量复盘多端作品",
    objectives: [
      "区分触达、观看、互动、转化与内容质量指标",
      "识别异常流量和统计口径差异",
      "提出下一轮可验证的编辑改进",
    ],
    competencyRefs: ["传播数据分析", "作品评价", "迭代改进"],
    taskBrief: "汇总三端仿真数据和作品证据，解释差异而非只排行流量，并提交一份含下一轮验证假设的课程终稿复盘。",
    sourceKnowledgeIds: [
      "village-k006-feedback-and-algorithm-boundary",
      "village-k010-cross-platform-streaming",
      "village-k012-live-and-data-job-loop",
    ],
    hiddenFacts: [
      {
        key: "single-repost-spike",
        summary: "仿真短视频的流量峰值来自单个大号转发，不能代表稳定受众增长。",
        revealCondition: "学生按播放量给版本排序时触发。",
      },
      {
        key: "low-completion",
        summary: "仿真直播回放触达高但前 30 秒流失明显，评论中的文化信息需求增加。",
        revealCondition: "学生查看留存与评论样本后触发。",
      },
    ],
    actions: [
      {
        key: "align",
        label: "对齐数据口径",
        intent: "align_metrics",
        guidance: "记录统计窗口、分母、去重方式和异常来源，再比较触达、留存与互动。",
        knowledgeIds: ["village-k006-feedback-and-algorithm-boundary", "village-k012-live-and-data-job-loop"],
        evidenceKey: "source",
      },
      {
        key: "evaluate",
        label: "评价协作与作品",
        intent: "decide_agent_contribution",
        guidance: "比较平台建议、事实核查和学生决定对质量的实际贡献，标记无关调用。",
        knowledgeIds: ["village-k010-cross-platform-streaming"],
        evidenceKey: "decision",
      },
      {
        key: "submit",
        label: "提交课程终稿复盘",
        intent: "submit_course_review",
        guidance: "整合作品、证据、数据口径、错误更正和下一轮可检验假设。",
        knowledgeIds: ["village-k006-feedback-and-algorithm-boundary", "village-k012-live-and-data-job-loop"],
        evidenceKey: "output",
      },
    ],
    primaryActionKey: "submit",
    event: {
      key: "anomaly-spike",
      triggerKind: "on_action",
      triggerKey: "align",
      studentBrief: "仿真数据出现单次外部转发峰值。请决定是否调整结论，并说明哪些指标仍可比较。",
      hiddenPayload: "仿真分析事件：峰值来自单一外部账号，完播率与后续回访没有同步增长。",
      affectedAgentIds: ["agent-platform", "agent-evidence-assessor"],
      candidateAgentIds: ["agent-platform", "agent-evidence-assessor", "agent-work-quality-assessor", "agent-learning"],
      teacherApprovalRequired: true,
    },
    agentSelection: {
      affectedAgentIds: ["agent-platform", "agent-evidence-assessor"],
      candidateAgentIds: ["agent-platform", "agent-evidence-assessor", "agent-work-quality-assessor", "agent-learning"],
      selectWhen: "数据异常、证据覆盖或作品质量结论需要解释时选择相应评价智能体。",
      skipWhen: "候选输出只复述分数、没有新增证据或不能影响改进决策时跳过。",
      maximumSelectedAgents: 3,
    },
    artifact: {
      label: "村超多平台报道作品与数据复盘包",
      format: "evidence_bundle",
      completionCriteria: ["包含最终三端作品", "数据口径与异常说明完整", "至少提出两项可验证改进"],
      finalCourseArtifact: true,
    },
    evidenceFocus: {
      source: "三端统计口径、异常来源、作品版本与评论样本。",
      decision: "对评价智能体建议作出决定并指出真实贡献或无关调用。",
      output: "作品、证据、数据解释、更正和迭代假设组成的复盘包。",
    },
    rubricFocus: {
      accuracy: "指标口径可比，异常流量没有被误写成稳定效果。",
      reasoning: "协作必要性、证据覆盖和学生修订的因果关系清晰。",
      deliverable: "终稿复盘能指导下一轮平台与内容实验。",
      transfer: "能迁移到其他县域活动的多平台效果评估。",
      failClosedWhen: "用单一播放量宣称课程或智能体架构优越，或忽略统计口径",
    },
    teacherGate: {
      label: "课程终稿与数据解释门",
      trigger: "before_section_complete",
      checks: ["作品证据齐全", "数据结论不越界", "改进假设可验证"],
      minimumEvidenceCount: 3,
      rejectReturnsToActionKey: "align",
    },
    reflection: {
      prompt: "如果下一门课程没有播放量，只能获得作品证据与教师反馈，应如何评价效果？",
      targetContext: "低数据量公共文化报道的质量评估",
      comparisonDimensions: ["数据可得性", "证据质量", "协作必要性", "改进可验证性"],
    },
  }),
] as const;

export const villageSuperCourseRelease = createMigrationCourse({
  courseId: "course-village-super-multiplatform",
  releaseId: "release-course-village-super-multiplatform-2.0.0-content.1",
  version: "2.0.0-content.1",
  title: "贵州村超多平台视听报道",
  summary: "以权威公开案例为事实底座，训练记者完成平台分析、社区本位选题、视听分镜、直播快讯、多端适配和数据复盘；所有现场冲突均为不映射真实个人的仿真情境。",
  durationMinutes: 180,
  courseOutcomes: [
    "能从同一事实底座策划多平台视听报道",
    "能在直播压力下维护来源、时间线与更正关系",
    "能对智能体建议作出采纳、补证或拒绝决定",
    "能综合传播数据、作品证据和编辑质量形成迭代方案",
  ],
  sections,
  knowledgeRecords: villageSuperKnowledgeRecords,
});

export const villageSuperSectionCount = villageSuperCourseRelease.sections.length;
