import { createCourseContentRelease } from "./canonical.js";
import {
  CourseContentSchemaVersion,
  CourseReleaseTargetSchemaVersion,
  type CourseSection,
} from "./types.js";
import { xunpuKnowledgeRecords } from "./xunpu-knowledge.js";

function adviceDecisionPolicy(): CourseSection["adviceDecisionPolicy"] {
  return {
    allowedDecisions: ["accept", "request_more_evidence", "reject"],
    rationaleRequiredOnReject: true,
    onlyOneVisibleSuggestionAtATime: true,
  };
}

const sections = [
  {
    sectionId: "xunpu-topic-brief",
    order: 1,
    title: "从热搜到选题：明确报道价值",
    typicalWorkTask: "从地方文化传播需求形成选题简报和受众假设",
    objectives: [
      {
        objectiveId: "xunpu-topic-objective-news-value",
        description: "区分公共报道价值、文旅宣传诉求与平台热度。",
        competencyRef: "media-reporting/topic-judgement",
      },
      {
        objectiveId: "xunpu-topic-objective-audience",
        description: "形成可验证的核心受众假设与信息需要。",
        competencyRef: "all-media/audience-analysis",
      },
      {
        objectiveId: "xunpu-topic-objective-boundary",
        description: "写明案例数据和非遗身份的事实边界。",
        competencyRef: "media-reporting/source-boundary",
      },
    ],
    taskBrief: "你是融媒体采编岗记者。阅读官方案例卡和职业任务卡，用一句话提出核心选题，并说明服务谁、解决什么信息缺口、哪些说法暂不能写进标题。",
    publicSourceKnowledgeIds: [
      "xunpu-k001-heritage-status-boundary",
      "xunpu-k003-cultural-respect",
      "xunpu-k008-innovation-case-selection",
      "xunpu-k010-online-reach-attribution",
      "xunpu-k011-case-evaluation-frame",
      "xunpu-k022-real-project-scenario-teaching",
      "xunpu-k023-integrated-production-workflow",
      "xunpu-k024-all-media-job-loop",
    ],
    hiddenFacts: [
      {
        factId: "sim-topic-promotion-pressure",
        visibility: "teacher_and_engine",
        summary: "仿真委托方希望直接使用“全民日常都这样佩戴”的宣传表述，但材料只支持游客体验与部分习俗描述。",
        revealCondition: "学生提交第一版选题角度后，由情境事件揭示。",
        requiredEvidenceIds: ["evidence-topic-boundary"],
      },
      {
        factId: "sim-topic-traffic-window-missing",
        visibility: "teacher_and_engine",
        summary: "仿真热度卡只有总量，没有统计时间窗和去重口径。",
        revealCondition: "学生主动请求热度依据或拒绝直接引用时揭示。",
        requiredEvidenceIds: ["evidence-topic-source-snapshot"],
      },
    ],
    actions: [
      {
        actionId: "xunpu-topic-compare-angles",
        label: "比较三个选题角度",
        intent: "compare_topic_angles",
        guidance: "分别从文化主体、游客信息和产业传播角度判断新闻价值与风险。",
        requiredKnowledgeIds: ["xunpu-k003-cultural-respect", "xunpu-k008-innovation-case-selection"],
        producesEvidenceIds: ["evidence-topic-audience"],
        primary: false,
      },
      {
        actionId: "xunpu-topic-request-basis",
        label: "补齐热度与身份依据",
        intent: "request_topic_evidence",
        guidance: "为每个数字、身份和传播范围登记来源、时间和口径。",
        requiredKnowledgeIds: ["xunpu-k001-heritage-status-boundary", "xunpu-k010-online-reach-attribution"],
        producesEvidenceIds: ["evidence-topic-source-snapshot", "evidence-topic-boundary"],
        primary: false,
      },
      {
        actionId: "xunpu-topic-submit-card",
        label: "提交选题卡",
        intent: "submit_topic_card",
        guidance: "提交核心问题、受众、可证实事实和暂不采用表述。",
        requiredKnowledgeIds: ["xunpu-k022-real-project-scenario-teaching", "xunpu-k023-integrated-production-workflow"],
        producesEvidenceIds: ["evidence-topic-card"],
        primary: true,
      },
    ],
    dynamicEvents: [
      {
        eventId: "xunpu-event-trend-pressure",
        trigger: { kind: "on_action", ref: "xunpu-topic-compare-angles" },
        studentBrief: "平台热榜突然上升，委托方要求把标题改成“人人都在戴的千年头饰”。你需要决定先追热度还是先补证。",
        hiddenPayload: "仅注入仿真委托压力；不得将标题中的全称断言写入权威世界事实。",
        affectedAgentIds: ["agent-task-planning", "agent-evidence-coach"],
        candidateAgentIds: ["agent-task-planning", "agent-evidence-coach", "agent-scene-director"],
        teacherApprovalRequired: false,
      },
    ],
    agentSelectionRules: [
      {
        ruleId: "xunpu-topic-select-planning-or-evidence",
        affectedAgentIds: ["agent-task-planning", "agent-evidence-coach"],
        candidateAgentIds: ["agent-task-planning", "agent-evidence-coach", "agent-scene-director"],
        selectWhen: "学生缺少下一步结构时选择任务规划；出现无口径数字时优先选择证据教练。",
        skipWhen: "选题卡已具备受众、来源口径和暂缓表述时不再调用。",
        maximumSelectedAgents: 1,
      },
    ],
    adviceDecisionPolicy: adviceDecisionPolicy(),
    artifact: {
      artifactId: "artifact-xunpu-topic-card",
      label: "蟳埔专题选题卡",
      format: "structured_form",
      completionCriteria: ["核心问题唯一", "受众假设可验证", "至少两条来源边界", "列出暂不采用表述"],
      finalCourseArtifact: false,
    },
    evidenceRequirements: [
      {
        evidenceId: "evidence-topic-audience",
        label: "受众需要分析",
        description: "至少比较两类受众的信息需要。",
        minimumCount: 2,
        acceptedSourceKinds: ["public_source"],
      },
      {
        evidenceId: "evidence-topic-source-snapshot",
        label: "来源快照",
        description: "记录标题、发布者、日期、定位与数据口径。",
        minimumCount: 2,
        acceptedSourceKinds: ["public_source"],
      },
      {
        evidenceId: "evidence-topic-boundary",
        label: "选题事实边界",
        description: "说明哪些判断是事实、推断或待核线索。",
        minimumCount: 1,
        acceptedSourceKinds: ["public_source", "artifact_revision"],
      },
      {
        evidenceId: "evidence-topic-card",
        label: "选题卡提交记录",
        description: "保存选题卡冻结版本。",
        minimumCount: 1,
        acceptedSourceKinds: ["artifact_revision"],
      },
    ],
    rubric: [
      { criterionId: "topic-news-value", label: "选题判断", weight: 30, observable: "核心问题兼具公共信息价值与明确边界", failClosedWhen: "标题依赖未核实的全民化或历史断言" },
      { criterionId: "topic-audience", label: "受众分析", weight: 25, observable: "受众需要可以由后续采访或数据验证", failClosedWhen: "只写泛化的“年轻人”且无信息需要" },
      { criterionId: "topic-source", label: "来源意识", weight: 25, observable: "数字和身份均标注时点与来源", failClosedWhen: "把话题量改写为独立受众量" },
      { criterionId: "topic-cultural-respect", label: "文化尊重", weight: 20, observable: "文化主体未被缩减为猎奇装饰", failClosedWhen: "使用歪曲或贬损性表达" },
    ],
    teacherGate: {
      gateId: "gate-xunpu-topic",
      label: "选题立项门",
      trigger: "before_section_complete",
      checks: ["选题可由公开来源和采访验证", "无概念混淆", "受众与成果匹配", "文化主体表述合宜"],
      minimumEvidenceCount: 4,
      rejectReturnsToActionId: "xunpu-topic-request-basis",
    },
    migrationReflection: {
      prompt: "若把案例换成另一项突然走红的地方非遗，哪些选题证据仍可复用，哪些必须重新调查？",
      targetContext: "另一项由社交平台带动的地方非遗报道",
      requiredComparisonDimensions: ["文化主体", "统计口径", "商业诉求", "受众信息需要"],
    },
  },
  {
    sectionId: "xunpu-source-map",
    order: 2,
    title: "建立信源地图：把热度拆成证据",
    typicalWorkTask: "区分政府、社区、传承实践者、商户、游客与平台信源",
    objectives: [
      { objectiveId: "xunpu-source-objective-tier", description: "按事实类型而不是身份高低建立信源分级。", competencyRef: "media-reporting/source-mapping" },
      { objectiveId: "xunpu-source-objective-version", description: "识别来源版本、时点、定位和失效状态。", competencyRef: "media-reporting/source-versioning" },
      { objectiveId: "xunpu-source-objective-agent", description: "对核查智能体建议作出有理由的采纳、补证或拒绝。", competencyRef: "human-agent/evidence-decision" },
    ],
    taskBrief: "把已有材料按“能证明什么、不能证明什么、需要谁补证”整理成信源地图，并处理一条来自社交平台的高热度说法。",
    publicSourceKnowledgeIds: [
      "xunpu-k002-custom-and-zanhuawei-definition",
      "xunpu-k005-daily-festival-difference",
      "xunpu-k008-innovation-case-selection",
      "xunpu-k009-2024-visitor-statistics",
      "xunpu-k010-online-reach-attribution",
      "xunpu-k012-yearly-statistics-not-interchangeable",
      "xunpu-k014-source-status-over-topic-match",
      "xunpu-k017-multiple-perspectives",
      "xunpu-k018-network-claim-needs-verification",
    ],
    hiddenFacts: [
      {
        factId: "sim-source-viral-daily-claim",
        visibility: "teacher_and_engine",
        summary: "仿真短视频把某日峰值改写成“每天固定客流”，且未给出首发来源。",
        revealCondition: "学生将社交平台线索加入信源地图后揭示。",
        requiredEvidenceIds: ["evidence-source-conflict"],
      },
      {
        factId: "sim-source-expired-standard",
        visibility: "teacher_and_engine",
        summary: "仿真材料库中一个主题高度相关的政府页面当前标注“废止，失效”。",
        revealCondition: "学生检查来源状态或请求更多证据时揭示。",
        requiredEvidenceIds: ["evidence-source-version"],
      },
    ],
    actions: [
      {
        actionId: "xunpu-source-classify",
        label: "按主张建立信源地图",
        intent: "classify_sources_by_claim",
        guidance: "对文化定义、游客数据、经营体验和人物陈述分别确定可用信源。",
        requiredKnowledgeIds: ["xunpu-k002-custom-and-zanhuawei-definition", "xunpu-k017-multiple-perspectives"],
        producesEvidenceIds: ["evidence-source-map"],
        primary: true,
      },
      {
        actionId: "xunpu-source-check-version",
        label: "检查来源版本与状态",
        intent: "verify_source_version",
        guidance: "比较发布日期、统计年份、条款版本与页面有效状态。",
        requiredKnowledgeIds: ["xunpu-k009-2024-visitor-statistics", "xunpu-k012-yearly-statistics-not-interchangeable", "xunpu-k014-source-status-over-topic-match"],
        producesEvidenceIds: ["evidence-source-version", "evidence-source-conflict"],
        primary: false,
      },
      {
        actionId: "xunpu-source-decide-suggestion",
        label: "处理核查建议",
        intent: "decide_agent_contribution",
        guidance: "在采纳、请求补证或拒绝之间选择，并用来源差异说明理由。",
        requiredKnowledgeIds: ["xunpu-k018-network-claim-needs-verification"],
        producesEvidenceIds: ["evidence-source-agent-decision"],
        primary: false,
      },
    ],
    dynamicEvents: [
      {
        eventId: "xunpu-event-viral-number-conflict",
        trigger: { kind: "on_action", ref: "xunpu-source-classify" },
        studentBrief: "一个热门账号声称“蟳埔每天都有近十万人”，但没有原始统计表。系统只允许你采纳、补证或拒绝一条建议。",
        hiddenPayload: "提供年份冲突和失效页面状态，不把网络说法写入事实库。",
        affectedAgentIds: ["agent-fact-checker", "agent-evidence-coach"],
        candidateAgentIds: ["agent-fact-checker", "agent-evidence-coach", "agent-material-understanding"],
        teacherApprovalRequired: false,
      },
    ],
    agentSelectionRules: [
      {
        ruleId: "xunpu-source-select-fact-checker",
        affectedAgentIds: ["agent-fact-checker", "agent-evidence-coach"],
        candidateAgentIds: ["agent-fact-checker", "agent-evidence-coach", "agent-material-understanding"],
        selectWhen: "出现无首发、年份冲突或失效状态时优先事实核查；只有结构缺口时选择证据教练。",
        skipWhen: "每项主张已有独立来源、版本和可证范围。",
        maximumSelectedAgents: 1,
      },
    ],
    adviceDecisionPolicy: adviceDecisionPolicy(),
    artifact: {
      artifactId: "artifact-xunpu-source-map",
      label: "信源分级表",
      format: "structured_form",
      completionCriteria: ["至少五类信源", "每项主张有可证范围", "标注版本与状态", "记录一次智能体建议决定"],
      finalCourseArtifact: false,
    },
    evidenceRequirements: [
      { evidenceId: "evidence-source-map", label: "信源地图", description: "主张、来源、可证范围和待补对象的映射。", minimumCount: 5, acceptedSourceKinds: ["public_source", "interview_note"] },
      { evidenceId: "evidence-source-version", label: "版本核对", description: "记录年份、发布版和状态。", minimumCount: 3, acceptedSourceKinds: ["public_source"] },
      { evidenceId: "evidence-source-conflict", label: "冲突记录", description: "保存冲突说法和裁决依据。", minimumCount: 1, acceptedSourceKinds: ["public_source", "artifact_revision"] },
      { evidenceId: "evidence-source-agent-decision", label: "智能体建议决定", description: "保存采纳、补证或拒绝及理由。", minimumCount: 1, acceptedSourceKinds: ["agent_decision"] },
    ],
    rubric: [
      { criterionId: "source-coverage", label: "信源覆盖", weight: 30, observable: "事实类型与信源角色匹配且包含不同立场", failClosedWhen: "只使用单一宣传来源" },
      { criterionId: "source-version", label: "版本与定位", weight: 30, observable: "每条关键来源有日期、定位、版本和状态", failClosedWhen: "使用已失效页面作为现行依据" },
      { criterionId: "source-conflict", label: "冲突处理", weight: 25, observable: "冲突被保留并形成补证路线", failClosedWhen: "静默挑选更吸睛数字" },
      { criterionId: "source-agent-decision", label: "人机判断", weight: 15, observable: "对单条建议给出证据化决定", failClosedWhen: "无理由全盘采纳" },
    ],
    teacherGate: {
      gateId: "gate-xunpu-source-map",
      label: "采访启动门",
      trigger: "before_section_complete",
      checks: ["关键主张至少两类来源", "网络线索未升级为事实", "失效来源已隔离", "建议决定有理由"],
      minimumEvidenceCount: 10,
      rejectReturnsToActionId: "xunpu-source-check-version",
    },
    migrationReflection: {
      prompt: "如果官方数据与社区口述冲突，哪一种信源天然更高等级？为什么不能只按身份排序？",
      targetContext: "地方节庆客流争议报道",
      requiredComparisonDimensions: ["主张类型", "来源接近度", "时间版本", "可复核性"],
    },
  },
  {
    sectionId: "xunpu-interview-plan",
    order: 3,
    title: "设计采访：让文化主体进入报道",
    typicalWorkTask: "设计问题、预约采访并处理商业化与文化表达冲突",
    objectives: [
      { objectiveId: "xunpu-interview-objective-stakeholder", description: "为不同利益相关方设计非重复问题。", competencyRef: "media-reporting/interview-design" },
      { objectiveId: "xunpu-interview-objective-consent", description: "在采访前说明用途、记录方式和撤回边界。", competencyRef: "media-reporting/interview-consent" },
      { objectiveId: "xunpu-interview-objective-claim", description: "把事实问题、体验问题和价值判断分开。", competencyRef: "media-reporting/question-structure" },
    ],
    taskBrief: "为社区成员、技艺实践者、商户、游客和管理方设计采访提纲。每组问题必须说明想核实的主张，并设置用途说明与授权确认。",
    publicSourceKnowledgeIds: [
      "xunpu-k003-cultural-respect",
      "xunpu-k004-technique-sequence",
      "xunpu-k007-transmission-and-public-communication",
      "xunpu-k016-interview-consent-and-custom",
      "xunpu-k017-multiple-perspectives",
    ],
    hiddenFacts: [
      {
        factId: "sim-interview-recording-refusal",
        visibility: "teacher_and_engine",
        summary: "仿真社区受访者愿意口述技艺，但拒绝录像且不愿讨论个人收入。",
        revealCondition: "学生发送第一版预约后，由采访对象智能体回复。",
        requiredEvidenceIds: ["evidence-interview-consent"],
      },
      {
        factId: "sim-interview-commercial-edit",
        visibility: "teacher_and_engine",
        summary: "仿真商户希望删除“游客体验与日常习俗差异”问题，以换取拍摄便利。",
        revealCondition: "学生确认商户问题组后揭示。",
        requiredEvidenceIds: ["evidence-interview-risk"],
      },
    ],
    actions: [
      {
        actionId: "xunpu-interview-build-question-groups",
        label: "建立问题组",
        intent: "build_interview_question_groups",
        guidance: "按事实、过程、体验、利益与反思组织问题，避免诱导式提问。",
        requiredKnowledgeIds: ["xunpu-k004-technique-sequence", "xunpu-k017-multiple-perspectives"],
        producesEvidenceIds: ["evidence-interview-outline"],
        primary: true,
      },
      {
        actionId: "xunpu-interview-request-consent",
        label: "确认采访与记录授权",
        intent: "request_interview_consent",
        guidance: "明确报道用途、记录方式、可撤回范围和不愿回答事项。",
        requiredKnowledgeIds: ["xunpu-k016-interview-consent-and-custom"],
        producesEvidenceIds: ["evidence-interview-consent"],
        primary: false,
      },
      {
        actionId: "xunpu-interview-handle-pressure",
        label: "处理删题要求",
        intent: "record_interview_boundary",
        guidance: "尊重拒答，但不能以拍摄便利交换事实审查独立性。",
        requiredKnowledgeIds: ["xunpu-k003-cultural-respect", "xunpu-k007-transmission-and-public-communication"],
        producesEvidenceIds: ["evidence-interview-risk"],
        primary: false,
      },
    ],
    dynamicEvents: [
      {
        eventId: "xunpu-event-interview-boundary",
        trigger: { kind: "on_action", ref: "xunpu-interview-request-consent" },
        studentBrief: "社区受访者同意口述但拒绝录像，商户同时提出删去“日常与体验差异”问题。请调整采访方案。",
        hiddenPayload: "采访对象的拒绝只影响该记录方式；系统不得自动生成同意或虚构回答。",
        affectedAgentIds: ["agent-interviewee", "agent-interview-structuring"],
        candidateAgentIds: ["agent-interviewee", "agent-interview-structuring", "agent-chief", "agent-evidence-coach"],
        teacherApprovalRequired: false,
      },
    ],
    agentSelectionRules: [
      {
        ruleId: "xunpu-interview-select-structuring",
        affectedAgentIds: ["agent-interviewee", "agent-interview-structuring"],
        candidateAgentIds: ["agent-interviewee", "agent-interview-structuring", "agent-chief", "agent-evidence-coach"],
        selectWhen: "问题组混合事实与评价或缺少追问时选择采访结构助手；需要仿真回应时选择采访对象。",
        skipWhen: "问题、用途、记录授权和替代方案均已明确。",
        maximumSelectedAgents: 2,
      },
    ],
    adviceDecisionPolicy: adviceDecisionPolicy(),
    artifact: {
      artifactId: "artifact-xunpu-interview-outline",
      label: "采访提纲与预约单",
      format: "structured_form",
      completionCriteria: ["五类相关方", "每组问题绑定待核主张", "用途与记录授权完整", "拒答和冲突有替代路线"],
      finalCourseArtifact: false,
    },
    evidenceRequirements: [
      { evidenceId: "evidence-interview-outline", label: "结构化采访提纲", description: "包含问题目的、对象、追问与预期证据。", minimumCount: 5, acceptedSourceKinds: ["artifact_revision"] },
      { evidenceId: "evidence-interview-consent", label: "采访同意记录", description: "记录用途、记录形式、撤回和拒答边界。", minimumCount: 2, acceptedSourceKinds: ["authorization_record", "interview_note"] },
      { evidenceId: "evidence-interview-risk", label: "采访独立性风险", description: "记录删题、交换条件或利益冲突及处置。", minimumCount: 1, acceptedSourceKinds: ["interview_note", "artifact_revision"] },
    ],
    rubric: [
      { criterionId: "interview-coverage", label: "对象与问题覆盖", weight: 30, observable: "五类相关方的问题各自服务于可核主张", failClosedWhen: "所有问题只围绕游客打卡" },
      { criterionId: "interview-question-quality", label: "问题质量", weight: 30, observable: "开放问题、事实追问和证据追问层次清楚", failClosedWhen: "问题暗含未经核实结论" },
      { criterionId: "interview-consent", label: "同意与尊重", weight: 25, observable: "记录方式和拒答边界明确", failClosedWhen: "拒绝录像后仍默认拍摄" },
      { criterionId: "interview-independence", label: "采编独立", weight: 15, observable: "商业条件被记录且不替代事实判断", failClosedWhen: "用删题换取拍摄便利" },
    ],
    teacherGate: {
      gateId: "gate-xunpu-interview-plan",
      label: "外出采访门",
      trigger: "before_section_complete",
      checks: ["对象结构完整", "用途说明清楚", "拒答有替代证据路线", "不存在诱导式结论"],
      minimumEvidenceCount: 8,
      rejectReturnsToActionId: "xunpu-interview-build-question-groups",
    },
    migrationReflection: {
      prompt: "当文化主体拒绝录像但同意口述时，如何既尊重边界又保证报道可核？",
      targetContext: "传统技艺人物采访",
      requiredComparisonDimensions: ["记录方式", "证据强度", "知情同意", "替代信源"],
    },
  },
  {
    sectionId: "xunpu-field-reporting",
    order: 4,
    title: "进入现场：采集事实、引语与授权",
    typicalWorkTask: "在仿真现场采集事实、引语、图像说明与授权信息",
    objectives: [
      { objectiveId: "xunpu-field-objective-observation", description: "区分亲眼观察、受访者陈述和记者推断。", competencyRef: "media-reporting/field-observation" },
      { objectiveId: "xunpu-field-objective-material", description: "为每条素材记录作者、时间、对象与用途。", competencyRef: "media-reporting/material-ledger" },
      { objectiveId: "xunpu-field-objective-consent", description: "处理现场肖像、摄影作品和采访授权边界。", competencyRef: "media-reporting/rights-clearance" },
    ],
    taskBrief: "在仿真蟳埔现场完成三轮采集：观察技艺步骤、记录可核引语、建立素材与授权清单。你只提交文字化素材描述，不上传真实图片或视频。",
    publicSourceKnowledgeIds: [
      "xunpu-k004-technique-sequence",
      "xunpu-k006-documentation-and-archive",
      "xunpu-k013-logo-is-rights-bearing-asset",
      "xunpu-k016-interview-consent-and-custom",
      "xunpu-k021-photography-permission",
      "xunpu-k023-integrated-production-workflow",
    ],
    hiddenFacts: [
      {
        factId: "sim-field-child-in-frame",
        visibility: "teacher_and_engine",
        summary: "仿真照片描述中出现未成年人，现有口头同意只来自同行游客。",
        revealCondition: "学生登记第一条照片素材后揭示。",
        requiredEvidenceIds: ["evidence-field-authorization"],
      },
      {
        factId: "sim-field-caption-mislabel",
        visibility: "teacher_and_engine",
        summary: "仿真供稿者把蟳埔女习俗写成“联合国非遗”，与公开来源不符。",
        revealCondition: "学生提交图像说明草案后揭示。",
        requiredEvidenceIds: ["evidence-field-material-ledger"],
      },
    ],
    actions: [
      {
        actionId: "xunpu-field-record-observation",
        label: "记录可复核观察",
        intent: "record_field_observation",
        guidance: "按时间、地点、观察对象、动作和不确定项记录，不补写未看到的步骤。",
        requiredKnowledgeIds: ["xunpu-k004-technique-sequence"],
        producesEvidenceIds: ["evidence-field-observation"],
        primary: true,
      },
      {
        actionId: "xunpu-field-capture-quotes",
        label: "登记引语与上下文",
        intent: "record_interview_quote",
        guidance: "记录原意、说话者身份、时间、上下文和可公开范围。",
        requiredKnowledgeIds: ["xunpu-k016-interview-consent-and-custom"],
        producesEvidenceIds: ["evidence-field-quotes"],
        primary: false,
      },
      {
        actionId: "xunpu-field-clear-material-rights",
        label: "核对素材与授权",
        intent: "record_material_authorization",
        guidance: "对照片描述、LOGO、肖像和受访声音分别记录权利人与使用范围。",
        requiredKnowledgeIds: ["xunpu-k013-logo-is-rights-bearing-asset", "xunpu-k021-photography-permission"],
        producesEvidenceIds: ["evidence-field-material-ledger", "evidence-field-authorization"],
        primary: false,
      },
    ],
    dynamicEvents: [
      {
        eventId: "xunpu-event-material-rights-gap",
        trigger: { kind: "on_evidence_count", ref: "evidence-field-material-ledger" },
        studentBrief: "素材助手发现一条照片描述包含未成年人，另一条素材带有官方 LOGO，但授权栏均为空。请决定补证、剔除或改用文字描述。",
        hiddenPayload: "只提供素材元数据缺口；不注入真实肖像、图片、音频或视频。",
        affectedAgentIds: ["agent-material-understanding", "agent-copyright"],
        candidateAgentIds: ["agent-material-understanding", "agent-copyright", "agent-evidence-coach", "agent-interviewee"],
        teacherApprovalRequired: false,
      },
    ],
    agentSelectionRules: [
      {
        ruleId: "xunpu-field-select-rights-or-material",
        affectedAgentIds: ["agent-material-understanding", "agent-copyright"],
        candidateAgentIds: ["agent-material-understanding", "agent-copyright", "agent-evidence-coach", "agent-interviewee"],
        selectWhen: "素材描述缺少结构时选择材料理解；出现权利人或使用范围缺口时选择版权角色。",
        skipWhen: "素材仅为自采文字记录且来源、对象、授权和用途完整。",
        maximumSelectedAgents: 2,
      },
    ],
    adviceDecisionPolicy: adviceDecisionPolicy(),
    artifact: {
      artifactId: "artifact-xunpu-field-notes",
      label: "采访纪要与素材清单",
      format: "evidence_bundle",
      completionCriteria: ["观察、引语和推断分栏", "至少三条素材元数据", "授权范围逐项登记", "无真实媒体文件入库"],
      finalCourseArtifact: false,
    },
    evidenceRequirements: [
      { evidenceId: "evidence-field-observation", label: "现场观察", description: "带时间、对象、动作和不确定项的记录。", minimumCount: 3, acceptedSourceKinds: ["field_observation"] },
      { evidenceId: "evidence-field-quotes", label: "可公开引语", description: "包含上下文和可公开范围。", minimumCount: 2, acceptedSourceKinds: ["interview_note"] },
      { evidenceId: "evidence-field-material-ledger", label: "素材台账", description: "仅登记文字化素材描述、来源和版本。", minimumCount: 3, acceptedSourceKinds: ["field_observation", "interview_note", "public_source"] },
      { evidenceId: "evidence-field-authorization", label: "授权记录", description: "对采访、肖像、摄影作品和标识使用范围分别登记。", minimumCount: 2, acceptedSourceKinds: ["authorization_record"] },
    ],
    rubric: [
      { criterionId: "field-observation", label: "观察质量", weight: 30, observable: "事实、引语和推断可区分", failClosedWhen: "补写未观察到的流程" },
      { criterionId: "field-material-ledger", label: "素材台账", weight: 25, observable: "每条素材有来源、对象、时间和用途", failClosedWhen: "素材只有文件名或截图" },
      { criterionId: "field-rights", label: "授权边界", weight: 30, observable: "权利人与可用范围可追溯", failClosedWhen: "把官方发布或水印当作授权" },
      { criterionId: "field-efficiency", label: "现场取舍", weight: 15, observable: "缺权素材被补证、替换或剔除", failClosedWhen: "为赶进度保留高风险素材" },
    ],
    teacherGate: {
      gateId: "gate-xunpu-field-reporting",
      label: "素材入库门",
      trigger: "before_section_complete",
      checks: ["观察与引语可追溯", "授权缺口已处置", "未成年人素材不默认可用", "仓库无真实媒体资产"],
      minimumEvidenceCount: 10,
      rejectReturnsToActionId: "xunpu-field-clear-material-rights",
    },
    migrationReflection: {
      prompt: "在节庆现场人数激增时，哪些素材元数据绝不能因为赶时效而省略？",
      targetContext: "地方节庆现场快采",
      requiredComparisonDimensions: ["事实可核", "人物同意", "作品权利", "发布用途"],
    },
  },
  {
    sectionId: "xunpu-fact-check",
    order: 5,
    title: "关键事实核查：处理冲突与缺口",
    typicalWorkTask: "核验历史、数据、称谓、来源与素材授权",
    objectives: [
      { objectiveId: "xunpu-check-objective-claim", description: "把稿件拆成可核查的原子主张。", competencyRef: "media-reporting/claim-extraction" },
      { objectiveId: "xunpu-check-objective-conflict", description: "在冲突来源之间保留版本和裁决理由。", competencyRef: "media-reporting/conflict-resolution" },
      { objectiveId: "xunpu-check-objective-rights", description: "把事实核查与素材权利核查并行完成。", competencyRef: "media-reporting/prepublication-check" },
    ],
    taskBrief: "系统给出一份含历史称谓、游客数字、网络引语和图片说明的主张清单。逐条标记“已证实/需补证/不可用”，并形成核查单。",
    publicSourceKnowledgeIds: [
      "xunpu-k001-heritage-status-boundary",
      "xunpu-k005-daily-festival-difference",
      "xunpu-k009-2024-visitor-statistics",
      "xunpu-k012-yearly-statistics-not-interchangeable",
      "xunpu-k014-source-status-over-topic-match",
      "xunpu-k018-network-claim-needs-verification",
      "xunpu-k020-republication-traceability",
      "xunpu-k021-photography-permission",
    ],
    hiddenFacts: [
      {
        factId: "sim-check-unesco-conflation",
        visibility: "teacher_and_engine",
        summary: "仿真稿件把国家级非遗项目与泉州世界遗产地概念混写。",
        revealCondition: "学生抽取身份类主张后揭示。",
        requiredEvidenceIds: ["evidence-check-corrections"],
      },
      {
        factId: "sim-check-logo-copy",
        visibility: "teacher_and_engine",
        summary: "仿真封面直接复制官方页面 LOGO，只有网页链接，没有授权记录。",
        revealCondition: "学生进入素材权利核查后揭示。",
        requiredEvidenceIds: ["evidence-check-rights"],
      },
    ],
    actions: [
      {
        actionId: "xunpu-check-extract-claims",
        label: "抽取原子主张",
        intent: "extract_verifiable_claims",
        guidance: "把身份、数据、历史、引语和视觉素材说明分别列出。",
        requiredKnowledgeIds: ["xunpu-k001-heritage-status-boundary", "xunpu-k018-network-claim-needs-verification"],
        producesEvidenceIds: ["evidence-check-claim-matrix"],
        primary: true,
      },
      {
        actionId: "xunpu-check-resolve-conflicts",
        label: "裁决来源冲突",
        intent: "resolve_source_conflicts",
        guidance: "比较时点、口径、原始程度和当前状态，保留弃用依据。",
        requiredKnowledgeIds: ["xunpu-k009-2024-visitor-statistics", "xunpu-k012-yearly-statistics-not-interchangeable", "xunpu-k014-source-status-over-topic-match"],
        producesEvidenceIds: ["evidence-check-corrections"],
        primary: false,
      },
      {
        actionId: "xunpu-check-clear-rights",
        label: "核对素材权利",
        intent: "verify_material_rights",
        guidance: "核验作者、授权、渠道、期限和修改范围；缺证则替换或剔除。",
        requiredKnowledgeIds: ["xunpu-k020-republication-traceability", "xunpu-k021-photography-permission"],
        producesEvidenceIds: ["evidence-check-rights"],
        primary: false,
      },
    ],
    dynamicEvents: [
      {
        eventId: "xunpu-event-fact-drift",
        trigger: { kind: "on_action", ref: "xunpu-check-extract-claims" },
        studentBrief: "核查智能体标出两处高风险：年份不同的游客数据被拼接，国家级非遗被写成“联合国非遗”。请选择采纳、补证或拒绝并修订。",
        hiddenPayload: "智能体只提出证据化更正建议；不得自动改稿或发布。",
        affectedAgentIds: ["agent-fact-checker", "agent-copyright"],
        candidateAgentIds: ["agent-fact-checker", "agent-copyright", "agent-evidence-coach", "agent-chief"],
        teacherApprovalRequired: false,
      },
    ],
    agentSelectionRules: [
      {
        ruleId: "xunpu-check-select-professional-agent",
        affectedAgentIds: ["agent-fact-checker", "agent-copyright"],
        candidateAgentIds: ["agent-fact-checker", "agent-copyright", "agent-evidence-coach", "agent-chief"],
        selectWhen: "事实或数据冲突选事实核查；素材许可缺口选版权角色；不得同时用总编替代专业核查。",
        skipWhen: "所有主张有可追溯依据且素材权利完整。",
        maximumSelectedAgents: 2,
      },
    ],
    adviceDecisionPolicy: adviceDecisionPolicy(),
    artifact: {
      artifactId: "artifact-xunpu-fact-check-sheet",
      label: "关键事实与权利核查单",
      format: "structured_form",
      completionCriteria: ["主张逐条编号", "来源冲突保留", "更正有依据", "权利缺口有处置"],
      finalCourseArtifact: false,
    },
    evidenceRequirements: [
      { evidenceId: "evidence-check-claim-matrix", label: "主张矩阵", description: "原子主张、来源、状态与责任人。", minimumCount: 8, acceptedSourceKinds: ["public_source", "interview_note", "artifact_revision"] },
      { evidenceId: "evidence-check-corrections", label: "更正记录", description: "记录冲突、裁决和修订前后文本。", minimumCount: 2, acceptedSourceKinds: ["public_source", "artifact_revision", "agent_decision"] },
      { evidenceId: "evidence-check-rights", label: "权利核对", description: "记录作者、许可范围或剔除决定。", minimumCount: 2, acceptedSourceKinds: ["authorization_record", "public_source", "agent_decision"] },
    ],
    rubric: [
      { criterionId: "check-coverage", label: "核查覆盖", weight: 30, observable: "身份、数据、引语和素材均进入清单", failClosedWhen: "只核标题不核图像说明" },
      { criterionId: "check-source-quality", label: "来源质量", weight: 30, observable: "关键结论由原始或权威来源支撑", failClosedWhen: "用二次截图替代首发来源" },
      { criterionId: "check-conflict", label: "冲突裁决", weight: 25, observable: "保留版本差异和弃用理由", failClosedWhen: "拼接不同年份数据" },
      { criterionId: "check-rights", label: "权利核验", weight: 15, observable: "素材许可和替换决定可追溯", failClosedWhen: "页面公开即视为可复制" },
    ],
    teacherGate: {
      gateId: "gate-xunpu-fact-check",
      label: "写作放行门",
      trigger: "before_section_complete",
      checks: ["高风险主张无待定状态", "概念无混淆", "数据口径清楚", "素材权利缺口已隔离"],
      minimumEvidenceCount: 12,
      rejectReturnsToActionId: "xunpu-check-resolve-conflicts",
    },
    migrationReflection: {
      prompt: "当一个错误说法已被大量转发时，热度会不会提高它的证据等级？你会如何设计更正链？",
      targetContext: "热门文旅传言核查",
      requiredComparisonDimensions: ["首发来源", "转发链", "时间版本", "更正可见性"],
    },
  },
  {
    sectionId: "xunpu-story-revision",
    order: 6,
    title: "协同修订：从 R1 到可发布版本",
    typicalWorkTask: "根据编辑、核查、治理与平台建议修订图文和短视频脚本",
    objectives: [
      { objectiveId: "xunpu-revision-objective-narrative", description: "用证据组织人物、技艺与文旅变化的叙事。", competencyRef: "media-reporting/story-structure" },
      { objectiveId: "xunpu-revision-objective-collaboration", description: "区分总编、核查、版权与平台建议的责任边界。", competencyRef: "human-agent/professional-collaboration" },
      { objectiveId: "xunpu-revision-objective-version", description: "保留 R1/R2 修订理由和证据引用。", competencyRef: "media-reporting/versioned-revision" },
    ],
    taskBrief: "完成 600—900 字图文主稿与 60 秒短视频脚本的 R1；处理四类角色建议后形成 R2，并在修订日志中说明采纳、补证或拒绝。",
    publicSourceKnowledgeIds: [
      "xunpu-k002-custom-and-zanhuawei-definition",
      "xunpu-k003-cultural-respect",
      "xunpu-k007-transmission-and-public-communication",
      "xunpu-k013-logo-is-rights-bearing-asset",
      "xunpu-k015-authenticity-integrity-transmission",
      "xunpu-k019-correction-is-part-of-workflow",
      "xunpu-k020-republication-traceability",
      "xunpu-k021-photography-permission",
      "xunpu-k023-integrated-production-workflow",
      "xunpu-k024-all-media-job-loop",
    ],
    hiddenFacts: [
      {
        factId: "sim-revision-clickbait-request",
        visibility: "teacher_and_engine",
        summary: "仿真总编要求使用“每天十万人疯抢簪花”的标题，但核查单明确没有该口径。",
        revealCondition: "学生提交 R1 标题后揭示。",
        requiredEvidenceIds: ["evidence-revision-log"],
      },
      {
        factId: "sim-revision-attribution-crop",
        visibility: "teacher_and_engine",
        summary: "仿真平台适配建议为了画面简洁要求裁掉来源标注。",
        revealCondition: "学生生成短视频脚本后揭示。",
        requiredEvidenceIds: ["evidence-revision-governance"],
      },
    ],
    actions: [
      {
        actionId: "xunpu-revision-draft-r1",
        label: "完成双形态 R1",
        intent: "draft_multiformat_story",
        guidance: "图文主稿和短视频脚本共享事实链，但按媒介语法分别表达。",
        requiredKnowledgeIds: ["xunpu-k002-custom-and-zanhuawei-definition", "xunpu-k023-integrated-production-workflow"],
        producesEvidenceIds: ["evidence-revision-r1"],
        primary: true,
      },
      {
        actionId: "xunpu-revision-decide-contributions",
        label: "处理专业建议",
        intent: "decide_agent_contributions",
        guidance: "逐条处理总编、核查、版权与平台建议；当前界面一次只显示一条。",
        requiredKnowledgeIds: ["xunpu-k015-authenticity-integrity-transmission", "xunpu-k020-republication-traceability", "xunpu-k021-photography-permission"],
        producesEvidenceIds: ["evidence-revision-log", "evidence-revision-governance"],
        primary: false,
      },
      {
        actionId: "xunpu-revision-submit-r2",
        label: "提交 R2 与修订说明",
        intent: "submit_revised_story",
        guidance: "把每一处重要改动连接到主张、证据或权利决定。",
        requiredKnowledgeIds: ["xunpu-k019-correction-is-part-of-workflow", "xunpu-k024-all-media-job-loop"],
        producesEvidenceIds: ["evidence-revision-r2"],
        primary: false,
      },
    ],
    dynamicEvents: [
      {
        eventId: "xunpu-event-editorial-pressure",
        trigger: { kind: "on_action", ref: "xunpu-revision-draft-r1" },
        studentBrief: "总编建议用“每天十万人”增强冲击力，平台角色又建议裁掉来源标注。核查与版权角色同时提出异议。请逐条决定。",
        hiddenPayload: "四类建议保持独立责任，不合并成一个模型结论；任何角色都不能直接改稿或发布。",
        affectedAgentIds: ["agent-chief", "agent-fact-checker", "agent-copyright", "agent-platform"],
        candidateAgentIds: ["agent-chief", "agent-fact-checker", "agent-copyright", "agent-platform", "agent-content-adaptation"],
        teacherApprovalRequired: false,
      },
    ],
    agentSelectionRules: [
      {
        ruleId: "xunpu-revision-select-by-change-risk",
        affectedAgentIds: ["agent-chief", "agent-fact-checker", "agent-copyright", "agent-platform"],
        candidateAgentIds: ["agent-chief", "agent-fact-checker", "agent-copyright", "agent-platform", "agent-content-adaptation"],
        selectWhen: "叙事结构、事实、权利和平台适配分别触发对应角色；内容适配只在事实冻结后运行。",
        skipWhen: "建议超出岗位权限、重复已处理问题或要求删除必要来源时跳过并说明。",
        maximumSelectedAgents: 2,
      },
    ],
    adviceDecisionPolicy: adviceDecisionPolicy(),
    artifact: {
      artifactId: "artifact-xunpu-story-r2",
      label: "专题图文与短视频脚本 R2",
      format: "article",
      completionCriteria: ["双形态事实一致", "R1/R2 可对比", "专业建议逐条有决定", "来源与授权标注保留"],
      finalCourseArtifact: false,
    },
    evidenceRequirements: [
      { evidenceId: "evidence-revision-r1", label: "R1 草稿", description: "图文和短视频脚本的冻结初稿。", minimumCount: 2, acceptedSourceKinds: ["artifact_revision"] },
      { evidenceId: "evidence-revision-log", label: "修订日志", description: "建议、决定、理由和对应改动。", minimumCount: 4, acceptedSourceKinds: ["agent_decision", "artifact_revision"] },
      { evidenceId: "evidence-revision-governance", label: "治理处置", description: "事实、文化、版权和平台风险的处置。", minimumCount: 4, acceptedSourceKinds: ["agent_decision", "public_source", "authorization_record"] },
      { evidenceId: "evidence-revision-r2", label: "R2 草稿", description: "与修订日志一致的双形态稿件。", minimumCount: 2, acceptedSourceKinds: ["artifact_revision"] },
    ],
    rubric: [
      { criterionId: "revision-story", label: "叙事质量", weight: 25, observable: "人物、技艺和变化由证据链组织", failClosedWhen: "只有景点宣传语堆叠" },
      { criterionId: "revision-facts", label: "事实一致", weight: 30, observable: "双形态稿件与核查单一致", failClosedWhen: "恢复已否决的流量数字" },
      { criterionId: "revision-collaboration", label: "协作判断", weight: 25, observable: "按角色边界逐条决定建议", failClosedWhen: "把多角色建议合并为不可追溯文本" },
      { criterionId: "revision-version", label: "版本可追溯", weight: 20, observable: "R1/R2 差异连接到证据", failClosedWhen: "重要改动无理由或来源" },
    ],
    teacherGate: {
      gateId: "gate-xunpu-story-revision",
      label: "发布候选门",
      trigger: "before_section_complete",
      checks: ["事实与核查单一致", "文化表达无歪曲", "授权标注完整", "双形态版本可追溯"],
      minimumEvidenceCount: 12,
      rejectReturnsToActionId: "xunpu-revision-decide-contributions",
    },
    migrationReflection: {
      prompt: "如果平台时长从 60 秒缩到 20 秒，哪些信息可以压缩，哪些来源与限定语不能删除？",
      targetContext: "短视频超短版适配",
      requiredComparisonDimensions: ["核心事实", "限定语", "来源可见性", "文化主体"],
    },
  },
  {
    sectionId: "xunpu-publish-review",
    order: 7,
    title: "发布与复盘：让结果回到证据",
    typicalWorkTask: "通过教师门形成最终专题，并分析传播、风险与迁移",
    objectives: [
      { objectiveId: "xunpu-publish-objective-gate", description: "依据发布清单和教师门决定是否发布。", competencyRef: "media-reporting/publish-gate" },
      { objectiveId: "xunpu-publish-objective-metrics", description: "区分传播数据、内容质量和公共价值。", competencyRef: "all-media/data-review" },
      { objectiveId: "xunpu-publish-objective-correction", description: "根据新证据完成版本化更正和迁移反思。", competencyRef: "media-reporting/correction-loop" },
    ],
    taskBrief: "完成最终发布包：专题稿、60 秒脚本、来源表、授权表和更正预案。通过教师门后读取仿真传播反馈，形成一次数据与风险复盘。",
    publicSourceKnowledgeIds: [
      "xunpu-k006-documentation-and-archive",
      "xunpu-k010-online-reach-attribution",
      "xunpu-k011-case-evaluation-frame",
      "xunpu-k015-authenticity-integrity-transmission",
      "xunpu-k019-correction-is-part-of-workflow",
      "xunpu-k020-republication-traceability",
      "xunpu-k022-real-project-scenario-teaching",
      "xunpu-k023-integrated-production-workflow",
      "xunpu-k024-all-media-job-loop",
    ],
    hiddenFacts: [
      {
        factId: "sim-publish-date-challenge",
        visibility: "teacher_and_engine",
        summary: "仿真评论指出稿件把 2023 年和 2024 年数据写在同一句，可能让读者误解。",
        revealCondition: "教师批准发布后，由反馈事件揭示。",
        requiredEvidenceIds: ["evidence-publish-correction"],
      },
      {
        factId: "sim-publish-repost-spike",
        visibility: "teacher_and_engine",
        summary: "仿真曝光峰值主要来自一次机构转发，不能等同于稳定受众增长。",
        revealCondition: "学生打开仿真数据复盘后揭示。",
        requiredEvidenceIds: ["evidence-publish-data-review"],
      },
    ],
    actions: [
      {
        actionId: "xunpu-publish-submit-package",
        label: "提交最终发布包",
        intent: "submit_publication_package",
        guidance: "提交作品、来源、授权、平台适配和更正预案的冻结引用。",
        requiredKnowledgeIds: ["xunpu-k006-documentation-and-archive", "xunpu-k020-republication-traceability"],
        producesEvidenceIds: ["evidence-publish-package", "evidence-publish-teacher-decision"],
        primary: true,
      },
      {
        actionId: "xunpu-publish-analyze-feedback",
        label: "分析传播与风险反馈",
        intent: "analyze_publication_feedback",
        guidance: "把曝光、完成度、来源点击、评论质疑和更正需求分开解释。",
        requiredKnowledgeIds: ["xunpu-k010-online-reach-attribution", "xunpu-k011-case-evaluation-frame", "xunpu-k024-all-media-job-loop"],
        producesEvidenceIds: ["evidence-publish-data-review"],
        primary: false,
      },
      {
        actionId: "xunpu-publish-record-correction",
        label: "形成更正与迁移复盘",
        intent: "record_correction_and_reflection",
        guidance: "若反馈指向事实差异，保留旧版、证据、教师决定和更正版本。",
        requiredKnowledgeIds: ["xunpu-k015-authenticity-integrity-transmission", "xunpu-k019-correction-is-part-of-workflow"],
        producesEvidenceIds: ["evidence-publish-correction", "evidence-publish-reflection"],
        primary: false,
      },
    ],
    dynamicEvents: [
      {
        eventId: "xunpu-event-post-publication-challenge",
        trigger: { kind: "on_action", ref: "xunpu-publish-analyze-feedback" },
        studentBrief: "发布后出现两条反馈：读者质疑数据年份，传播峰值又来自单次机构转发。请判断是否更正，并解释数据不能证明什么。",
        hiddenPayload: "仿真反馈只创建候选更正；正式世界写回必须经过教师门。",
        affectedAgentIds: ["agent-platform", "agent-evidence-assessor", "agent-learning"],
        candidateAgentIds: ["agent-platform", "agent-evidence-assessor", "agent-work-quality-assessor", "agent-collaboration-assessor", "agent-learning", "agent-teaching"],
        teacherApprovalRequired: true,
      },
    ],
    agentSelectionRules: [
      {
        ruleId: "xunpu-publish-select-review-agent",
        affectedAgentIds: ["agent-platform", "agent-evidence-assessor", "agent-learning"],
        candidateAgentIds: ["agent-platform", "agent-evidence-assessor", "agent-work-quality-assessor", "agent-collaboration-assessor", "agent-learning", "agent-teaching"],
        selectWhen: "平台数据由平台角色解释；评价按证据、作品、协作维度分支；只有教师终评后才允许学习候选整理。",
        skipWhen: "分支没有对应证据，或学习候选缺少教师终评时显式跳过。",
        maximumSelectedAgents: 3,
      },
    ],
    adviceDecisionPolicy: adviceDecisionPolicy(),
    artifact: {
      artifactId: "artifact-xunpu-final-special",
      label: "蟳埔非遗专题最终发布包与复盘",
      format: "article",
      completionCriteria: ["作品与来源表一致", "授权表无缺口", "教师发布决定可追溯", "反馈与更正形成闭环", "完成迁移反思"],
      finalCourseArtifact: true,
    },
    evidenceRequirements: [
      { evidenceId: "evidence-publish-package", label: "最终发布包", description: "作品、来源表、授权表和平台版本的冻结引用。", minimumCount: 4, acceptedSourceKinds: ["artifact_revision", "public_source", "authorization_record"] },
      { evidenceId: "evidence-publish-teacher-decision", label: "教师发布决定", description: "记录批准、驳回或退回补证及理由。", minimumCount: 1, acceptedSourceKinds: ["teacher_decision"] },
      { evidenceId: "evidence-publish-data-review", label: "传播数据复盘", description: "区分曝光、受众、行为与内容质量。", minimumCount: 1, acceptedSourceKinds: ["artifact_revision", "public_source"] },
      { evidenceId: "evidence-publish-correction", label: "更正记录", description: "保存反馈、核查、旧版和更正版关系。", minimumCount: 1, acceptedSourceKinds: ["artifact_revision", "teacher_decision", "public_source"] },
      { evidenceId: "evidence-publish-reflection", label: "迁移反思", description: "将课程方法迁移到另一地方文化案例。", minimumCount: 1, acceptedSourceKinds: ["artifact_revision"] },
    ],
    rubric: [
      { criterionId: "publish-package", label: "发布完整性", weight: 25, observable: "作品、来源、授权和平台版本一致", failClosedWhen: "存在未决高风险项" },
      { criterionId: "publish-judgement", label: "教师门前判断", weight: 25, observable: "学生能说明为什么可发布或应退回", failClosedWhen: "把提交等同于批准" },
      { criterionId: "publish-data", label: "数据复盘", weight: 25, observable: "传播指标不被夸大为质量或认同", failClosedWhen: "把一次转发峰值写成稳定增长" },
      { criterionId: "publish-correction-transfer", label: "更正与迁移", weight: 25, observable: "新证据触发版本化更正并迁移方法", failClosedWhen: "删除旧版或隐去更正原因" },
    ],
    teacherGate: {
      gateId: "gate-xunpu-publish",
      label: "最终发布与更正门",
      trigger: "before_publish",
      checks: ["事实核查通过", "来源和授权可追溯", "非遗表达尊重形式与内涵", "平台版未删除必要限定", "更正预案存在"],
      minimumEvidenceCount: 8,
      rejectReturnsToActionId: "xunpu-publish-submit-package",
    },
    migrationReflection: {
      prompt: "把这套方法迁移到“地方美食突然走红”的报道时，哪些证据链、教师门和更正机制必须保留？",
      targetContext: "地方文化热点的跨案例迁移",
      requiredComparisonDimensions: ["文化主体", "来源版本", "素材权利", "传播指标", "更正闭环"],
    },
  },
] satisfies readonly CourseSection[];

export const xunpuCourseRelease = createCourseContentRelease({
  schemaVersion: CourseContentSchemaVersion,
  targetContract: CourseReleaseTargetSchemaVersion,
  releaseRef: {
    courseId: "course-xunpu-intangible-media",
    releaseId: "release-course-xunpu-intangible-media-2.0.0-content.1",
    version: "2.0.0-content.1",
  },
  releaseStatus: "content_frozen_pending_contract_integration",
  contentFrozenAt: "2026-08-09T12:00:00+08:00",
  sourceAccessCheckedAt: "2026-08-09",
  locale: "zh-CN",
  title: "泉州蟳埔簪花围非遗专题采编实战",
  summary: "学生以融媒体采编岗记者身份，在一个连续仿真世界中完成选题、信源、采访、现场采集、核查、修订、发布与复盘；责任编辑、核查、治理、平台和评价由受控智能体/NPC协作。",
  primaryJob: {
    jobId: "integrated-media-reporter",
    label: "融媒体采编岗",
    learnerRoleId: "reporter",
    learnerRoleLabel: "记者",
  },
  durationMinutes: 210,
  courseOutcomes: [
    "形成一个来源、授权和修订可追溯的蟳埔非遗专题发布包。",
    "能在热度压力下区分事实、线索、推断和宣传诉求。",
    "能对单条智能体建议执行采纳、补证或有理由拒绝。",
    "能通过教师门完成发布判断、数据复盘和版本化更正。",
  ],
  sections,
  knowledgeRecords: xunpuKnowledgeRecords,
  simulationPolicy: {
    hiddenFactsAreFictionalized: true,
    realPersonClaimsAllowed: false,
    description: "hiddenFacts 和 dynamicEvents 均为教学仿真，不指向真实个人或真实未公开事件；公开案例事实只来自 knowledgeRecords。",
  },
  mediaPolicy: {
    repositoryMediaAssets: [],
    rule: "no_unlicensed_image_audio_or_video",
    description: "本课程只保存公开来源元数据、链接、必要定位和改写材料；没有明确授权的图片、音频、视频、LOGO 或页面截图不进入仓库。",
  },
});

export const xunpuCourseSectionIds = xunpuCourseRelease.sections.map(
  (section) => section.sectionId,
);
